### ISSUE TITLE
BUG: Failed to Fetch modules / next can't find react.

### ISSUE THREAD

**Issue by IanSSenne** [stackblitz/webcontainer-core#10]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: 'bug'
assignees: ''

---

**Describe the bug**

**Link to the blitz that caused the error**
https://stackblitz.com/github/mc-build/mcbuild.dev?file=package.json

**To Reproduce**
1. Go to https://stackblitz.com/github/mc-build/mcbuild.dev?file=package.json
2. See error

**Expected behavior**
react and react-dom are not found by next although they are in the package.json file under dependencies.
 * this may be due to an error with module resolution `HttpError: Failed to fetch dependencies`

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 59938551,
  usedJSHeapSize: 56875467,
  jsHeapSizeLimit: 4294705152
}

**Additional context**
# terminal log
```sh
/projects/nbwiorvzn.github
❯ npm install && npx next dev
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 21.922s
┌ [2/3] 🚚  Fetching dependencies
└ 𐄂 Failed
HttpError: Failed to fetch dependencies

error Command failed with exit code 1
success Install finished in 7.539s

The module 'react' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react'
The module 'react-dom' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react-dom'
Error: Cannot find module 'react'
Require stack:
- /.turbo/npx/DT8K2j/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (https://nbwiorvzn--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:185516)
    at Function.Module._load (https://nbwiorvzn--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:183130)
    at Module.require (https://nbwiorvzn--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:186304)
    at i (https://nbwiorvzn--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:484674)
    at _0x1e5cfd (https://nbwiorvzn--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19724)
    at Object.eval (/.turbo/npx/DT8K2j/node_modules/next/dist/bin/next:25:13)
    at Object.function (https://nbwiorvzn--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19819)
    at Module._compile (https://nbwiorvzn--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187549)
    at Object.Module._extensions..js (https://nbwiorvzn--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187908)
    at Module.load (https://nbwiorvzn--github.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:185988) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/.turbo/npx/DT8K2j/node_modules/next/dist/bin/next' ]
}

error Command failed with exit code 1

/projects/nbwiorvzn.github 39s
❯ 

/projects/nbwiorvzn.github
❯ 
```

**Comment by jonathansampson** [comment]
I believe I ran into this earlier as well; running the `build` command resolved.

**Comment by KwintenP** [comment]
Hi!

🙏 for reporting. This does seem like a bug on our end!

**Comment by d3lm** [comment]
Hey there, the issue with installing the dependencies has been fixed. However, I am seeing CORS errors for the Google Fonts API which is unrelated to this ticket. Therefore I am going to close this one and have tracked the CORS error internally. Feel free to open a new issue if you run into anything else.
