### ISSUE TITLE
BUG: Module not found when i use nest command 

### ISSUE THREAD

**Issue by RawZ06** [stackblitz/webcontainer-core#100]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
When i run `nest` command to generate for example a module `nest generate module my-module`, i receive an error

```
Error: Cannot find module '/projects/nestjs-template/node_modules/@angular-devkit/schematics-cli/bin/schematics.js" @nestjs/schematics:sub-app --name=service --no-dry-run --collection="@nestjs/schematics" --language="ts" --sourceRoot="src'
    at Function.Module._resolveFilename (https://nestjs-template.jw.staticblitz.com/blitz.57be275669708b1d42e233d60c80159bef577631.js:6:185516)
    at Function.Module._load (https://nestjs-template.jw.staticblitz.com/blitz.57be275669708b1d42e233d60c80159bef577631.js:6:183130)
    at Function.executeUserEntryPoint [as runMain] (https://nestjs-template.jw.staticblitz.com/blitz.57be275669708b1d42e233d60c80159bef577631.js:6:794697)
    at Object.a0_0x2054 (https://nestjs-template.jw.staticblitz.com/blitz.57be275669708b1d42e233d60c80159bef577631.js:6:1395283)
    at _0x3318cc (https://nestjs-template.jw.staticblitz.com/blitz.57be275669708b1d42e233d60c80159bef577631.js:8:21813)
    at _0x5b1fdf (https://nestjs-template.jw.staticblitz.com/blitz.57be275669708b1d42e233d60c80159bef577631.js:11:162780)
    at _0x2adfc6 (https://nestjs-template.jw.staticblitz.com/blitz.57be275669708b1d42e233d60c80159bef577631.js:11:131623)
    at Object.run (https://nestjs-template.jw.staticblitz.com/blitz.57be275669708b1d42e233d60c80159bef577631.js:11:130796) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Failed to execute command: node @nestjs/schematics:sub-app --name=service --no-dry-run --collection="@nestjs/schematics" --language="ts" --sourceRoot="src" --spec
```

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nestjs-template-m4bpef?file=.estlintrc.js

**To Reproduce**
1. Go to project
2. Execute nest command `nest generate module my-module'
3. See error

**Version of webcontainer**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots**
![image](https://user-images.githubusercontent.com/44646690/119710798-147f7500-be5f-11eb-8f01-a4fbb0de3e0a.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 74475169,
  usedJSHeapSize: 69530685,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by KwintenP** [comment]
Hey,

This seems like a bug! I can't seem to open the blitz anymore. Did you delete it by any chance?

Could you provide a new repro link? 🙏

**Comment by RawZ06** [comment]
Oups, yes, i created a new here : https://stackblitz.com/edit/nestjs-template-deslul?file=package.json

**Comment by KwintenP** [comment]
This seems to be an issue indeed. Thanks for adding the link.

**Comment by jrvidal** [comment]
@RawZ06 Is this still an issue? The last repro link seems to be gone.

**Comment by AlexandreLon** [comment]
This error was fixed, thank you.
