### ISSUE TITLE
NextJS middleware doesn't work

### ISSUE THREAD

**Issue by drfattytuna** [stackblitz/webcontainer-core#1044]
### Describe the bug

If you create a new generic next.js fullstack starter project and add middleware to it the app crashes with the following error:

```
error - Error [TypeError]: runtime.context.addEventListener is not a function
    at createModuleContext (file:///home/projects/nextjs-7gaz28/node_modules/next/dist/server/web/sandbox/context.js:229:21)
    at async Object.getModuleContext (file:///home/projects/nextjs-7gaz28/node_modules/next/dist/server/web/sandbox/context.js:253:25)
    at async getRuntimeContext (file:///home/projects/nextjs-7gaz28/node_modules/next/dist/server/web/sandbox/sandbox.js:37:46)
    at async eval (file:///home/projects/nextjs-7gaz28/node_modules/next/dist/server/web/sandbox/sandbox.js:53:21)
    at async DevServer.runMiddleware (file:///home/projects/nextjs-7gaz28/node_modules/next/dist/server/next-server.js:1122:24)
    at async DevServer.runMiddleware (file:///home/projects/nextjs-7gaz28/node_modules/next/dist/server/dev/next-dev-server.js:644:28)
    at async Object.fn (file:///home/projects/nextjs-7gaz28/node_modules/next/dist/server/next-server.js:1201:38)
    at async Router.execute (file:///home/projects/nextjs-7gaz28/node_modules/next/dist/server/router.js:252:36)
    at async DevServer.run (file:///home/projects/nextjs-7gaz28/node_modules/next/dist/server/base-server.js:383:29)
    at async DevServer.run (file:///home/projects/nextjs-7gaz28/node_modules/next/dist/server/dev/next-dev-server.js:734:20) {
  middleware: true
}
```

It seems it can't find the runtime context for the nextjs server.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-7gaz28?file=middleware.js

### Steps to reproduce

1. Load a fullstack next.js application (can use template on main site)
2. Add middleware, doesn't need to have anything in it

### Expected behavior

Middleware should work without crashing the server

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 112.0.5615.49

**Comment by jordn** [comment]
I have the same issue, but no middleware. I'll create a second ticket in case its different: https://github.com/stackblitz/webcontainer-core/issues/1193

**Comment by SamVerschueren** [comment]
Thanks for the bug report. We investigated it and deployed a fix. Have a good weekend 👋 !
