### ISSUE TITLE
Webcontainer not starting on chrome 112 (32 bit)

### ISSUE THREAD

**Issue by seriousme** [stackblitz/webcontainer-core#1058]
### Describe the bug

Trying to open https://stackblitz.com/edit/vitejs-vite-str6qk?file=index.html&terminal=dev
shows the editor but reports on the right pane: `failed to boot webcontainer`

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-str6qk?file=index.html&terminal=dev

### Steps to reproduce

1. Open the blitz
2. Wait a few seconds
3. View the error

### Expected behavior

A booted webcontainer

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 112.0.0.0
Major version = 112
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 56746870,
  "usedJSHeapSize": 55007858,
  "jsHeapSizeLimit": 1043857408
}
Hash = d830b1a2
```

### Additional context

The device is a ChromeOS tablet, but I read that StackBlitz also runs on an iPad ;-)

The Chrome console reports:
```
client-77c97378d00fa.js:2 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
e._parseColor @ client-77c97378d00fa.js:2
(index):6736 crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):6736
client-77c97378d00fa.js:2 RuntimeError: unreachable
    at 166eabc2
    at 166eabc2
    at _0x4af1c5 (blitz.d830b1a2.js:44:37511)
    at _0x4d8d0c (blitz.d830b1a2.js:44:38627)
    at async _0x36ac2d._initSlabAsync (blitz.d830b1a2.js:44:41450)
    at async _0x36ac2d.create (blitz.d830b1a2.js:44:39135)
    at async _0x2d156c.init (blitz.d830b1a2.js:63:39384)
(anonymous) @ client-77c97378d00fa.js:2
client-77c97378d00fa.js:2 Something went wrong RuntimeError: unreachable
    at 166eabc2
    at 166eabc2
    at _0x4af1c5 (blitz.d830b1a2.js:44:37511)
    at _0x4d8d0c (blitz.d830b1a2.js:44:38627)
    at async _0x36ac2d._initSlabAsync (blitz.d830b1a2.js:44:41450)
    at async _0x36ac2d.create (blitz.d830b1a2.js:44:39135)
    at async _0x2d156c.init (blitz.d830b1a2.js:63:39384)
(anonymous) @ client-77c97378d00fa.js:2
webcontainer.d830b1a2.js:1 Uncaught (in promise) RuntimeError: unreachable
    at 166eabc2
    at 166eabc2
    at _0x4af1c5 (blitz.d830b1a2.js:44:37511)
    at _0x4d8d0c (blitz.d830b1a2.js:44:38627)
    at async _0x36ac2d._initSlabAsync (blitz.d830b1a2.js:44:41450)
    at async _0x36ac2d.create (blitz.d830b1a2.js:44:39135)
    at async _0x2d156c.init (blitz.d830b1a2.js:63:39384)
webcontainer.d830b1a2.js:1 Uncaught (in promise) RuntimeError: unreachable
    at 166eabc2
    at 166eabc2
    at _0x4af1c5 (blitz.d830b1a2.js:44:37511)
    at _0x4d8d0c (blitz.d830b1a2.js:44:38627)
    at async _0x36ac2d._initSlabAsync (blitz.d830b1a2.js:44:41450)
    at async _0x36ac2d.create (blitz.d830b1a2.js:44:39135)
    at async _0x2d156c.init (blitz.d830b1a2.js:63:39384)
webcontainer.d830b1a2.js:1 Uncaught (in promise) RuntimeError: unreachable
    at 166eabc2
    at 166eabc2
    at _0x4af1c5 (blitz.d830b1a2.js:44:37511)
    at _0x4d8d0c (blitz.d830b1a2.js:44:38627)
    at async _0x36ac2d._initSlabAsync (blitz.d830b1a2.js:44:41450)
    at async _0x36ac2d.create (blitz.d830b1a2.js:44:39135)
    at async _0x2d156c.init (blitz.d830b1a2.js:63:39384)
vitejs-vite-str6qk:1 Uncaught (in promise) RuntimeError: unreachable
    at 166eabc2
    at 166eabc2
    at _0x4af1c5 (blitz.d830b1a2.js:44:37511)
    at _0x4d8d0c (blitz.d830b1a2.js:44:38627)
    at async _0x36ac2d._initSlabAsync (blitz.d830b1a2.js:44:41450)
    at async _0x36ac2d.create (blitz.d830b1a2.js:44:39135)
    at async _0x2d156c.init (blitz.d830b1a2.js:63:39384)
vitejs-vite-str6qk:1 Uncaught (in promise) RuntimeError: unreachable
    at 166eabc2
    at 166eabc2
    at _0x4af1c5 (blitz.d830b1a2.js:44:37511)
    at _0x4d8d0c (blitz.d830b1a2.js:44:38627)
    at async _0x36ac2d._initSlabAsync (blitz.d830b1a2.js:44:41450)
    at async _0x36ac2d.create (blitz.d830b1a2.js:44:39135)
    at async _0x2d156c.init (blitz.d830b1a2.js:63:39384)
vitejs-vite-str6qk:1 Uncaught (in promise) RuntimeError: unreachable
    at 166eabc2
    at 166eabc2
    at _0x4af1c5 (blitz.d830b1a2.js:44:37511)
    at _0x4d8d0c (blitz.d830b1a2.js:44:38627)
    at async _0x36ac2d._initSlabAsync (blitz.d830b1a2.js:44:41450)
    at async _0x36ac2d.create (blitz.d830b1a2.js:44:39135)
    at async _0x2d156c.init (blitz.d830b1a2.js:63:39384)
vitejs-vite-str6qk:1 Uncaught (in promise) RuntimeError: unreachable
    at 166eabc2
    at 166eabc2
    at _0x4af1c5 (blitz.d830b1a2.js:44:37511)
    at _0x4d8d0c (blitz.d830b1a2.js:44:38627)
    at async _0x36ac2d._initSlabAsync (blitz.d830b1a2.js:44:41450)
    at async _0x36ac2d.create (blitz.d830b1a2.js:44:39135)
    at async _0x2d156c.init (blitz.d830b1a2.js:63:39384)
vitejs-vite-str6qk:1 Uncaught (in promise) RuntimeError: unreachable
    at 166eabc2
    at 166eabc2
    at _0x4af1c5 (blitz.d830b1a2.js:44:37511)
    at _0x4d8d0c (blitz.d830b1a2.js:44:38627)
    at async _0x36ac2d._initSlabAsync (blitz.d830b1a2.js:44:41450)
    at async _0x36ac2d.create (blitz.d830b1a2.js:44:39135)
    at async _0x2d156c.init (blitz.d830b1a2.js:63:39384)
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
vitejs-vite-str6qk:7 [Violation] 'setInterval' handler took 62ms

```

**Comment by jrvidal** [comment]
We're now tracking this internally, we have a general idea of what it might be happening.

We suspect it is related to memory constraints in your device. Do you always get the same error? What if you reboot and open your project before doing anything else with the device?

**Comment by seriousme** [comment]
Ok, just did another test directly after reboot.
Exactly the same error log. I diffed it and it is only missing the last few lines `The resource <URL> was preloaded using..` because I didn't let it run that long.
My first guess would be memory as well given that its a tablet, however the same blitz works on my other chromebook (non-tablet) that has the same 4 GB of RAM while having VScode open in a Linux container ;-)

The chromebook has an Intel Celeron N4000  and Chrome and Chrome OS report as 64 bits, where on the tablet its a MediaTek Helio P60T (ARM CPU) where Chrome and Chrome OS reports as 32 bits.

So it might be a quirck in the Intel vs ARM versions of Chrome.

I tried running Fabrice Bellards jslinux (https://bellard.org/jslinux/)
Both console and X-windows versions seem to run fine on the tablet. (althouh the X version is rather slow on both machines ;-))

Hope this helps !

Kind regards,
Hans
ps. I don't *need* a solution, so no problem if you close the issue, just wanted to let you know ;-)

**Comment by seriousme** [comment]
When running the demo on https://pkg-size.dev on the tablet using chrome 114.0.5735.205 (32 bits)
I get:
```
ebcontainer.bec01ace.js:1 Uncaught (in promise) RuntimeError: unreachable
    at w-corp.staticblitz.com/fs_bg.bec01ace.wasm
    at w-corp.staticblitz.com/fs_bg.bec01ace.wasm
    at _0x434fdc (blitz.bec01ace.js:37:136266)
    at _0x1c636d (blitz.bec01ace.js:37:137880)
    at async _0x36e1f4.initFileSystem (blitz.bec01ace.js:42:477184)
    at async _0x3b3336.init (blitz.bec01ace.js:42:515277)
deserialize @ webcontainer.bec01ace.js:1
_0xb788e7 @ webcontainer.bec01ace.js:1
await in _0xb788e7 (async)
addLazyFileHandler @ webcontainer.bec01ace.js:1
U @ headless-c3b3aedf.js:1
factory @ headless-c3b3aedf.js:1
await in factory (async)
_unsynchronizedBuild @ webcontainer.bec01ace.js:1
_build @ webcontainer.bec01ace.js:1
build @ webcontainer.bec01ace.js:1
apply @ webcontainer.bec01ace.js:1
_0x613c38 @ webcontainer.bec01ace.js:1
webcontainer.bec01ace.js:1 Uncaught (in promise) RuntimeError: unreachable
    at w-corp.staticblitz.com/fs_bg.bec01ace.wasm
    at w-corp.staticblitz.com/fs_bg.bec01ace.wasm
    at _0x434fdc (blitz.bec01ace.js:37:136266)
    at _0x1c636d (blitz.bec01ace.js:37:137880)
    at async _0x36e1f4.initFileSystem (blitz.bec01ace.js:42:477184)
    at async _0x3b3336.init (blitz.bec01ace.js:42:515277)
deserialize @ webcontainer.bec01ace.js:1
_0xb788e7 @ webcontainer.bec01ace.js:1
await in _0xb788e7 (async)
addLazyFileHandler @ webcontainer.bec01ace.js:1
$ @ headless-c3b3aedf.js:1
factory @ headless-c3b3aedf.js:1
await in factory (async)
_unsynchronizedBuild @ webcontainer.bec01ace.js:1
_build @ webcontainer.bec01ace.js:1
build @ webcontainer.bec01ace.js:1
apply @ webcontainer.bec01ace.js:1
_0x613c38 @ webcontainer.bec01ace.js:1
index-0d761363.js:2 Uncaught (in promise) RuntimeError: unreachable
    at w-corp.staticblitz.com/fs_bg.bec01ace.wasm
    at w-corp.staticblitz.com/fs_bg.bec01ace.wasm
    at _0x434fdc (blitz.bec01ace.js:37:136266)
    at _0x1c636d (blitz.bec01ace.js:37:137880)
    at async _0x36e1f4.initFileSystem (blitz.bec01ace.js:42:477184)
    at async _0x3b3336.init (blitz.bec01ace.js:42:515277)
index-0d761363.js:1 Uncaught (in promise) RuntimeError: unreachable
    at w-corp.staticblitz.com/fs_bg.bec01ace.wasm
    at w-corp.staticblitz.com/fs_bg.bec01ace.wasm
    at _0x434fdc (blitz.bec01ace.js:37:136266)
    at _0x1c636d (blitz.bec01ace.js:37:137880)
    at async _0x36e1f4.initFileSystem (blitz.bec01ace.js:42:477184)
    at async _0x3b3336.init (blitz.bec01ace.js:42:515277)
headless:1 The resource https://w-corp.staticblitz.com/fetch.worker.bec01ace.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
headless:1 The resource https://w-corp.staticblitz.com/fetch.worker.bec01ace.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
Maybe this gives more insight.
To me it feels like a bug in the ARM32 implementation of WASM in Chrome, but I could be wrong ;-)

Kind regards,
Hans

**Comment by seriousme** [comment]
Just tried again on  `version 117.0.5938.144 (Official build) (32-bits)` and there is good news: it works!!
