### ISSUE TITLE
Inconsistent Module Resolution

### ISSUE THREAD

**Issue by skeep-exogee** [stackblitz/webcontainer-core#1137]
### Describe the bug

Running `npx graphweaver@latest init` from within a Node.js v16.20.0 env works as expected.

Running the same command in a webcontainer produces the error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/.npm/_npx/e8eab1776c427c85/node_modules/lightningcss/index.mjs not supported.
Instead change the require of /home/.npm/_npx/e8eab1776c427c85/node_modules/lightningcss/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at InternalError.get (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:35:385022)
    at getStackString (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:35:120434)
    at <anonymous> (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:35:115969)
    at <anonymous> (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:35:117659)
    at formatValue (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:35:120024)
    at inspect (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:35:108834)
    at _0x399238 (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:42:168580)
    at _0x4ebb65 (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:37:139334)
    at <anonymous> (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:42:113030)
    at process._0xacb050 (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:42:113054)
    at _0x4eee2d (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:37:289103)
    at _0x10b863 (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:61:2530)
    at _0x5971b2.run (https://httplocalhost5173-b5wu.w-corp.staticblitz.com/blitz.bec01ace.js:61:960) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-wphfrv?file=main.js

### Steps to reproduce

A reproduction of the issue is here:

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-wphfrv?file=main.js

### Expected behavior

The cli tool should run as it does in a native environment.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SamVerschueren** [comment]
Hey @skeep-exogee 👋 . Thanks for reaching out! This looks like an issue on our side indeed. I've created an internal ticket for this.
