### ISSUE TITLE
Error: `line` must be greater than 0 (lines start at line 1)

### ISSUE THREAD

**Issue by archiewood** [stackblitz/webcontainer-core#1158]
### Describe the bug

This project runs in my local machine but not on Stackblitz.

The server boots, but then it throws an error before displaying any output in the side-by-side preview window.

It appears to be some kind of runtime error, which is difficult to understand.

## Full trace

```
  VITE v4.0.4  ready in 2052 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h to show help
Error: `line` must be greater than 0 (lines start at line 1)
RuntimeError: abort(Error: `line` must be greater than 0 (lines start at line 1)). Build with -s ASSERTIONS=1 for more info.
    at process.abort (file:///home/projects/evidence-dw7cb2/node_modules/@evidence-dev/sqlite/node_modules/sqlite3/lib/sqlite3.pure.js:1:10598)
    at EventEmitter.emit (https://evidencedw7cb2-kmb1.w-credentialless.staticblitz.com/blitz.d5d65229.js:45:8318)
    at emit (https://evidencedw7cb2-kmb1.w-credentialless.staticblitz.com/blitz.d5d65229.js:249:1157)
    at processPromiseRejections (https://evidencedw7cb2-kmb1.w-credentialless.staticblitz.com/blitz.d5d65229.js:249:3678)
    at processTicksAndRejections (https://evidencedw7cb2-kmb1.w-credentialless.staticblitz.com/blitz.d5d65229.js:111:1108)
    at _0x3bb3d0 (https://evidencedw7cb2-kmb1.w-credentialless.staticblitz.com/blitz.d5d65229.js:329:284508)
    at _0xe470ca (https://evidencedw7cb2-kmb1.w-credentialless.staticblitz.com/blitz.d5d65229.js:334:161880)
    at https://evidencedw7cb2-kmb1.w-credentialless.staticblitz.com/blitz.d5d65229.js:334:161684

~/projects/evidence-dw7cb2 14s
❯ fatal error: too many writes on closed pipe

goroutine 6 [running]:
runtime.throw({0x95c7a, 0x1e})
        runtime/panic.go:1047 +0x3 fp=0x83aee0 sp=0x83aeb8 pc=0x122b0003
os.sigpipe()
        runtime/os_js.go:144 +0x2 fp=0x83aef8 sp=0x83aee0 pc=0x139b0002
os.epipecheck(...)
        os/file_unix.go:195
os.(*File).Write(0x80c020, {0x5464e00, 0x150, 0x200})
        os/file.go:184 +0x27 fp=0x83af80 sp=0x83aef8 pc=0x15e30027
main.runService.func1()
        github.com/evanw/esbuild/cmd/esbuild/service.go:112 +0x9 fp=0x83afe0 sp=0x83af80 pc=0x1ed00009
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x83afe8 sp=0x83afe0 pc=0x13ea0001
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:109 +0x1e
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/evidence-dw7cb2?file=pages%2Findex.md,package.json

### Steps to reproduce

Open blitz in Chrome, wait for it to boot

### Expected behavior

Preview window shows content stored in /page.md

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 115.0.0.0
Major version = 115
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76943101,
  "usedJSHeapSize": 70239341,
  "jsHeapSizeLimit": 4294705152
}
Hash = d5d65229
```

**Comment by sammyfilly** [comment]
Line must start with 1

**Comment by Nemikolh** [comment]
Hi @archiewood! Thanks for the report and sorry for the late reply!

Looks like someone else saw a similar looking bug which might help debugging this issue.
