### ISSUE TITLE
SB throws `out2Clone.tee is not a function or its return value is not iterable`

### ISSUE THREAD

**Issue by mhevery** [stackblitz/webcontainer-core#1172]
### Describe the bug

SB throws `out2Clone.tee is not a function or its return value is not iterable`

### Link to the blitz that caused the error

https://stackblitz.com/edit/qwik-starter-up7tax

### Steps to reproduce

1. open project.
2. in the field enter some new todo item text.
3. Click `Add item`
4. Observer this exception: `out2Clone.tee is not a function or its return value is not iterable`
```
[vite] Internal server error: out2Clone.tee is not a function or its return value is not iterable
      at cloneBody (file:///home/projects/qwik-starter-up7tax/node_modules/undici/lib/fetch/body.js:284:36)
      at cloneRequest (file:///home/projects/qwik-starter-up7tax/node_modules/undici/lib/fetch/request.js:806:23)
      at Request.clone (file:///home/projects/qwik-starter-up7tax/node_modules/undici/lib/fetch/request.js:715:27)
      at parseRequest (file:///home/projects/qwik-starter-up7tax/node_modules/@builder.io/qwik-city/vite/index.cjs:24953:23)
      at Object.parseBody (file:///home/projects/qwik-starter-up7tax/node_modules/@builder.io/qwik-city/vite/index.cjs:24907:28)
      at eval (file:///home/projects/qwik-starter-up7tax/node_modules/@builder.io/qwik-city/vite/index.cjs:24374:40)
      at Object.next (file:///home/projects/qwik-starter-up7tax/node_modules/@builder.io/qwik-city/vite/index.cjs:24759:22)
      at handleRedirect (file:///home/projects/qwik-starter-up7tax/node_modules/@builder.io/qwik-city/vite/index.cjs:24576:23)
      at Object.next (file:///home/projects/qwik-starter-up7tax/node_modules/@builder.io/qwik-city/vite/index.cjs:24759:22)
      at renderQData (file:///home/projects/qwik-starter-up7tax/node_modules/@builder.io/qwik-city/vite/index.cjs:24604:21)
 ```

### Expected behavior

Not throw exception and return the data from server.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Nemikolh** [comment]
Hey @mhevery! We're currently upgrading to node 18 and in the process we have fixed this issue. We don't have an exact ETA just yet for when it will be released but we can keep you posted here. 😃

**Comment by SamVerschueren** [comment]
Closing this as it has been fixed now 🙏 .

**Comment by mhevery** [comment]
Thank you, you rock!
