### ISSUE TITLE
Nextjs app: `runtime.context.addEventListener is not a function` 

### ISSUE THREAD

**Issue by jordn** [stackblitz/webcontainer-core#1193]
### Describe the bug

TypeError: runtime.context.addEventListener is not a function
    at createModuleContext (file:///home/projects/github-7va1zg/node_modules/next/dist/server/web/sandbox/context.js:326:21)
    at async getModuleContext (file:///home/projects/github-7va1zg/node_modules/next/dist/server/web/sandbox/context.js:346:71)
    at async getRuntimeContext (file:///home/projects/github-7va1zg/node_modules/next/dist/server/web/sandbox/sandbox.js:58:46)
    at async runWithTaggedErrors (file:///home/projects/github-7va1zg/node_modules/next/dist/server/web/sandbox/sandbox.js:75:21)
    at async DevServer.runEdgeFunction (file:///home/projects/github-7va1zg/node_modules/next/dist/server/next-server.js:1241:24)
    at async DevServer.handleCatchallRenderRequest (file:///home/projects/github-7va1zg/node_modules/next/dist/server/next-server.js:664:55)
    at async DevServer.handleRequestImpl (file:///home/projects/github-7va1zg/node_modules/next/dist/server/base-server.js:647:17) {
  type: 'TypeError'
}

### Link to the blitz that caused the error

https://stackblitz.com/github/humanloop/chatbot-starter

### Steps to reproduce

Just let this repo run. It will build, but then fail to work.

This is a simplified version of the Nextjs example chatbot app.

### Expected behavior

Should have a rendered chatbot app (it wont respond without API keys but should all work)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1912" alt="Screenshot 2023-09-26 at 21 24 19" src="https://github.com/stackblitz/webcontainer-core/assets/1463197/d5050be6-fff1-45a8-94b8-11e250ce14b7">

### Platform

- OS: macOs 13.5.2
- Browser: Chrome
- Version:  117.0.5938.62

### Additional context

Likely related to https://github.com/stackblitz/webcontainer-core/issues/1044 except its not middleware related for me.

**Comment by SamVerschueren** [comment]
This is now fixed. It was kind of related to #1044, but there was also something else. Anyways, `humanloop` now boots.

<img width="1713" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/1913805/9486b1d2-93e8-425d-9e67-e92d2502b865">
