### ISSUE TITLE
BUG: Adding `sass` as dependency only works after a page refresh

### ISSUE THREAD

**Issue by SamVerschueren** [stackblitz/webcontainer-core#12]
**Describe the bug**
@trezy tried WebContainer live on Twitch and ran into the issue where `next dev` fails to build after installing `sass`. After a page refresh it works.

**Link to the blitz that caused the error**

**To Reproduce**
1. Create a new [Next.js](https://stackblitz.com/fork/nextjs) project
2. Stop the build process and run `turbo add sass`
3. Start the server with `turbo dev`
```
/projects/nextjs-cp1rsm
❯ turbo dev
$ next dev
TypeError: Class extends value undefined is not a constructor or null
    at Object.618 (/projects/nextjs-cp1rsm/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:161)
    at __nccwpck_require__ (/projects/nextjs-cp1rsm/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11796)
    at Object.270 (/projects/nextjs-cp1rsm/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:474)
    at __nccwpck_require__ (/projects/nextjs-cp1rsm/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11796)
    at Object.327 (/projects/nextjs-cp1rsm/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:321)
    at __nccwpck_require__ (/projects/nextjs-cp1rsm/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11796)
    at Object.845 (/projects/nextjs-cp1rsm/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3794)
    at __nccwpck_require__ (/projects/nextjs-cp1rsm/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11796)
    at eval (/projects/nextjs-cp1rsm/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11924)
    at Object.eval (/projects/nextjs-cp1rsm/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11950)
```
4. Reload the page and now `turbo dev` works 🎉 

**Expected behavior**
After running `turbo add sass`, the `turbo dev` command should just work.

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1
 - Browser Chrome
 - Version 91

**Additional context**
/

**Comment by trezy** [comment]
Here's a clip from the stream in case it helps: https://www.twitch.tv/videos/1029419054

**Comment by SamVerschueren** [comment]
This seems to be working now. Closing the issue. If anyone experience this error with `node-sass` or with another package, feel free to open a new issue.
