### ISSUE TITLE
Codeflow server crashed: Installed Neovim extension

### ISSUE THREAD

**Issue by 2B1Kenobi** [stackblitz/webcontainer-core#1209]
### Describe the bug

I installed this plugin
```
Name: VSCode Neovim
Id: asvetliakov.vscode-neovim
Description: VSCode Neovim Integration
Version: 0.9.0
Publisher: asvetliakov
VS Marketplace Link: https://open-vsx.org/vscode/item?itemName=asvetliakov.vscode-neovim
```

And the server has been crashing ever since. I guess the environment isn't designed to handle this plugin yet.

But another problem surfaced, and it's trying to uninstall the extension before the server crashes. Uninstalling the extension is unable to complete before the server crashes. After multiple attempts of trying to uninstall the extension, I managed to uninstall it by immediately disabling the extension on boot and then uninstalling it.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/2B1Kenobi/kodego-miniproject2

### Steps to reproduce

1. Install the [Neovim extension](https://open-vsx.org/vscode/item?itemName=asvetliakov.vscode-neovim).
2. Server will crash.

### Expected behavior

Be able to run Vim Mode with the Neovim extension.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.80.0
Hash = a0abf0747572ea6e64ff1736404cdf76336c29d4
WebContainer = 7a1fe16d

Browser name  = Chrome
Full version  = 117.0.0.0
Major version = 117
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 90821899,
  "usedJSHeapSize": 65536251,
  "jsHeapSizeLimit": 2172649472
}
```

### Additional context

Server bound to /usr/share/codeflow/.ipc-socket
Extension host agent listening on /usr/share/codeflow/.ipc-socket

[16:29:10] 

[16:29:10] Extension host agent started.
[16:29:10] [<unknown>][9de014ae][ManagementConnection] New connection established.
[16:29:10] [<unknown>][2c4a343e][ExtensionHostConnection] New connection established.
[16:29:10] [<unknown>][2c4a343e][ExtensionHostConnection] <5> Launched Extension Host Process.
[16:29:14] Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
    at __node_internal_ (https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:36:5410)
    at new <anonymous> (https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:36:4172)
    at readableAddChunk (https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:105:3639)
    at Readable.push (https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:105:2679)
    at _0x431028.onStreamRead [as onread] (https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:158:2341)
    at Object.emit (https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:350:314783)
    at _0x39a9b7 (https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:350:316394)
    at https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:350:317061
    at Array.forEach (<anonymous>)
    at _flushBuffer (https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:350:317049)
    at Map.forEach (<anonymous>)
    at https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:350:315591
    at _0x235de8 (https://kodegominiproject2-4dds.w-credentialless.staticblitz.com/blitz.7a1fe16d.js:350:315660) {
  code: 'ERR_STREAM_PUSH_AFTER_EOF'
}

**Comment by samdenty** [comment]
Hi there thanks for reporting this error. I can reproduce and will look into this on monday

**Comment by samdenty** [comment]
i'll add a `Reset data` option in the crash screen, since it was hard for you to uninstall the extension.

![CleanShot 2023-10-14 at 15 33 49@2x](https://github.com/stackblitz/webcontainer-core/assets/13242392/64f872d9-cf3f-483d-9d41-5ceb89ede7e6)

**Comment by samdenty** [comment]
Ok so I looked into it, and this extension is unsupported because it uses native binaries specifically `nvim`. We're currently using openvsx because we didn't manage to setup our own registry yet, but when we do these sorts of extensions will be filtered out.

Until there's an open source build of neovim compiling to wasi [(someone did it, but looks like it's not open source)](https://github.com/neovim/neovim/issues/19863#issuecomment-1694325623), we won't be able to support it. If you want it though I'd suggest leaving comments on neovim repo

**Comment by samdenty** [comment]
we've also just fixed the issue with the server crashing, now you'll just get a notification instead of an unrecoverable crash screen

![CleanShot 2023-10-16 at 17 46 42@2x](https://github.com/stackblitz/webcontainer-core/assets/13242392/608a3f33-1bc1-426a-8589-3d30414be134)
