### ISSUE TITLE
Live example for Angular Tour of Heroes, 3, does not work

### ISSUE THREAD

**Issue by Gluups** [stackblitz/webcontainer-core#1247]
### Describe the bug

Hello everybody,

Google has a nice feature: the online demonstration of their projects.

But for the third part of the Tour of Heroes, ["Create a freature component"](https://angular.io/generated/live-examples/toh-pt3/stackblitz.html), it does not work, it stays stuck at "Running start command", where it has run the whole night, opposite to the two first ones, that worked like a charm.

Is there a problem on my machine?

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Fheroes%2Fheroes.component.html

### Steps to reproduce

Just click on the link I gave.
It comes from [https://angular.io/tutorial/tour-of-heroes/toh-pt3](url), "live example".

### Expected behavior

Show the execution on the right.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

[
![Angular exemple 3 Capture d'écran 2023-11-11 100136](https://github.com/stackblitz/webcontainer-core/assets/6567976/9126c6e3-60fe-408d-96ff-4a01e5231ce4)
](url)

### Platform

```
Browser name  = Firefox
Full version  = 119.0
Major version = 119
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
performance.memory = undefined
Hash = 5a198b5c
```

**Comment by Gluups** [comment]
"Link to the blitz that caused the error" : do you succeed on clicking on this?
I do not, it sends to the start page of Stackblitz.
You really need to click where I said in the bug description, 
https://angular.io/generated/live-examples/toh-pt3/stackblitz.html

**Comment by Gluups** [comment]
I have difficulties to find the app.module.ts file.

**Comment by Gluups** [comment]
If I download the project and run locally (link "download example" rather than "live example") the results is different:

`** Angular Live Development Server is listening on localhost:44479, open your browser on https://localhost:44479/ **


× Failed to compile.
Error: ENOENT: no such file or directory, open 'C:/Projects Visual Studio/Web/Angular_tohpt3/Angular_tohpt3/ClientApp/src/polyfills.ts'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at NodeJSFileSystem.readFile (file:///C:/Projects%20Visual%20Studio/Web/Angular_tohpt3/Angular_tohpt3/ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-TBUSSXUA.js:332:16)
    at EsmDependencyHost.recursivelyCollectDependencies (file:///C:/Projects%20Visual%20Studio/Web/Angular_tohpt3/Angular_tohpt3/ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-EKN42M4J.js:213:34)
    at EsmDependencyHost.processFile (file:///C:/Projects%20Visual%20Studio/Web/Angular_tohpt3/Angular_tohpt3/ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-EKN42M4J.js:242:12)
    at EsmDependencyHost.collectDependenciesInFiles (file:///C:/Projects%20Visual%20Studio/Web/Angular_tohpt3/Angular_tohpt3/ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-EKN42M4J.js:209:12)
    at ProgramBasedEntryPointFinder.getInitialEntryPointPaths (file:///C:/Projects%20Visual%20Studio/Web/Angular_tohpt3/Angular_tohpt3/ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-EKN42M4J.js:860:10)
    at ProgramBasedEntryPointFinder.findEntryPoints (file:///C:/Projects%20Visual%20Studio/Web/Angular_tohpt3/Angular_tohpt3/ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-EKN42M4J.js:819:35)
    at file:///C:/Projects%20Visual%20Studio/Web/Angular_tohpt3/Angular_tohpt3/ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-EKN42M4J.js:1269:33
    at new ClusterMaster (file:///C:/Projects%20Visual%20Studio/Web/Angular_tohpt3/Angular_tohpt3/ClientApp/node_modules/@angular/compiler-cli/bundles/chunk-EKN42M4J.js:1371:22)

Initial Chunk Files | Names   | Raw Size
runtime.js          | runtime |  6.53 kB |

4 unchanged chunks

Build at: 2023-11-11T09:51:54.154Z - Hash: 8d2bd6c2b5b7ae5b - Time: 1067ms

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

Error: Module not found: Error: Can't resolve 'src/polyfills.ts' in 'C:\Projects Visual Studio\Web\Angular_tohpt3\Angular_tohpt3\ClientApp'

Error: Failed to initialize Angular compilation - NGCC failed.
`

**Comment by Gluups** [comment]
Sorry, I forgot to get polyfills.ts from another project.
Locally it then runs OK.

**Comment by SamVerschueren** [comment]
You are right, it doesn't seem to be working in Firefox for some reason. It does seem to work in Chrome (for me at least). I'll create an internal ticket.
