### ISSUE TITLE
Codeflow server crashed

### ISSUE THREAD

**Issue by Graca98** [stackblitz/webcontainer-core#1266]
### Describe the bug

I looged into github account and now my IDE cannot load

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/Graca98/nextj-tailwind-online

### Steps to reproduce

Create a nextjs + tailwind IDE
log into github
IDE freezes and take all the ram

### Expected behavior

IDE loading

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 88b6330a54335025782a7d449b67b3486a435a31
WebContainer = 6843a59c

Browser name  = Chrome
Full version  = 119.0.0.0
Major version = 119
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 100706715,
  "usedJSHeapSize": 76592559,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Error: Cannot find module '/usr/share/codeflow/out/server-main.js'
    at Module._resolveFilename (https://nextjtailwindonline-dvu2.w-credentialless.staticblitz.com/blitz.6843a59c.js:55:12642)
    at Module._load (https://nextjtailwindonline-dvu2.w-credentialless.staticblitz.com/blitz.6843a59c.js:55:10056)
    at Function.executeUserEntryPoint [as runMain] (https://nextjtailwindonline-dvu2.w-credentialless.staticblitz.com/blitz.6843a59c.js:125:731)
    at https://nextjtailwindonline-dvu2.w-credentialless.staticblitz.com/blitz.6843a59c.js:318:166
    at Object._0x10770f (https://nextjtailwindonline-dvu2.w-credentialless.staticblitz.com/blitz.6843a59c.js:318:186)
    at _0xa98e92 (https://nextjtailwindonline-dvu2.w-credentialless.staticblitz.com/blitz.6843a59c.js:350:54422)
    at _0x1ed627 (https://nextjtailwindonline-dvu2.w-credentialless.staticblitz.com/blitz.6843a59c.js:352:105784)
    at _0x18c668.executeBootstrapper (https://nextjtailwindonline-dvu2.w-credentialless.staticblitz.com/blitz.6843a59c.js:352:598038)
    at _0x2ecff7.startExecution (https://nextjtailwindonline-dvu2.w-credentialless.staticblitz.com/blitz.6843a59c.js:371:2840)
    at _0x2ecff7.run (https://nextjtailwindonline-dvu2.w-credentialless.staticblitz.com/blitz.6843a59c.js:371:1381) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by Graca98** [comment]
W11, 16GB Ram

No issues now. Works perfectly. Thank you!

**Comment by Nemikolh** [comment]
Oh interesting, we do have issues with Chrome on Windows under 16GB of RAM or less. See #970 for similar issues. I'll close this for now but feel free to comment over there if you run again into issues. :+1:
