### ISSUE TITLE
StackBlitz server crashed

### ISSUE THREAD

**Issue by DOF1109** [stackblitz/webcontainer-core#1270]
### Describe the bug

No logra cargar los archivos del explorador cuando abro el IDE desde el proyecto de github

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/DOF1109/ticketmaster-events

### Steps to reproduce

1. Click para abrir el proyecto desde el repositorio de github
2. Se muestra el siguiente mensaje:
3. StackBlitz server crashed
Please report what you were doing before it crashed.

Last output: Error: Cannot find module '/usr/share/stackblitz/out/server-main.js' at Module._resolveFilename (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:55:12642) at Module._load (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:55:10056) at Function.executeUserEntryPoint [as runMain] (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:125:731) at https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:318:166 at Object._0x1c14ac (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:318:186) at _0x325be9 (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:350:55232) at _0x5ec220 (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:352:104173) at _0x7a7e22.executeBootstrapper (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:352:611560) at _0x3b4f2c.startExecution (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:371:2982) at _0x3b4f2c.run (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:371:1328) { code: 'MODULE_NOT_FOUND', requireStack: [] }

### Expected behavior

Se esperaba que se abra normalmente el IDE para poder continuar con el proyecto

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

No puedo descargar el proyecto para probarlo en mi maquina localmente

### Platform

```
Version = 1.84.0
Hash = a5b1ce2088a8c48a3bfda4a131ef20e00b36d9eb
WebContainer = d3416dfd

Browser name  = Chrome
Full version  = 120.0.0.0
Major version = 120
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 61664197,
  "usedJSHeapSize": 57078393,
  "jsHeapSizeLimit": 2172649472
}
```

### Additional context

Error: Cannot find module '/usr/share/stackblitz/out/server-main.js'
    at Module._resolveFilename (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:55:12642)
    at Module._load (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:55:10056)
    at Function.executeUserEntryPoint [as runMain] (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:125:731)
    at https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:318:166
    at Object._0x1c14ac (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:318:186)
    at _0x325be9 (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:350:55232)
    at _0x5ec220 (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:352:104173)
    at _0x7a7e22.executeBootstrapper (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:352:611560)
    at _0x3b4f2c.startExecution (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:371:2982)
    at _0x3b4f2c.run (https://ticketmasterevents-0acz.w-credentialless.staticblitz.com/blitz.d3416dfd.js:371:1328) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by ykmsd** [comment]
Hi @DOF1109 ! This should be fixed now, could you try it again? Please let us know if you still have a problem 🙏
