### ISSUE TITLE
crashStackBlitz server crashed

### ISSUE THREAD

**Issue by guidelli** [stackblitz/webcontainer-core#1271]
### Describe the bug

i interrupted a lon running program

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/guidelli/effect01

### Steps to reproduce

node-ts src/essentials/createeffect

### Expected behavior

just the end of the program

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

no screenshot

### Platform

```
Version = 1.84.0
Hash = a5b1ce2088a8c48a3bfda4a131ef20e00b36d9eb
WebContainer = d3416dfd

Browser name  = Chrome
Full version  = 119.0.0.0
Major version = 119
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55293681,
  "usedJSHeapSize": 46995389,
  "jsHeapSizeLimit": 2172649472
}
```

### Additional context

Error: Cannot find module '/usr/share/stackblitz/out/server-main.js'
    at Module._resolveFilename (https://effect01-zf3u.w-credentialless.staticblitz.com/blitz.d3416dfd.js:55:12642)
    at Module._load (https://effect01-zf3u.w-credentialless.staticblitz.com/blitz.d3416dfd.js:55:10056)
    at Function.executeUserEntryPoint [as runMain] (https://effect01-zf3u.w-credentialless.staticblitz.com/blitz.d3416dfd.js:125:731)
    at https://effect01-zf3u.w-credentialless.staticblitz.com/blitz.d3416dfd.js:318:166
    at Object._0x1c14ac (https://effect01-zf3u.w-credentialless.staticblitz.com/blitz.d3416dfd.js:318:186)
    at _0x325be9 (https://effect01-zf3u.w-credentialless.staticblitz.com/blitz.d3416dfd.js:350:55232)
    at _0x5ec220 (https://effect01-zf3u.w-credentialless.staticblitz.com/blitz.d3416dfd.js:352:104173)
    at _0x7a7e22.executeBootstrapper (https://effect01-zf3u.w-credentialless.staticblitz.com/blitz.d3416dfd.js:352:611560)
    at _0x3b4f2c.startExecution (https://effect01-zf3u.w-credentialless.staticblitz.com/blitz.d3416dfd.js:371:2982)
    at _0x3b4f2c.run (https://effect01-zf3u.w-credentialless.staticblitz.com/blitz.d3416dfd.js:371:1328) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by ykmsd** [comment]
Hi @guidelli, thanks for your report! This issue should be fixed now, could you try it again? Please let us know if you still see the issue 🙏
