### ISSUE TITLE
StackBlitz server crashed

### ISSUE THREAD

**Issue by SuheylZ** [stackblitz/webcontainer-core#1294]
### Describe the bug

click on github project and it fails to load project

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/SuheylZ/react-components

### Steps to reproduce

try open the project and it cant load

### Expected behavior

could not load and always crashes

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = b8962b431f1d341b4ddfaaf7f9230afb4c5effbe
WebContainer = f7aa08df

Browser name  = Chrome
Full version  = 120.0.0.0
Major version = 120
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
performance.memory = {
  "totalJSHeapSize": 48469998,
  "usedJSHeapSize": 41381842,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Error: Cannot find module '/usr/share/stackblitz/out/server-main.js'
    at Module._resolveFilename (https://reactcomponents-kriu.w-corp.staticblitz.com/blitz.f7aa08df.js:55:12642)
    at Module._load (https://reactcomponents-kriu.w-corp.staticblitz.com/blitz.f7aa08df.js:55:10056)
    at Function.executeUserEntryPoint [as runMain] (https://reactcomponents-kriu.w-corp.staticblitz.com/blitz.f7aa08df.js:125:731)
    at https://reactcomponents-kriu.w-corp.staticblitz.com/blitz.f7aa08df.js:318:166
    at Object._0x92b135 (https://reactcomponents-kriu.w-corp.staticblitz.com/blitz.f7aa08df.js:318:186)
    at _0x3788f4 (https://reactcomponents-kriu.w-corp.staticblitz.com/blitz.f7aa08df.js:350:55480)
    at _0x3cc69d (https://reactcomponents-kriu.w-corp.staticblitz.com/blitz.f7aa08df.js:352:104751)
    at _0x56df71.executeBootstrapper (https://reactcomponents-kriu.w-corp.staticblitz.com/blitz.f7aa08df.js:352:612532)
    at _0x65ea87.startExecution (https://reactcomponents-kriu.w-corp.staticblitz.com/blitz.f7aa08df.js:371:2902)
    at _0x65ea87.run (https://reactcomponents-kriu.w-corp.staticblitz.com/blitz.f7aa08df.js:371:1334) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by SamVerschueren** [comment]
Hey @SuheylZ 👋 . I just tried myself and I am able to run the project. Can you try again to see if you still have that issue? If you still experience the issue, can you run `ls /usr/share/stackblitz/out` in the terminal and copy-paste the output?

![image](https://github.com/stackblitz/webcontainer-core/assets/1913805/55f9f707-16e2-4b8a-9dd5-98cd5953091a)
