### ISSUE TITLE
Project crashes with optionalDependencies in package

### ISSUE THREAD

**Issue by ciscoheat** [stackblitz/webcontainer-core#1295]
### Describe the bug

This project crashes when loading, possibly because the package `sveltekit-superforms` (which I'm the author of) uses `optionalDependencies` in package.json to avoid loading certain packages that the user won't need.

I suspect this because of the error messages:

```
[vite] Error when evaluating SSR module /node_modules/sveltekit-superforms/dist/adapters/typebox.js: failed to import "@sinclair/typebox/compiler"
|- ReferenceError: Cannot access 'Object' before initialization
    at eval (file:///home/projects/superforms-2-testing/node_modules/@sinclair/typebox/build/import/type/object/object.mjs:6:1)
```

`@sinclair/typebox/compiler` is one of the optionalDependencies.

### Link to the blitz that caused the error

https://stackblitz.com/edit/superforms-2-testing?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2F%2Bpage.server.ts

### Steps to reproduce

Simply go to the Stackblitz link. Errors should appear:

```
  VITE v5.0.11  ready in 2752 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
09:21:44 [vite] Error when evaluating SSR module /node_modules/sveltekit-superforms/dist/adapters/typebox.js: failed to import "@sinclair/typebox/compiler"
|- ReferenceError: Cannot access 'Object' before initialization
    at eval (file:///home/projects/superforms-2-testing/node_modules/@sinclair/typebox/build/import/type/object/object.mjs:6:1)
    at Generator.next (<anonymous>)
    at _0x50a39c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:371712)
    at _0x50a39c.instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:370785)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:375297)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)

09:21:44 [vite] Error when evaluating SSR module /node_modules/sveltekit-superforms/dist/adapters/index.js: failed to import "/node_modules/sveltekit-superforms/dist/adapters/typebox.js"
|- ReferenceError: Cannot access 'Object' before initialization
    at eval (file:///home/projects/superforms-2-testing/node_modules/@sinclair/typebox/build/import/type/object/object.mjs:6:1)
    at Generator.next (<anonymous>)
    at _0x50a39c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:371712)
    at _0x50a39c.instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:370785)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:375297)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)

09:21:44 [vite] Error when evaluating SSR module /src/routes/+page.server.ts: failed to import "/node_modules/sveltekit-superforms/dist/adapters/index.js"
|- ReferenceError: Cannot access 'Object' before initialization
    at eval (file:///home/projects/superforms-2-testing/node_modules/@sinclair/typebox/build/import/type/object/object.mjs:6:1)
    at Generator.next (<anonymous>)
    at _0x50a39c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:371712)
    at _0x50a39c.instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:370785)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:375297)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)

ReferenceError: Cannot access 'Object' before initialization
    at eval (file:///home/projects/superforms-2-testing/node_modules/@sinclair/typebox/build/import/type/object/object.mjs:6:1)
    at Generator.next (<anonymous>)
    at _0x50a39c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:371712)
    at _0x50a39c.instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:370785)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:375297)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
    at _0xbc6e8c._instantiate (https://superforms2testing-fbzy.w-credentialless.staticblitz.com/blitz.f7aa08df.js:352:374561)
```

### Expected behavior

The project should load as usual. It works locally with these commands:

```bash
npm install
npm run dev
```

(Then browse to the url)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Windows 10
- Browser: Chrome
- Version: 120.0.6099.217

**Comment by SamVerschueren** [comment]
Hey @ciscoheat 👋 ! Thanks for reaching out.

I created an internal ticket to look into this. I'm also not sure what's going on or why it goes wrong.

**Comment by ciscoheat** [comment]
Thank you for checking it out! I hope you can get it working.

**Comment by d3lm** [comment]
Hey 👋 Just wanted to let you know that this issue has been fixed.

**Comment by ciscoheat** [comment]
That's great news, thank you!
