### ISSUE TITLE
BUG: TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by ericclemmons** [stackblitz/webcontainer-core#13]
---
name: Bug report
about: Create a report to help us improve
title: 'TypeError: Class extends value undefined is not a constructor or null'
labels: ''
assignees: ''

---

**Describe the bug**

`npx next dev` triggers error after installing `aws-amplify` and `@aws-amplify/ui-react`:

```console
TypeError: Class extends value undefined is not a constructor or null
    at Object.618 (/projects/nextjs-fbxtsa/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:161)
    at __nccwpck_require__ (/projects/nextjs-fbxtsa/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11796)
    at Object.270 (/projects/nextjs-fbxtsa/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:474)
    at __nccwpck_require__ (/projects/nextjs-fbxtsa/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11796)
    at Object.327 (/projects/nextjs-fbxtsa/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:321)
    at __nccwpck_require__ (/projects/nextjs-fbxtsa/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11796)
    at Object.845 (/projects/nextjs-fbxtsa/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3794)
    at __nccwpck_require__ (/projects/nextjs-fbxtsa/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11796)
    at eval (/projects/nextjs-fbxtsa/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11924)
    at Object.eval (/projects/nextjs-fbxtsa/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11950)
    at Object.function (https://nextjs-fbxtsa.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19819)
    at Module._compile (https://nextjs-fbxtsa.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187549)
    at Object.Module._extensions..js (https://nextjs-fbxtsa.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187908)
    at Module.load (https://nextjs-fbxtsa.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:185988)
    at Function.Module._load (https://nextjs-fbxtsa.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:183564)
    at Module.require (https://nextjs-fbxtsa.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:186304)

error Command failed with exit code 1
```

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nextjs-fbxtsa?file=pages%2Findex.js

**To Reproduce**
1. Go to https://stackblitz.com/fork/nextjs
2. <kbd>Ctrl-C</kbd> the server
3. `npm i aws-amplify @aws-amplify/ui-react`
4. `npm install && npx next dev`

**Expected behavior**

I didn't change any of the code, only installed dependencies, so I expected `npx next dev` to work at least.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.93
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
performance.memory = {
  totalJSHeapSize: 97503413,
  usedJSHeapSize: 74534329,
  jsHeapSizeLimit: 4294705152
}

**Comment by KwintenP** [comment]
Seems like a bug indeed, thanks for reporting 🙏

**Comment by SamVerschueren** [comment]
@ericclemmons if you add those packages, try and save your files (package.json + package-lock.json) and refresh the browser. I believe that should fix it. At least I was able to add the dependencies and start the project https://stackblitz.com/edit/nextjs-vwvppl?file=package.json.

**Comment by SamVerschueren** [comment]
I tested this again and it seems to work now. I tried adding the authenticator component and it works.

![image](https://user-images.githubusercontent.com/1913805/122062517-c6bbb400-cdef-11eb-83bf-c07ea51369db.png)

Feel free to respond or create a new issue if you run into things like this again.
