### ISSUE TITLE
a flood of "runtime error. Build with -s ASSERTIONS=1" that crashes the browser

### ISSUE THREAD

**Issue by daxherrera** [stackblitz/webcontainer-core#1303]
### Describe the bug

a small bug creates this flood of "runtime error. Build with -s ASSERTIONS=1" that never stops and crashes the browser. 

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/daxherrera/seanies-quest?initialPath=/metadata/2

### Steps to reproduce

it happens if there's a small variable mismatch between express routes and inside the function

### Expected behavior

it should display the error once.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 0c70e92b3d3a027d78ae676e788f37bcd21bac24
WebContainer = babcaeac

Browser name  = Chrome
Full version  = 119.0.0.0
Major version = 119
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 180513895,
  "usedJSHeapSize": 160843807,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by jrvidal** [comment]
@daxherrera Thanks for the report. Could you include more detailed reproduction steps? When I open the project, I just see:

```
> app
> nodemon index.js

[nodemon] 3.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node index.js`
Error: No database connection string was provided to `neon()`. Perhaps an environment variable has not been set?
    at neon (/home/daxherrera/seanies-quest/node_modules/@neondatabase/serverless/index.js:1514:75)
    at Object.eval (/home/daxherrera/seanies-quest/index.js:9:13)
    at Object.function (https://seaniesquest-1kxk.w-credentialless.staticblitz.com/blitz.563c79eb.js:352:194798)
    at Module._compile (node:internal/modules/cjs/loader:54:14871)
    at Module._extensions..js (node:internal/modules/cjs/loader:54:15550)
    at Module.load (node:internal/modules/cjs/loader:54:13457)
    at Module._load (node:internal/modules/cjs/loader:54:10535)
    at Function.executeUserEntryPoint (node:internal/modules/run_main:125:731)
    at <anonymous> (node:internal/main/run_main_module:318:166)
    at Object._0x2fc967 (node:internal/main/run_main_module:318:186)
[nodemon] app crashed - waiting for file changes before starting...
```
