### ISSUE TITLE
StackBlitz server crashed

### ISSUE THREAD

**Issue by AlenaRudenko** [stackblitz/webcontainer-core#1311]
### Describe the bug

crash app permanentely

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/AlenaRudenko/chat-app

### Steps to reproduce

go to stackblitz, and it`s crash after cleanoing browser history and app cashe

### Expected behavior

appearing my project

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 5b71eec7e7e29934191def5462461888ab204c32
WebContainer = 6854296d

Browser name  = Chrome
Full version  = 120.0.0.0
Major version = 120
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 81607115,
  "usedJSHeapSize": 62868355,
  "jsHeapSizeLimit": 2172649472
}
```

### Additional context

Error: Cannot find module '/usr/share/stackblitz/out/server-main.js'
    at Module._resolveFilename (https://chatapp-bslw.w-credentialless.staticblitz.com/blitz.6854296d.js:54:12642)
    at Module._load (https://chatapp-bslw.w-credentialless.staticblitz.com/blitz.6854296d.js:54:10056)
    at Function.executeUserEntryPoint [as runMain] (https://chatapp-bslw.w-credentialless.staticblitz.com/blitz.6854296d.js:125:731)
    at https://chatapp-bslw.w-credentialless.staticblitz.com/blitz.6854296d.js:318:166
    at Object._0x491215 (https://chatapp-bslw.w-credentialless.staticblitz.com/blitz.6854296d.js:318:186)
    at _0x178083 (https://chatapp-bslw.w-credentialless.staticblitz.com/blitz.6854296d.js:350:54825)
    at _0x67300a (https://chatapp-bslw.w-credentialless.staticblitz.com/blitz.6854296d.js:352:101553)
    at _0x4c63d5.executeBootstrapper (https://chatapp-bslw.w-credentialless.staticblitz.com/blitz.6854296d.js:352:615891)
    at _0x5c2ca6.startExecution (https://chatapp-bslw.w-credentialless.staticblitz.com/blitz.6854296d.js:371:3003)
    at _0x5c2ca6.run (https://chatapp-bslw.w-credentialless.staticblitz.com/blitz.6854296d.js:371:1331) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by AlenaRudenko** [comment]
(https://github.com/stackblitz/webcontainer-core/assets/89128807/8d90ed0d-fdfb-4177-bafc-4a43abee0179)

**Comment by Nemikolh** [comment]
Hey @AlenaRudenko ! :wave: 

I'm curious, do you also get this issue in incognito? Usually clearing the site data via:

![](https://developer.chrome.com/static/docs/devtools/storage/websql/image/the-clear-site-data-butto-112c9d28a24d3_1920.png)

Should be enough. You might also want to manually delete all `IndexedDB` databases for `stackblitz.com` if the above button didn't work.

**Comment by AlenaRudenko** [comment]
I've been really struggling with the problem for two months now that stackblitz doesn't see the github branch in any way other than the master branch, or if I create this branch directly in stackblitz. If I clear the cache and clear the browser history, this occurs : thirst two screenshots.




Отправлено из мобильной Почты Mail.ru


вторник, 30 января 2024 г. в 13:41 +03:00 от ***@***.***  ***@***.***>:

**Comment by AlenaRudenko** [comment]
Отправлено из мобильной Почты Mail.ru


вторник, 30 января 2024 г. в 13:48 +03:00 от алёна руденко  ***@***.***>:
