### ISSUE TITLE
Error: nodeUtil is not defined

### ISSUE THREAD

**Issue by himself65** [stackblitz/webcontainer-core#1312]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

util module should be considered as a node internal package

```shell
Error: nodeUtil is not defined
    at <anonymous> (/home/projects/llqiawwrr.github/node_modules/pdf2json/lib/pdf.js)
    at eval (/home/projects/llqiawwrr.github/node_modules/pdf2json/lib/pdf.js:87:1)
    at _0x345efc._evaluate (https://llqiawwrrgithub-0ckm.w-credentialless.staticblitz.com/blitz.6854296d.js:352:378687)
    at async _0x345efc._evaluate (https://llqiawwrrgithub-0ckm.w-credentialless.staticblitz.com/blitz.6854296d.js:352:378298)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:2372)
```

### **Steps to Reproduce**

1. Go to https://stackblitz.com/github/run-llama/LlamaIndexTS/tree/main/examples?file=README.md
2.

```shell
ts-node ./readers/load-pdf.ts
```

### **Expected Behavior**

Parse pdf successfully

### **Screenshots/Screencast**

<img width="692" alt="image" src="https://github.com/stackblitz/core/assets/14026360/463d5d90-da80-473c-becb-ec47ff66065f">

**Additional Context/Questions**
Add any other context or questions regarding this bug.

```js
import nodeUtil from 'util';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { EventEmitter } from 'events';
import { Blob } from 'buffer';
import { DOMParser } from '@xmldom/xmldom';
// ...
```

**Comment by himself65** [comment]
sorry I published the new llamaindex, you can see the error now
