### ISSUE TITLE
Angular Web container is failing with `TypeError: (0 , window.WebContainer) is not a constructor`

### ISSUE THREAD

**Issue by iKrishnaSahu** [stackblitz/webcontainer-core#1348]
### Describe the bug

Angular Web container is failing with `TypeError: (0 , window.WebContainer) is not a constructor` in console.

Link - https://stackblitz.com/edit/stackblitz-starters-vaymjp?file=package.json

```
Uncaught (in promise) TypeError: (0 , window.WebContainer) is not a constructor
    at $U (client-cd40551b8329a.js:2:2742110)
    at client-cd40551b8329a.js:2:3323145
    at client-cd40551b8329a.js:2:3323355
    at nrWrapper (stackblitz-starters-vaymjp?file=package.json:8:16615)
```

This issue is reproducing in other projects as well - https://stackblitz.com/edit/stackblitz-starters-spergq?file=package.json

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-vaymjp?file=package.json

### Steps to reproduce

1. Go to `https://stackblitz.com/edit/stackblitz-starters-vaymjp?file=package.json`
2. Check if terminal is working
3. Open console to check error

### Expected behavior

Web container should boot up

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="953" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/34937515/a7011e2b-9050-4a7f-b79e-1ff4c118210c">

### Platform

- OS: [e.g. macOS, Windows, Linux] - Windows
- Browser: [e.g. Chrome, Safari, Firefox] - Chrome
- Version: [e.g. 91.1] - latest

**Comment by SamVerschueren** [comment]
Hey @iKrishnaSahu. Can you try to refresh? Maybe there was some network issue or something. If it still happens, can you open the network tab, do you see some resources that fail to load?

I see that it printed a message "slow network is detected". So I'm wondering if this is a racing condition on our side in case of slower networks.

**Comment by SamVerschueren** [comment]
We found out that this is indeed a racing condition on our side. I'll create an internal ticket to track this. Thank you for reporting this 🙏 .
