### ISSUE TITLE
Can't use Fetch API from `undici` (max header count assertion error)

### ISSUE THREAD

**Issue by steveluscher** [stackblitz/webcontainer-core#1363]
### Describe the bug

When trying to use the `fetch` API from Node's `undici` library, the following results:

```shell
Error: fetch failed
    at _0x15be0c._evaluate (https://stackblitzstartersmkfl4d-4h03.w-credentialless-staticblitz.com/blitz.c9a8a620.js:352:379484)
    at async ModuleJob.run (https://stackblitzstartersmkfl4d-4h03.w-credentialless-staticblitz.com/blitz.c9a8a620.js:181:2372) {
  [cause]: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  
    assert(Number.isFinite(client[kMaxHeadersSize]) && client[kMaxHeadersSize] > 0)
  
      at new Parser (file:///home/projects/stackblitz-starters-mkfl4d/node_modules/undici/lib/dispatcher/client-h1.js:140:5)
      at connectH1 (file:///home/projects/stackblitz-starters-mkfl4d/node_modules/undici/lib/dispatcher/client-h1.js:646:21)
      at async connect (file:///home/projects/stackblitz-starters-mkfl4d/node_modules/undici/lib/dispatcher/client.js:439:11) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  }
}
```

`client[kMaxHeadersSize]` appears to be `undefined` in Stackblitz.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-mkfl4d?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js,package.json&title=node.new%20Starter

### Steps to reproduce

```shell
npm start
```

### Expected behavior

I would expect the fetch to succeed and return a `Response` object.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 122.0.0.0
Major version = 122
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 114414369,
  "usedJSHeapSize": 91390805,
  "jsHeapSizeLimit": 4294705152
}
Hash = c9a8a620
```

**Comment by steveluscher** [comment]
I _presume_ this might be because you're using a proxy behind the scenes, and that the default `undici` [dispatcher](https://github.com/nodejs/undici/tree/main/docs#undicisetglobaldispatcherdispatcher) just doesn't know what to do or where to go.

**Comment by steveluscher** [comment]
New discovery: on this WebContainer, the following is `undefined`:

```ts
const http = require('node:http');
console.log(http.maxHeaderSize);
```

**Comment by steveluscher** [comment]
Is it possible that `HTTP_MAX_HEADER_SIZE` is set (to `undefined`) somewhere in this environment?

**Comment by steveluscher** [comment]
Interestingly, merely doing a bare import of `undici` will break the _global_ `fetch`.

https://stackblitz.com/edit/stackblitz-starters-vuwntr?file=index.js
