### ISSUE TITLE
Can't fetch from third-party domain (`UND_ERR_SOCKET` error)

### ISSUE THREAD

**Issue by steveluscher** [stackblitz/webcontainer-core#1364]
### Describe the bug

When trying to fetch from a domain other than stackblitz[dot]com using the `fetch` API globally available in Node, we get the following error:

```shell
TypeError: fetch failed
    at _0x28682a (https://stackblitzstarters9mscrr-151h.w-credentialless-staticblitz.com/blitz.c9a8a620.js:352:615633)
    at _0x423f12._0x55b3a7 (https://stackblitzstarters9mscrr-151h.w-credentialless-staticblitz.com/blitz.c9a8a620.js:352:626518)
    at t.exports.fetch (node:internal/deps/undici/undici:194:308109)
    at async eval (/home/projects/stackblitz-starters-9mscrr/index.js:7:5) {
  cause: y [SocketError]: other side closed
      at TLSSocket.onSocketEnd (node:internal/deps/undici/undici:194:268609)
      at EventEmitter.emit (node:events:42:9318)
      at endReadableNT (node:internal/streams/readable:105:15152)
      at _0x271e48 (https://stackblitzstarters9mscrr-151h.w-credentialless-staticblitz.com/blitz.c9a8a620.js:352:154311)
      at <anonymous> (https://stackblitzstarters9mscrr-151h.w-credentialless-staticblitz.com/blitz.c9a8a620.js:352:154068) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '1.0.0.2',
      localPort: 443,
      remoteAddress: undefined,
      remotePort: undefined,
      remoteFamily: undefined,
      timeout: undefined,
      bytesWritten: undefined,
      bytesRead: undefined
    }
  }
}
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-9mscrr?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=index.js&title=node.new%20Starter

### Steps to reproduce

```shell
npm start
```

### Expected behavior

I would expect `fetch` to resolve with a `Response` object.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 122.0.0.0
Major version = 122
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 122939021,
  "usedJSHeapSize": 102347725,
  "jsHeapSizeLimit": 4294705152
}
Hash = c9a8a620
```

**Comment by steveluscher** [comment]
This turned out to be because of CORS. A better error message here would be lovely, if possible.
