### ISSUE TITLE
StackBlitz server crashed

### ISSUE THREAD

**Issue by kalosfide** [stackblitz/webcontainer-core#1372]
### Describe the bug

loading failed

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/kalosfide/select-form-control

### Steps to reproduce

load

### Expected behavior

project start

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 832d7b9e39c64736b58cf4b4d600381f1e63d13d
WebContainer = dc33e3af

Browser name  = Firefox
Full version  = 123.0
Major version = 123
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
performance.memory = undefined
```

### Additional context

Error: Cannot find module '/usr/share/stackblitz/out/server-main.js'
    at InternalError (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:64:14749)
    at Module._resolveFilename (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:54:12642)
    at Module._load (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:54:10056)
    at executeUserEntryPoint (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:125:731)
    at  (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:318:166)
    at  (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:318:186)
    at _0x81a4ae (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:350:56858)
    at _0x3a3e4b (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:352:101626)
    at executeBootstrapper (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:352:617310)
    at startExecution (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:371:2893)
    at run (https://selectformcontrol-0bcw.w-corp-staticblitz.com/blitz.dc33e3af.js:371:1334) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by jrvidal** [comment]
:wave: The project you linked fails with:

```
An unhandled exception occurred: require() of ES Module /home/node/project/node_modules/@angular/compiler/fesm2015/compiler.mjs not supported.
Instead change the require of /home/node/project/node_modules/@angular/compiler/fesm2015/compiler.mjs to a dynamic import() which is available in all CommonJS modules.
See "/tmp/ng-uLb8Qh/angular-errors.log" for further details.
```

both at StackBlitz and locally. Is there any other way to reproduce the error you were seeing?
