### ISSUE TITLE
BUG: a is not a function

### ISSUE THREAD

**Issue by nicholaschiang** [stackblitz/webcontainer-core#140]
**Describe the bug:**

My Next.js app doesn't compile. Instead, it gives me this error:

```
TypeError: a is not a function
    at https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:293835
    at https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:34190
    at Object.eval (/home/projects/github-wpszkt/node_modules/jose/lib/registry/ec_curves.js:5:5)
    at Object.function (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:11:15383)
    at Module._compile (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:187553)
    at Object.Module._extensions..js (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:187912)
    at Module.load (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:185992)
    at Function.Module._load (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:183568)
    at Module.require (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:186308)
    at i (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:484683)
    at _0x2d4ef9 (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:11:15298)
    at Object.eval (/home/projects/github-wpszkt/node_modules/jose/lib/registry/index.js:1:80)
    at Object.function (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:11:15383)
    at Module._compile (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:187553)
    at Object.Module._extensions..js (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:187912)
    at Module.load (https://github-wpszkt.jw.staticblitz.com/blitz.12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08.js:6:185992)
```

Which is then shown in the development server:

![image](https://user-images.githubusercontent.com/20798889/120519878-ff877200-c387-11eb-90b7-88caa9fe45ee.png)

**Link to the blitz that caused the error**
https://stackblitz.com/edit/tutorbook

**Steps to reproduce:**

1. Open https://stackblitz.com/edit/tutorbook.
2. Wait for the web container to boot, deps to install, and dev server to start.
3. See error.

**Expected behavior:**

There should no error.

**Version of webcontainer:**
Hash: 12423d4ada17c5bf9dcd8d2c2bd877a5f9b12d08

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.218
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 13816.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.218 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 170309605,
  "usedJSHeapSize": 160609069,
  "jsHeapSizeLimit": 2172649472
}

**Additional context:**

I'm trying to get [Tutorbook](https://github.com/tutorbookapp/tutorbook) working in StackBlitz.

**Comment by SamVerschueren** [comment]
Hi @nicholaschiang! Thanks for reporting. This looks like an issue on our end. Could you create a new Blitz and update the URLs? It looks like you removed the project so would be great if I had a direct URL 🙏 .

**Comment by nicholaschiang** [comment]
@SamVerschueren I've updated the original issue with the renamed https://stackblitz.com/edit/tutorbook.

Or, if you can't access that, you should be able to fork https://stackblitz.com/github/tutorbookapp/tutorbook but you'll need some `.env.local` files (see stackblitz/core#1492).

**Comment by ndom91** [comment]
I'm having the same issue with a private backend hapi api. Seems to be a jose elliptic curve issue.

Let me know if I can help in any way either!

**Comment by SamVerschueren** [comment]
Everything crypto related is currently kinda wonky. Not everything works yet as we focussed heavily on front-end tooling first. It’s something we’re working on though but can’t give you an exact timing.

**Comment by d3lm** [comment]
Hey! While `getCurves` is not yet implemented, it doesn't throw anymore and you'll get an empty array instead. But I can't run the project cause I am getting `UNAVAILABLE: No connection established`. May be related to some environment variables being incorrect that it can't connect to the Firebase DB?

**Comment by jrvidal** [comment]
:wave: We're closing this due to inactivity. Please, feel free to open a new one if you're still encountering any errors.
