### ISSUE TITLE
`nuxt preview` not working anymore after `nuxt generate`

### ISSUE THREAD

**Issue by codeflorist** [stackblitz/webcontainer-core#1439]
### Describe the bug

Currently, when running `nuxt preview` to preview a nuxt application built with `nuxt generate`, the following error is thrown:

```
 ERROR  Command failed with exit code 13: npx serve ./public                                                                            11:06:18

  at makeError (node_modules/nuxi/dist/chunks/index3.mjs:1292:11)
  at handlePromise (node_modules/nuxi/dist/chunks/index3.mjs:2530:26)
  at async Object.run (node_modules/nuxi/dist/chunks/preview.mjs:141:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1678:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1669:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1807:7) 
```

This was definitely working a while (maybe 2-3 weeks) ago. I also don't think that a Nuxt-update caused this, since the current Nuxt version (v3.11.2) came out more than a month ago, and i definitely had stackblitzes like this working in the meantime. I also tried with v3.11.1 and it has the same problem.

It is worth noting, that it is still working using `nuxt build` instead of `nuxt generate`.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nuxt-starter-zrndgf?file=package.json

### Steps to reproduce

1. launch the stackblitz
2. i have the `startCommand` set to `npm run generate && npm run preview`, so you just have to press `y` when asked to install the `serve` package.

### Expected behavior

No error being thrown - instead the generated site should be served.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 124.0.0.0
Major version = 124
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 93891146,
  "usedJSHeapSize": 75402534,
  "jsHeapSizeLimit": 4294705152
}
Hash = 34455753
```

**Comment by codeflorist** [comment]
I think the problem is, that `nuxt preview` is trying to launch `npx serve ./public` instead of `npx serve .output/public`. So the problem might lie with nuxt or nitro. This however doesn't happen locally.

**Comment by SamVerschueren** [comment]
Hey @codeflorist 👋 . Thanks for reaching out!

I opened your project and it seems to work for me. Can you maybe try again and see if it's fixed in the mean time? We did release a new Node.js version with some additional fixes so it might have (accidentally) fixed it.

**Comment by codeflorist** [comment]
> Hey @codeflorist 👋 . Thanks for reaching out!
> 
> I opened your project and it seems to work for me. Can you maybe try again and see if it's fixed in the mean time? We did release a new Node.js version with some additional fixes so it might have (accidentally) fixed it.

@SamVerschueren 

Thanks for taking a look!

I just tried https://stackblitz.com/edit/nuxt-starter-zrndgf?file=package.json again, and the same error is thrown.

I tried in Chrome as well as Firefox (Windows 11).

It's weird, that it is working with you.

One additional note: After booting up, the procedure halts at:
```
Need to install the following packages:
serve@14.2.3
Ok to proceed? (y) 
```
There you have to press `y`, since the nuxt preview command requires the serve package.

**Comment by SamVerschueren** [comment]
Hey @codeflorist !

Yes, I did press `y` and enter. I don't have to do anything else besides opening the project and then pressing `y` when it asks for it? The only thing I can think off is that you're running on Windows 🤔 . I might need to ask someone else from the team to test this on a Windows machine.

![image](https://github.com/stackblitz/webcontainer-core/assets/1913805/caea4506-e152-420d-9c73-440df552ca96)

**Comment by codeflorist** [comment]
here is a screenshot from me in a chrome inkognito window:
![image](https://github.com/stackblitz/webcontainer-core/assets/41453547/00a5fa6e-ad19-4162-ac8c-d5b49d55dfee)

**Comment by Iaicox** [comment]
@SamVerschueren I faced the same issue. I also use Windows, but don't think it's the key of the issue.

For example, I see the same issue on your screenshot:
There's no "output" folder created in the project on your screenshot. Some file without extension "dist" created after command "npm run generate" finished. It's pretty strange that your command running works instead of crashing.

So, you don't have "output" folder, your current "public" folder doesn't contain index.html (or any other *.html files), some strange file "dist" appears after "generate" command finished. After that there's no way the serve could start correctly =(

Check it again, please🙏

**Comment by Iaicox** [comment]
https://stackblitz.com/edit/nuxt-starter-4kcqmvfs
![Image](https://github.com/user-attachments/assets/054c5130-9506-4899-a7e0-b0738fad94dd)

**Comment by SamVerschueren** [comment]
I still can't reproduce this unfortunately :/. I still need to check on a Windows machine though.

<img width="1666" alt="Image" src="https://github.com/user-attachments/assets/7d9cfb9b-ea8e-497f-8a68-4f32d4408e98" />

**Comment by Iaicox** [comment]
Ah, now the folder ".output" appears, in your message https://github.com/stackblitz/webcontainer-core/issues/1439#issuecomment-2165186783 there wasn't such folder =(

Ok, ping us when you check it on windows please

**Comment by okathira** [comment]
Might be the same problem as https://github.com/stackblitz/webcontainer-core/issues/1805
So the essence of the problem is; when a directory is created that starts with a dot, it is not recognized?

**Comment by codeflorist** [comment]
> Might be the same problem as [#1805](https://github.com/stackblitz/webcontainer-core/issues/1805) So the essence of the problem is; when a directory is created that starts with a dot, it is not recognized?

This should not be an issue here, since `.output` is created by Nuxt during the `generate` command to actually store the built output. Furthermore, `nuxt build` works, and it is also creating this folder. Additionally `nuxt generate` works on Linux, but not on Windows, but the linked issue seems to be OS-independent

> So, you don't have "output" folder, your current "public" folder doesn't contain index.html (or any other *.html files), some strange file "dist" appears after "generate" command finished. After that there's no way the serve could start correctly =(

`dist` is simply a symlink to `.output/public`. This is normal Nuxt behaviour. The interface just shows the symlink as a file, because it doesn't support it. It's also irrelevant, since it isn't used at all, since `npx serve` is called on `.output/public` directly.

The root `public` folder of Nuxt has nothing to do with the built output. It just contains static files to be copied over. The built output resides in `.output/public`. (The command `npx serve ./output` is a bit misleading here. In the screenshots you can see `Working directory: .output`. So actually `.output/public` is correctly served.)

So the Linux screenshots seem perfectly correct to me. Why the same doesn't work on Windows is the big question though.
