### ISSUE TITLE
Terminal & browser window are not working

### ISSUE THREAD

**Issue by ShubhanshuLV** [stackblitz/webcontainer-core#1464]
### Describe the bug

Terminal window must load properly so I can run the npm commands to run this sample project.
Also preview window must work to display application UI after npm app compilation.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-k7yd6v?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=package.json&template=node&title=Angular%20Starter

### Steps to reproduce

1. Go to application editor (IDE)
2. Then you will see the terminal is not loading

### Expected behavior

Terminal must be load and I can run npm commands to execute this sample application.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/102136684/4b175186-1401-4280-bd77-3329265b9dd0)

### Platform

```
Browser name  = Chrome
Full version  = 125.0.0.0
Major version = 125
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87852217,
  "usedJSHeapSize": 71428693,
  "jsHeapSizeLimit": 2172649472
}
Hash = 9e2d28a3
```

**Comment by SamVerschueren** [comment]
Hey @ShubhanshuLV 👋 . Thanks for reaching out! Would it be possible to open the Chrome DevTools and check if there are any error messages? It's very weird that it doesn't even show "Booting WebContainer".

**Comment by ShubhanshuLV** [comment]
@SamVerschueren, Thanks for your response.
Yes. there is one error I am seeing as follows:

Uncaught (in promise) TypeError: (0 , window.WebContainer) is not a constructor
    at PW (client-85cd01487893a.js:2:2927704)
    at client-85cd01487893a.js:2:3514330
    at client-85cd01487893a.js:2:3514555
    at nrWrapper (stackblitz-starters-k7yd6v?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=package.json&template=node&title=Angular%20Starter:8:17817)

Please check the attached screenshot here.
Thanks 

![image](https://github.com/stackblitz/webcontainer-core/assets/102136684/258f438d-cf28-4ac5-9415-a615090cb6e2)

**Comment by SamVerschueren** [comment]
Do you happen to be on a network which might block some of the requests that we make? You should be able to see failing requests in the network tab. This might happen due to a company firewall or something like that blocking the requests.

**Comment by ShubhanshuLV** [comment]
@SamVerschueren, this issue will suppose to all stackblitz projects but that's not the case.
If I am opening the others project applications on same system then it's working fine but if I am trying to open my project application then I am getting this issue.
