### ISSUE TITLE
SyntaxError: Unexpected token ')' 

### ISSUE THREAD

**Issue by davegaly** [stackblitz/webcontainer-core#1479]
### Describe the bug

I was working normally with a small Koa.js app, when suddendly a wild error appears:

> start
> node index.js

SyntaxError: Unexpected token ')'
    at __global_eval__ (https://skep-dtfm.w-credentialless-staticblitz.com/blitz.70dbe416.js:12:15)
    at _0x89751f (https://skep-dtfm.w-credentialless-staticblitz.com/blitz.70dbe416.js:40:799685)
    at _0x2444b3._compile (https://skep-dtfm.w-credentialless-staticblitz.com/blitz.70dbe416.js:40:806217)
    at _0x50c1b2 (https://skep-dtfm.w-credentialless-staticblitz.com/blitz.70dbe416.js:40:797559)
    at internalCompileFunction (https://skep-dtfm.w-credentialless-staticblitz.com/builtins.5bf3667c.js:266:849)
    at wrapSafe (https://skep-dtfm.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:13497)
    at Module._compile (https://skep-dtfm.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:13881)
    at Module._extensions..js (https://skep-dtfm.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:14855)
    at Module.load (https://skep-dtfm.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:12820)
    at Module._load (https://skep-dtfm.w-credentialless-staticblitz.com/builtins.5bf3667c.js:144:10273)

Node.js 18.20.3

I tried to undo my last edits, clear cache, reload all over, but nothing seems to solve that.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/davegaly/skep?file=index.js

### Steps to reproduce

Just do an "npm start"

### Expected behavior

I'd like no error in stackblitz libraries, so I can continue working :D

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 499be3932f50ab06349575b1c9042f95bc072a8b
WebContainer = 70dbe416

Browser name  = Chrome
Full version  = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 180768219,
  "usedJSHeapSize": 124709227,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by davegaly** [comment]
Foudn the problem (in my code, sorry)
