### ISSUE TITLE
`jsh: spawn ... ENOENT` Running NPM Binary

### ISSUE THREAD

**Issue by shellscape** [stackblitz/webcontainer-core#1519]
### Describe the bug

Attempting to run an NPM installed package binary results in `jsh: spawn email ENOENT`. Initially I used `pnpm` to install things. Locally and in CI systems, pnpm will create a `node_modules/.bin/email` file that looks like this:

```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/code/jsx-email/packages/jsx-email/dist/esm/cli/node_modules:/Users/code/jsx-email/packages/jsx-email/dist/esm/node_modules:/Users/code/jsx-email/packages/jsx-email/dist/node_modules:/Users/code/jsx-email/packages/jsx-email/node_modules:/Users/code/jsx-email/packages/node_modules:/Users/code/jsx-email/node_modules:/Users/code/node_modules:/Users/node_modules:/Users/node_modules:/node_modules:/Users/code/jsx-email/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/code/jsx-email/packages/jsx-email/dist/esm/cli/node_modules:/Users/code/jsx-email/packages/jsx-email/dist/esm/node_modules:/Users/code/jsx-email/packages/jsx-email/dist/node_modules:/Users/code/jsx-email/packages/jsx-email/node_modules:/Users/code/jsx-email/packages/node_modules:/Users/code/jsx-email/node_modules:/Users/code/node_modules:/Users/node_modules:/Users/node_modules:/node_modules:/Users/code/jsx-email/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  --enable-source-maps --no-warnings=ExperimentalWarning "$basedir/../jsx-email/dist/esm/cli/index.mjs" "$@"
else
  exec node  --enable-source-maps --no-warnings=ExperimentalWarning "$basedir/../jsx-email/dist/esm/cli/index.mjs" "$@"
fi
```

NPM does it a bit different, but you get the idea. 

When I ran `❯ cat node_modules/.bin/email` I was presented with:

```js
#!/usr/bin/env node --enable-source-maps --no-warnings=ExperimentalWarning
import './main.mjs';
```

Which is significantly not what it should be. It looks like StackBlitz is having a bad day here. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/jsx-email-repro

### Steps to reproduce

1. `npm i`
2. `npm run dev`

### Expected behavior

I'd expect it to run the NPM script, and the appropriate binary. No clue what it's trying to do presently. 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by shellscape** [comment]
I was finally able to execute the target package using a line from the pnpm binary content above:

```
node --enable-source-maps --no-warnings=ExperimentalWarning ./node_modules/jsx-email/dist/esm/cli/index.mjs  preview ./templates 
```

That's less than ideal. 

But holy cow did that run slow. Easily 20x slower than local. Also noticed that Stackblitz doesn't appear to be passing the Node flags `--enable-source-maps --no-warnings=ExperimentalWarning` to the Node binary, as the warning excluded in the flags is showing up below... Stackblitz also seems to have issues executing Node that are otherwise fine locally:

```js
import watcher from '@parcel/watcher';
```

Throws an error on Stackblitz that doesn't occur locally:

```
(node:23) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/projects/jsx-email-repro/node_modules/.pnpm/jsx-email@2.0.5_@jsx-email+app-preview@2.0.2_@jsx-email+plugin-inline@1.0.1_@jsx-email+plugin_onjnu34ermvoyaem7xv73kqu7u/node_modules/jsx-email/dist/esm/cli/watcher.mjs:3
import watcher from '@parcel/watcher';
       ^^^^^^^
SyntaxError: The requested module '@parcel/watcher' does not provide an export named 'default'
    at async ModuleJob.run (https://jsxemailrepro-n4kg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:155:2422)
    at async ModuleLoader.import (https://jsxemailrepro-n4kg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:2688)
    at async loadESM (https://jsxemailrepro-n4kg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:184:541)
    at async handleMainPromise (https://jsxemailrepro-n4kg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:165:296)

Node.js v18.20.3
```

If I manually edit node_modules and change the line to:

```js
import * as watcher from '@parcel/watcher';
```

It works fine. But again, that isn't required locally using the same Node version.

**Comment by shellscape** [comment]
_(Possibly not a helpful comment, but on the far off chance that it is... The same source as used in the stackblitz above succeeds within Codesandbox)_

**Comment by shellscape** [comment]
Related, the StackBlitz shell doesn't support an absolutely CRITICAL flag for `/usr/bin/env`. To reproduce run:

```
/usr/bin/env -S node --enable-source-maps --no-warnings=ExperimentalWarning
```

And you'll recieve:

```
env: '-S': No such file or directory
```

**Comment by shellscape** [comment]
And in my quest to find a workaround to this, I come to find that `jsh` doesn't support bash's `$@`. 

```
#!/bin/sh

basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

echo "opts: $@"

node  "./node_modules/jsx-email/bin/email" "$@"
```

This doesn't work because jsh isn't passing arguments via `$@`. This is massively frustrating, folks. There doesn't appear to be any documentation around the limitations of StackBlitz's console.
