### ISSUE TITLE
Javascripting error

### ISSUE THREAD

**Issue by Seveiron** [stackblitz/webcontainer-core#1592]
### Describe the bug

While rewriting a file using bolt ai it threw this error 
Application Error
TypeError: Cannot read properties of undefined (reading 'available')
    at gie (https://bolt.new/assets/_index-C_pxOfaT.js:148:8510)
    at https://bolt.new/assets/_index-C_pxOfaT.js:148:6986
    at Vo (https://bolt.new/assets/components-B64jh5hJ.js:22:16948)
    at Ji (https://bolt.new/assets/components-B64jh5hJ.js:24:3134)
    at cc (https://bolt.new/assets/components-B64jh5hJ.js:24:2350)
    at Tc (https://bolt.new/assets/components-B64jh5hJ.js:24:47013)
    at Rc (https://bolt.new/assets/components-B64jh5hJ.js:24:39500)
    at Ep (https://bolt.new/assets/components-B64jh5hJ.js:24:39431)
    at dl (https://bolt.new/assets/components-B64jh5hJ.js:24:39289)
    at oo (https://bolt.new/assets/components-B64jh5hJ.js:24:35706)

### Link to the blitz that caused the error

https://stackblitz.com/edit/sb1-goax37?file=index.html

### Steps to reproduce

I am unsure

### Expected behavior

Should of just changed one syntax

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 96325525,
  "usedJSHeapSize": 80017505,
  "jsHeapSizeLimit": 4294705152
}
Hash = f565b097
```

**Comment by mansofian** [comment]
me to

Application Error
TypeError: t.toSorted is not a function
    at Kse (https://bolt.new/assets/_index-2yOnXKZs.js:148:40436)
    at tae (https://bolt.new/assets/_index-2yOnXKZs.js:148:90722)
    at Vo (https://bolt.new/assets/components-B64jh5hJ.js:22:16948)
    at Tc (https://bolt.new/assets/components-B64jh5hJ.js:24:43699)
    at Rc (https://bolt.new/assets/components-B64jh5hJ.js:24:39500)
    at Ep (https://bolt.new/assets/components-B64jh5hJ.js:24:39431)
    at dl (https://bolt.new/assets/components-B64jh5hJ.js:24:39289)
    at oo (https://bolt.new/assets/components-B64jh5hJ.js:24:35706)
    at ma (https://bolt.new/assets/components-B64jh5hJ.js:24:36507)
    at St (https://bolt.new/assets/components-B64jh5hJ.js:22:3258)
