### ISSUE TITLE
BUG: Cannot use ES modules in "node.js".

### ISSUE THREAD

**Issue by masx200** [stackblitz/webcontainer-core#173]
**Describe the bug:**

Cannot use ES modules in "node.js".
**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-jsj5ay?file=cli.js

**Steps to reproduce:**

```shell
❯ node
Welcome to Node.js v14.16.0.
Type ".help" for more information.
> import('./cli.js')
Uncaught TypeError: _e is not a function or its return value is not iterable
    at formatPromise (https://node-jsj5ay.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:113536)
    at https://node-jsj5ay.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:108528
    at formatValue (https://node-jsj5ay.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:109353)
    at inspect (https://node-jsj5ay.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:97300)
    at REPLServer.writer (https://node-jsj5ay.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:1088861)
    at finish (https://node-jsj5ay.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:1098574)
    at finishExecution (https://node-jsj5ay.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:1091944)
    at REPLServer.p (https://node-jsj5ay.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:1092987)
    at bound (https://node-jsj5ay.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:1322969)
    at REPLServer.runBound [as eval] (https://node-jsj5ay.jw.staticblitz.com/blitz.cb1eb6b301af424e8dffb694972509f06ea6b5db.js:6:1324528)
> 
```
**Expected behavior:**

**Version of webcontainer:**
Hash: cb1eb6b301af424e8dffb694972509f06ea6b5db

**Screenshots:**

<img width="960" alt="屏幕截图 2021-06-08 140408" src="https://user-images.githubusercontent.com/34191203/121131484-76c67580-c862-11eb-8259-24b721736d7d.png">
**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82328428,
  "usedJSHeapSize": 75405996,
  "jsHeapSizeLimit": 4294705152
}

**Additional context:**

cli.js
```js
#!/usr/bin/env node
import fs from "fs";
import http from "http";
import http2 from "http2";
import { dirname, join } from "path";
import process from "process";
import { fileURLToPath } from "url";
import { argv } from "./argv.js";
import { app } from "./index.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const selfSignedKey = join(__dirname, "./certs/self-signed.key.pem");
const selfSignedCert = join(__dirname, "./certs/self-signed.cert.pem");
console.log("serve-cli");
if (argv.help || argv.h) {
    console.log(
        [
            "usage: serve-cli [options]",
            "",
            "options:",
            "  --path       Path to folder [process.cwd()]",
            "  --host       Host to use [0.0.0.0]",
            "  --port       Port to use [3000]",

            "  --ssl        Enable https [false]",
            "  --sslKey     Path to ssl key file [self-signed]",
            "  --sslCert    Path to ssl cert file [self-signed]",
            "  --help       Print this list and exit",

            "",
        ].join("\n")
    );
    process.exit();
}
const config = {
    path: argv.path || process.cwd(),
    host: argv.host || "0.0.0.0",
    port: Number(argv.port) || 3000,

    ssl: Boolean(argv.ssl),
    sslKey: Boolean(argv.ssl)
        ? fs.readFileSync(argv.sslKey || selfSignedKey).toString()
        : "",
    sslCert: Boolean(argv.ssl)
        ? fs.readFileSync(argv.sslCert || selfSignedCert).toString()
        : "",
};
console.log(config);
const serverHandler = app.callback();
const httpsopt = { cert: config.sslCert, key: config.sslKey };
const server = config.ssl
    ? http2.createSecureServer(httpsopt, serverHandler)
    : http.createServer(serverHandler);
server.on("error", (err) => {
    if (err.code === "EADDRINUSE") {
        console.error(err);
        server.listen(Math.round(Math.random() * 65535));
        return;
    } else {
        throw err;
    }
});

server.on("listening", () => {
    console.log(`Server listening on ` + JSON.stringify(server.address()));
});
function run() {
    server.listen(config.port, config.host);
}

process.on("unhandledRejection", (e) => {
    console.error(e);
});
const configurl = `${config.ssl ? "https" : "http"}://${config.host}:${
    config.port
}`;
const logs = [
    `Server running at ${configurl}`,

    "Hit CTRL-C to stop the server",
    "Run with --help to print help",
];

console.log(logs.join("\n"));
run();

```

**Comment by SamVerschueren** [comment]
Hi @masx200! Thanks for reporting and providing feedback. I'm closing this as it's a duplicate of #6.
