### ISSUE TITLE
Impossible to run an AdonisJS 5 project

### ISSUE THREAD

**Issue by RomainLanz** [stackblitz/webcontainer-core#194]
Hey there! 👋 

**Describe the bug:**
I am trying to run an AdonisJS 5 project inside a StackBlitz container but I am not able to run it.

When trying to run the code, I have the following error.

```bash
~/projects/node-wgjpqs
❯ node ace serve -w
[ info ]  building project...
[ info ]  starting http server...
Error: Cannot find module '/home/projects/node-wgjpqs/@adonisjs/assembler/build/register'
    at Function.Module._resolveFilename (https://node-wgjpqs.jw.staticblitz.com/blitz.b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62.js:6:185520)
    at Function.Module._load (https://node-wgjpqs.jw.staticblitz.com/blitz.b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62.js:6:183134)
    at Function.executeUserEntryPoint [as runMain] (https://node-wgjpqs.jw.staticblitz.com/blitz.b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62.js:6:794726)
    at Object.a0_0x4ef4 (https://node-wgjpqs.jw.staticblitz.com/blitz.b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62.js:6:1395329)
    at _0x481dcf (https://node-wgjpqs.jw.staticblitz.com/blitz.b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62.js:8:22636)
    at _0x3a4156 (https://node-wgjpqs.jw.staticblitz.com/blitz.b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62.js:11:164647)
    at _0x3551c2 (https://node-wgjpqs.jw.staticblitz.com/blitz.b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62.js:11:140268)
    at Object.run (https://node-wgjpqs.jw.staticblitz.com/blitz.b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62.js:11:139486) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

It seems that StackBlitz container is not able to resolve our modules when booting the code.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-wgjpqs

**Steps to reproduce:**
You can try to run the code by using `node ace serve`.

**Expected behavior:**
The server should start.

**Version of webcontainer:**
Hash: b5c3c7f283d527b6b05ec10dc99d5b2c3d4dec62

**Desktop (please complete the following information):**
```
Browser name  = Chrome Canary
Full version  = 93.0.4543.0 (Official Build) canary (64-bit)

**Comment by SamVerschueren** [comment]
Hi @RomainLanz 👋 ! Thanks for trying out WebContainer. Is it possible that it uses native dependencies under the hood? Native dependencies don't work unless they are compiled to WASM. Not sure if that's the case here though.

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.
