### ISSUE TITLE
Tailwind styles not showing up

### ISSUE THREAD

**Issue by deadcoder0904** [stackblitz/webcontainer-core#222]
**Describe the bug:**
I want Tailwind + Next.js combo to work but the styles aren't showing up.

**Link to the blitz that caused the error:** https://stackblitz.com/edit/next-themes-undefined-bug?file=pages%2F_app.js

**Steps to reproduce:**
Start with the Next.js template & try installing Tailwind using https://tailwindcss.com/docs/guides/nextjs

**Expected behavior:**
Styles should show up

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

Would love if there is an Official Stackblitz template or a guide to follow through. I have checked other Tailwind Stackblitz projects but not sure they are helping me.

Check the `_app.js` file to see I have imported `tailwndcss/tailwindcss`. You can comment that one & uncomment the below one & it still doesn't work.

Even the icons aren't showing up. The code is correct there.

Moreover, the dark theme doesn't show up in the side-by-side container but shows up when I open the full-screen.

**Comment by EricSimons** [comment]
I just tried running this in SB and it appears some of tailwind's styles are ending up in the preview- do you happen to know if this works properly on local? If so, screenshots comparing the two side by side would be super helpful

**Comment by deadcoder0904** [comment]
I can't get it to run on SB. I get this:

```bash
~/projects/next-themes-undefined-bug
❯ npm install && npx next dev
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 0.405s
┌ [2/3] 🚚  Fetching dependencies
└ Completed in 26.193s
┌ [3/3] 🔗  Linking dependencies
└ Completed in 0.919s

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 27.689s
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
SyntaxError: Unexpected token '<'
    at __global_eval__ (https://next-themes-undefined-bug.jw.staticblitz.com/blitz.6a754de1dca8799163c05b54a4efbad0569024b8.js:8:18053)
    at _0xc92fe9 (https://next-themes-undefined-bug.jw.staticblitz.com/blitz.6a754de1dca8799163c05b54a4efbad0569024b8.js:11:175722)
    at _0x3c2055.runInThisContext (https://next-themes-undefined-bug.jw.staticblitz.com/blitz.6a754de1dca8799163c05b54a4efbad0569024b8.js:11:174955)
    at _0x393783 (https://next-themes-undefined-bug.jw.staticblitz.com/blitz.6a754de1dca8799163c05b54a4efbad0569024b8.js:11:174058)
    at wrapSafe (https://next-themes-undefined-bug.jw.staticblitz.com/blitz.6a754de1dca8799163c05b54a4efbad0569024b8.js:6:187598)
    at Module._compile (https://next-themes-undefined-bug.jw.staticblitz.com/blitz.6a754de1dca8799163c05b54a4efbad0569024b8.js:6:188230)
    at Object.Module._extensions..js (https://next-themes-undefined-bug.jw.staticblitz.com/blitz.6a754de1dca8799163c05b54a4efbad0569024b8.js:6:188952)
    at Module.load (https://next-themes-undefined-bug.jw.staticblitz.com/blitz.6a754de1dca8799163c05b54a4efbad0569024b8.js:6:187032)
    at Function.Module._load (https://next-themes-undefined-bug.jw.staticblitz.com/blitz.6a754de1dca8799163c05b54a4efbad0569024b8.js:6:184610)
    at Module.require (https://next-themes-undefined-bug.jw.staticblitz.com/blitz.6a754de1dca8799163c05b54a4efbad0569024b8.js:6:187348)
```

**Comment by HeyGarrison** [comment]
@deadcoder0904 this looks to be working now. Let me know if for some reason I am mistaken but closing for now. ❤️❤️❤️❤️

**Comment by deadcoder0904** [comment]
@HeyGarrison Doesn't work in side-by-side preview. See:

<img width="987" alt="Screenshot 2022-02-04 at 12 10 13 PM" src="https://user-images.githubusercontent.com/16436270/152483895-58fb8050-c0c7-484c-867c-22df5023dc38.png">

But works in New Window. See:

<img width="1440" alt="Screenshot 2022-02-04 at 12 10 42 PM" src="https://user-images.githubusercontent.com/16436270/152483960-3d3d8ec9-5100-4c43-9293-1c6f71afcbf6.png">

**Comment by abid365** [comment]
I want to  use tailwind in my SB vite-react project, but styles are not showing up. 
I additionally installed postcss via npm but it's not working. Suggestions would be very helpful.

Here's the SB Project Link: [https://stackblitz.com/edit/vitejs-vite-e6srde?file=src/App.jsx](url)

![Screenshot from 2023-04-26 20-28-48](https://user-images.githubusercontent.com/69803964/234608218-ce17c233-ba90-4c3b-aab3-f0ed74adfd2e.png)
