### ISSUE TITLE
Import doesn't work if the branch uses Github's new `main` branch. It only works for `master` which is old one.

### ISSUE THREAD

**Issue by deadcoder0904** [stackblitz/webcontainer-core#225]
**Describe the bug:**
I created a new repo & Github's setup is it uses `main` branch instead of `master`

**Steps to reproduce:**
1. Create a local Next.js project
2. Upload it to Github which uses `main` branch
3. Import it in Stackblitz & watch it yelling

**Expected behavior:**
Should support `main` branch by default. Additionally, must have a UI that which allows me to select a primary branch if my git project neither contains `master` or `main`.

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.124
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 101393084,
  "usedJSHeapSize": 92853428,
  "jsHeapSizeLimit": 4294705152
}
```

**Additional context:**
Importing is hidden inside a project. It should be prominent near the templates or somewhere where it can be seen. I can't see it unless I open a project.

**Comment by deadcoder0904** [comment]
Additionally, I can't run it from the `master` branch as well. It throws an error:

```bash
❯ npm install && npx next dev
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 0.478s
┌ [2/3] 🚚  Fetching dependencies
└ Completed in 0.001s
┌ [3/3] 🔗  Linking dependencies
└ Completed in 0.004s

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 0.578s
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
SyntaxError: Unexpected token '<'
    at __global_eval__ (https://nextjs-hywq3y.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:8:17279)
    at _0x5d4bfc (https://nextjs-hywq3y.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:11:191638)
    at _0x5a0173.runInThisContext (https://nextjs-hywq3y.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:11:190861)
    at _0x52c017 (https://nextjs-hywq3y.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:11:189961)
    at wrapSafe (https://nextjs-hywq3y.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:190766)
    at Module._compile (https://nextjs-hywq3y.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:191398)
    at Object.Module._extensions..js (https://nextjs-hywq3y.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:192120)
    at Module.load (https://nextjs-hywq3y.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:190200)
    at Function.Module._load (https://nextjs-hywq3y.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:187776)
    at Module.require (https://nextjs-hywq3y.jw.staticblitz.com/blitz.70a1ff62a0f0131ac0df3c30faf487fef744ac90.js:6:190516)
```

The repo is at https://github.com/deadcoder0904/mdx-bundler-next-themes-error (check the `master` branch which I won't touch)

**Comment by tony19** [comment]
Looks like a duplicate of #195

**Comment by deadcoder0904** [comment]
Yes, it is & do make the import prominent.
