### ISSUE TITLE
TypeError: n._handle.getAsyncId is not a function

### ISSUE THREAD

**Issue by Suryaprakash1024** [stackblitz/webcontainer-core#257]
### Describe the bug

I developing  a telegram bot using nodejs. Actually when I tried on local, it is working fine but it is causing bug in stackblitz.

Console error :

`TypeError: n._handle.getAsyncId is not a function
    at responseKeepAlive (https://github-ej3k7n.jw.staticblitz.com/blitz.84452ea99b8c6a79e19cae2129beaf85d5da007c.js:6:761706)
    at IncomingMessage.responseOnEnd (https://github-ej3k7n.jw.staticblitz.com/blitz.84452ea99b8c6a79e19cae2129beaf85d5da007c.js:6:762037)
    at IncomingMessage.EventEmitter.emit (https://github-ej3k7n.jw.staticblitz.com/blitz.84452ea99b8c6a79e19cae2129beaf85d5da007c.js:6:126312)
    at endReadableNT (https://github-ej3k7n.jw.staticblitz.com/blitz.84452ea99b8c6a79e19cae2129beaf85d5da007c.js:6:489841)
    at https://github-ej3k7n.jw.staticblitz.com/blitz.84452ea99b8c6a79e19cae2129beaf85d5da007c.js:11:125491
    at https://github-ej3k7n.jw.staticblitz.com/blitz.84452ea99b8c6a79e19cae2129beaf85d5da007c.js:11:158166
    at _0x31eff0 (https://github-ej3k7n.jw.staticblitz.com/blitz.84452ea99b8c6a79e19cae2129beaf85d5da007c.js:11:158411)
    at MessagePort._0xe4431a.port1.onmessage (https://github-ej3k7n.jw.staticblitz.com/blitz.84452ea99b8c6a79e19cae2129beaf85d5da007c.js:11:158524)`

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-ej3k7n

### Steps to reproduce

npm install
node index.js

### Expected behavior

The server should run without error 

### Platform

```
Browser name  = Chrome 
Full version  = 89.0.4389.90
Major version = 89
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72910662,
  "usedJSHeapSize": 57096194,
  "jsHeapSizeLimit": 2172649472
}
Hash = 84452ea99b8c6a79e19cae2129beaf85d5da007c
```

**Comment by d3lm** [comment]
Hey there 👋 Thanks for reporting this issue. It's indeed a bug. We'll add this to our list and get back to you once it's been fixed.

**Comment by jrvidal** [comment]
@Suryaprakash1024 Sorry it took so long, but I think this is no longer an issue. Feel free to file a new one if you find something else off.
