### ISSUE TITLE
StackblitzFsGit statusList err ResolveRefError: Could not resolve reference "refs/heads/master".

### ISSUE THREAD

**Issue by masx200** [stackblitz/webcontainer-core#303]
### Describe the bug

ResolveRefError: Could not resolve reference "master".
GitWorkerService: cloned https://github.com/masx200/nextjs-masx200-home.git master
StackblitzFsGit addAll err ResolveRefError: Could not resolve reference "refs/heads/master".
StackblitzFsGit statusList err ResolveRefError: Could not resolve reference "refs/heads/master".
Uncaught (in promise) 
T
a: null
code: "auth/network-request-failed"
message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-l44aph

### Steps to reproduce

import github Repository
https://github.com/masx200/nextjs-masx200-home/

This repository does not have a "master" branch. It only has a "main" branch.

### Expected behavior

There should be no errors.

### Screenshots

![image](https://user-images.githubusercontent.com/34191203/129843984-f698badc-96d8-45ef-9d59-ac896efd30a4.png)
![image](https://user-images.githubusercontent.com/34191203/129844080-1cb2f1a5-e894-471f-8d45-6acd1bd2c12d.png)

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.131
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.73
performance.memory = {
  "totalJSHeapSize": 48599937,
  "usedJSHeapSize": 45783917,
  "jsHeapSizeLimit": 2172649472
}
Hash = f91df8ee833f18bedf806af681eeaccd3addac72
```

**Comment by tony19** [comment]
This is a duplicate of #195

**Comment by ElMassimo** [comment]
Running into the same error even though the repo does have a `master` branch:

<img width="1062" alt="Screen Shot 2022-03-24 at 10 44 57" src="https://user-images.githubusercontent.com/1158253/159929693-939e682a-87f7-45e9-a520-080ee0670a0f.png">

```
gitworker-e9c1e20e6208.js:2
StackblitzFsGit addAll err ResolveRefError: Could not resolve reference "refs/heads/master".
    at Function.resolve (gitworker-e9c1e20e6208.js:2:176948)
    at async gitworker-e9c1e20e6208.js:2:200082
    at async he.readdir (gitworker-e9c1e20e6208.js:2:200526)
    at async Promise.all (/edit/index 0)
    at async l (gitworker-e9c1e20e6208.js:2:202875)
    at async f (gitworker-e9c1e20e6208.js:2:203105)
    at async ar (gitworker-e9c1e20e6208.js:2:235004)
    at async Object.addAll (gitworker-e9c1e20e6208.js:2:245818)
(anonymous) @ gitworker-e9c1e20e6208.js:2
Promise.catch (async)
addAll @ gitworker-e9c1e20e6208.js:2
addAll @ gitworker-e9c1e20e6208.js:2
e.onCall @ index.js:61
(anonymous) @ index.js:16

gitworker-e9c1e20e6208.js:2
StackblitzFsGit statusList err ResolveRefError: Could not resolve reference "refs/heads/master".
    at Function.resolve (gitworker-e9c1e20e6208.js:2:176948)
    at async gitworker-e9c1e20e6208.js:2:200082
    at async he.readdir (gitworker-e9c1e20e6208.js:2:200526)
    at async Promise.all (/edit/index 0)
    at async l (gitworker-e9c1e20e6208.js:2:202875)
    at async f (gitworker-e9c1e20e6208.js:2:203105)
    at async ar (gitworker-e9c1e20e6208.js:2:235004)
    at async ur.statusList (gitworker-e9c1e20e6208.js:2:237735)
    at async Object.statusList (gitworker-e9c1e20e6208.js:2:245942)
```
