### ISSUE TITLE
BUG: crypto.createHmac not working

### ISSUE THREAD

**Issue by Cubelrti** [stackblitz/webcontainer-core#31]
**Describe the bug**
Node REPL failed when running `crypto.createHmac`

**Link to the blitz that caused the error**
https://stackblitz.com/edit/http-server-fnwea1?file=server.js

**To Reproduce**
Open node REPL, enter `require('crypto').createHmac('sha256', 'abcdefg').update('I love cupcakes').digest('hex');` and I got TypeError.

```
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at new e.exports (https://http-server-fnwea1.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:1179499)
    at new Hmac (https://http-server-fnwea1.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:924216)
    at Object.createHmac (https://http-server-fnwea1.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:612717)
    at eval (REPL1:1:19)
    at __global_eval__ (https://http-server-fnwea1.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:8:15949)
    at _0x18a892 (https://http-server-fnwea1.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:21075)
    at Script.runInThisContext (https://http-server-fnwea1.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:20268)
    at Script.runInThisContext (https://http-server-fnwea1.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:458038)
    at REPLServer.p (https://http-server-fnwea1.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:1092122)
    at bound (https://http-server-fnwea1.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:1322974)
```

**Expected behavior**
Correct hash should be printed.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.62
performance.memory = {
  totalJSHeapSize: 82262584,
  usedJSHeapSize: 73815152,
  jsHeapSizeLimit: 4294705152
}

**Comment by SamVerschueren** [comment]
Hi @Cubelrti! Thanks for trying it out :). It's correct that `crypto` is not yet entirely implemented, we're aware of that and it's something we have planned to do soon. I believe md5 is implemented because Webpack uses it under the hood for hashing, but all other stuff is definitely lacking.

**Comment by jrvidal** [comment]
@Cubelrti  This is now fixed :tada:

**Comment by Cubelrti** [comment]
Wow you guys are so awesome! Can't wait to see General Availability for WebContainer, looking forward to get involved more👍
