### ISSUE TITLE
Firebase Tools

### ISSUE THREAD

**Issue by ajonp** [stackblitz/webcontainer-core#319]
### Describe the bug

I am unable to initialize products by running

`firebase init`

or 

`firebase projects:addfirebase`

It will timeout or show this error...

```
[error] Error: Failed to list Firebase projects. See firebase-debug.log for more info.
[debug] [2021-09-07T19:51:33.399Z] ----------------------------------------------------------------------
[debug] [2021-09-07T19:51:33.399Z] Command:       /usr/local/bin/node /home/projects/node-2jcbtf/node_modules/.bin/firebase projects:addfirebase
[debug] [2021-09-07T19:51:33.399Z] CLI Version:   9.17.0
[debug] [2021-09-07T19:51:33.400Z] Platform:      linux
[debug] [2021-09-07T19:51:33.400Z] Node Version:  v14.16.0
[debug] [2021-09-07T19:51:33.400Z] Time:          Tue Sep 07 2021 15:51:33 GMT-0400 (Eastern Daylight Time)
[debug] [2021-09-07T19:51:33.400Z] ----------------------------------------------------------------------
[debug] 
[debug] [2021-09-07T19:51:33.403Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2021-09-07T19:51:33.404Z] > authorizing via signed-in user (alex@codingcat.dev)
[debug] [2021-09-07T19:51:33.405Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/availableProjects pageSize=100
[debug] [2021-09-07T19:51:33.814Z] Failed to make request: Invalid response body while trying to fetch https://firebase.googleapis.com/v1beta1/availableProjects?pageSize=100: incorrect header check
[debug] [2021-09-07T19:51:33.815Z] FirebaseError: Failed to make request: Invalid response body while trying to fetch https://firebase.googleapis.com/v1beta1/availableProjects?pageSize=100: incorrect header check
    at Client.request (/home/projects/node-2jcbtf/node_modules/firebase-tools/lib/apiv2.js:109:19)
    at async getProjectPage (/home/projects/node-2jcbtf/node_modules/firebase-tools/lib/management/projects.js:233:17)
    at async getAvailableCloudProjectPage (/home/projects/node-2jcbtf/node_modules/firebase-tools/lib/management/projects.js:265:16)
    at async Object.promptAvailableProjectId (/home/projects/node-2jcbtf/node_modules/firebase-tools/lib/management/projects.js:143:41)
    at async Command.eval [as actionFn] (/home/projects/node-2jcbtf/node_modules/firebase-tools/lib/commands/projects-addfirebase.js:12:21)
[error] 
[error] Error: Failed to list available Google Cloud Platform projects. See firebase-debug.log for more info.
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-2jcbtf

### Steps to reproduce

1. wait for install to finish
2. run `firebase init`
3. you may be asked to login and then add token
4. after correct authorization is added, there will be issues in debug
3. view firebase-debug.info

### Expected behavior

Expectation is that all calls work for firebase.

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.159
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76481163,
  "usedJSHeapSize": 70253487,
  "jsHeapSizeLimit": 4294705152
}
Hash = dd88a1655a6ea3f646b7279b57a2839a424ce920
```

### Additional context

I am wondering if somehow the CLI is not able to access the correct access_token?

**Comment by d3lm** [comment]
Hey there! Thanks for reporting this issue. I haven't looked more closely at your issue but this might be related to some internal compression bug related to gzip. The `incorrect header check` could come from the `zlib` builtins. It would be awesome if you could investigate a bit and if possible provide a more minimal reproduction. This would help us tremendously and increases the chance for this to be fixed more quickly. I'd recommend you you start debugging your project and setp into `node_modules` and see if you can find the culprit or at least if you can reduce the complexity of the project.

**Tip**: You can open any file in `node_modules` with the built-in `code` command from the terminal, e.g. `code node_modules/chalk/index.js`. This will open the file in the editor and you can add `debugger` statements.

Thanks!

**Comment by azu** [comment]
> incorrect header check

I met similar issue on using [kuromoji.js](https://github.com/takuyaa/kuromoji.js).
I've created reproduce container.

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-gj9gls?file=README.md,index.mjs

```
❯ npm test
$ node index.mjs
Success: base.dat.gz
Error: cc.dat.gz Error: incorrect header check
    at InternalError (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:291731)
    at zlibOnError (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:1719050)
    at Zlib.prototype._error (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:394064)
    at Zlib.prototype._checkError (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:393775)
    at Zlib.prototype._after (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:393850)
    at Zlib.prototype._write/< (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:392183)
    at _0x5d97a4 (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:15:150541)
    at _0x2fb6cc/< (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:15:150281)
    at <anonymous> (<anonymous>) {
  errno: -3,
  code: undefined
}
Success: check.dat.gz
Success: tid.dat.gz
Success: tid_map.dat.gz
Success: tid_pos.dat.gz
Success: unk.dat.gz
Success: unk_char.dat.gz
Success: unk_compat.dat.gz
Success: unk_invoke.dat.gz
Success: unk_map.dat.gz
Success: unk_pos.dat.gz
```

In Local Node.js v16.19.0

```
Success: unk_char.dat.gz
Success: unk_compat.dat.gz
Success: unk_invoke.dat.gz
Success: unk_map.dat.gz
Success: cc.dat.gz
Success: tid_map.dat.gz
Success: base.dat.gz
Success: check.dat.gz
Success: tid.dat.gz
Success: unk.dat.gz
Success: unk_pos.dat.gz
Success: tid_pos.dat.gz
```

Web Container can not decode https://github.com/takuyaa/kuromoji.js/blob/master/dict/cc.dat.gz by `zlib.gunzip`.

**Comment by d3lm** [comment]
Thanks for reporting this issue. As mentioned ion #973, there may be an issue with zlib on our end and we'll investigate when we find time for it. We'll keep you posted here if there's any progress.
