### ISSUE TITLE
JS Anti-NPM

### ISSUE THREAD

**Issue by MISHA35656** [stackblitz/webcontainer-core#322]
### Describe the bug

When im importing module in js, and noding, file is consoled error. Here's error:

Please accept to work
ReferenceError: Notification is not defined
    at Object.eval (/home/projects/node-nbrhlm/index.js:7:1)
    at Object.function (https://node-nbrhlm.jw.staticblitz.com/blitz.dd88a1655a6ea3f646b7279b57a2839a424ce920.js:11:124216)
    at Module._compile (https://node-nbrhlm.jw.staticblitz.com/blitz.dd88a1655a6ea3f646b7279b57a2839a424ce920.js:6:167879)
    at Object.Module._extensions..js (https://node-nbrhlm.jw.staticblitz.com/blitz.dd88a1655a6ea3f646b7279b57a2839a424ce920.js:6:168238)
    at Module.load (https://node-nbrhlm.jw.staticblitz.com/blitz.dd88a1655a6ea3f646b7279b57a2839a424ce920.js:6:166316)
    at Function.Module._load (https://node-nbrhlm.jw.staticblitz.com/blitz.dd88a1655a6ea3f646b7279b57a2839a424ce920.js:6:163856)
    at Function.executeUserEntryPoint [as runMain] (https://node-nbrhlm.jw.staticblitz.com/blitz.dd88a1655a6ea3f646b7279b57a2839a424ce920.js:6:691401)
    at Object.a0_0x1ec6 (https://node-nbrhlm.jw.staticblitz.com/blitz.dd88a1655a6ea3f646b7279b57a2839a424ce920.js:6:1252697)
    at _0x2bee85 (https://node-nbrhlm.jw.staticblitz.com/blitz.dd88a1655a6ea3f646b7279b57a2839a424ce920.js:8:26842)
    at _0x6f2d0e (https://node-nbrhlm.jw.staticblitz.com/blitz.dd88a1655a6ea3f646b7279b57a2839a424ce920.js:11:56770)

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-nbrhlm?file=index.js

### Steps to reproduce

1. Install Push.js module
2. Connect package to code
3. Set code of index.js to 
const push = require('push.js');
const fs = require('fs');

console.log('Please accept to work');
Notification.requestPermission();
4. View the error in terminal (no new tab with text)

### Expected behavior

Im needed to test push.js module. Needed to be a open new tab with text 'Allow site show notifications?'

### Screenshots

https://i.imgur.com/bGcAWBW.png here screenshot

### Platform

```
Browser name  = Chrome 
Full version  = 93.0.4577.63
Major version = 93
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76182634,
  "usedJSHeapSize": 66877674,
  "jsHeapSizeLimit": 2044198912
}
Hash = dd88a1655a6ea3f646b7279b57a2839a424ce920
```

**Comment by jrvidal** [comment]
Hi @MISHA35656 this is working as intended. WebContainers is a _Node.js_ runtime. The code you're showing us would not work locally on Node.js either, would it? 

What you _can_ do is to run a Node.js application that _serves_ a web application using notifications. See for instance https://next.new for an example using Next.js (though you can write it using any library/framework you want).

Hope that helps.
