### ISSUE TITLE
SyntaxError when starting Vite after `npm i vuex`

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#351]
### Describe the bug

Installing `vuex` causes `vite` to hit a `SyntaxError`, as seen in the terminal log below. There's no need to even invoke `vuex` in the project.

```
~/projects/stackblitz-bug-syntax-error-after-npm-i-vuex
❯ npm install && yarn dev
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 0.21s
┌ [2/3] 🚚  Fetching dependencies
│ info pruneDeps Excluding 12 dependencies. For more information use `--verbose`.
└ Completed in 1.044s
┌ [3/3] 🔗  Linking dependencies
└ Completed in 0.557s
info security We found `install` scripts which turbo skips for security reasons. For more information see https://turbo.sh/install-scripts.
├─ core-js@2.6.12
└─ esbuild@0.13.8

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 1.878s
$ vite
SyntaxError: Invalid or unexpected token
    at __global_eval__ (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:8:20243)
    at _0x277d07 (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:11:124947)
    at _0x365c7d._compile (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:11:123136)
    at _0x54839c (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:11:120921)
    at wrapSafe (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:6:166884)
    at Module._compile (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:6:167516)
    at Object.Module._extensions..js (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:6:168238)
    at Module.load (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:6:166316)
    at Function.Module._load (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:6:163856)
    at Function.executeUserEntryPoint [as runMain] (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:6:699031)
failed to load config from /home/projects/stackblitz-bug-syntax-error-after-npm-i-vuex/vite.config.js
error when starting dev server:
Error: The service was stopped
    at eval (/home/projects/stackblitz-bug-syntax-error-after-npm-i-vuex/node_modules/esbuild/lib/main.js:1237:25)
    at eval (/home/projects/stackblitz-bug-syntax-error-after-npm-i-vuex/node_modules/esbuild/lib/main.js:629:9)
    at Socket.afterClose (/home/projects/stackblitz-bug-syntax-error-after-npm-i-vuex/node_modules/esbuild/lib/main.js:607:7)
    at Socket.EventEmitter.emit (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:6:126742)
    at endReadableNT (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:6:505167)
    at https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:11:138038
    at https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:11:112207
    at _0x4c7835 (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:11:112436)
    at MessagePort._0x43397b.port1.onmessage (https://stackblitz-bug-syntax-error-after-npm-i-vuex.jw.staticblitz.com/blitz.c39325dd3d976e6d2170e0078ef1d9bb3de015b9.js:11:112590)
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-bug-syntax-error-after-npm-i-vuex?file=vite.config.js

### Steps to reproduce

1. Open [Vite + Vue 2 Starter](https://stackblitz.com/edit/vue2-vite-starter)
2. In terminal, install `vuex` with: `npm i vuex`
3. Restart `vite` dev server with: `yarn dev`
4. Observe the error

### Expected behavior

The blitz starts without error

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 80983870,
  "usedJSHeapSize": 71975242,
  "jsHeapSizeLimit": 4294705152
}
Hash = c39325dd3d976e6d2170e0078ef1d9bb3de015b9
```

**Comment by tony19** [comment]
@klevron Thanks! I confirmed the issue is no longer reproducible.

**Comment by klevron** [comment]
The error is back this morning

**Comment by tony19** [comment]
@klevron I think it's fixed now based on https://github.com/stackblitz/webcontainer-core/issues/356#issuecomment-947633187
