### ISSUE TITLE
The package "esbuild-linux-64" could not be found, and is needed by esbuild.

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#352]
### Describe the bug

[This Vite project](https://github.com/tony19-sandbox/vmodel-demo) seems to fail startup in a Node.js container, as shown in the terminal log below. The error is the same one from https://github.com/vitejs/vite/issues/5187, and installing `esbuild@0.13.4` (as a [workaround](https://github.com/vitejs/vite/issues/5187#issuecomment-934526169)) does resolve the error, but then it runs into #351.

```
~/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found
❯ npm install && npm run serve
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 0.209s
┌ [2/3] 🚚  Fetching dependencies
│ info pruneDeps Excluding 2 dependencies. For more information use `--verbose`.
└ Completed in 0.819s
┌ [3/3] 🔗  Linking dependencies
└ Completed in 0.877s
info security We found `install` scripts which turbo skips for security reasons. For more information see https://turbo.sh/install-scripts.
├─ core-js@2.6.12
└─ esbuild@0.13.8

success Saved lockfile "package-lock.json"
success Saved lockfile "yarn.lock"
success Updated "package.json"

success Install finished in 2s
$ vite preview
failed to load config from /home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/vite.config.js
error when starting preview server:
Error: The package "esbuild-linux-64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
by esbuild to install the correct binary executable for your current platform.
    at generateBinPath (/home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/node_modules/esbuild/lib/main.js:1643:15)
    at esbuildCommandAndArgs (/home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/node_modules/esbuild/lib/main.js:1699:11)
    at ensureServiceIsRunning (/home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/node_modules/esbuild/lib/main.js:1856:25)
    at Object.build (/home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/node_modules/esbuild/lib/main.js:1749:26)
    at bundleConfigFile (/home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/node_modules/vite/dist/node/chunks/dep-be032392.js:68624:34)
    at loadConfigFromFile (/home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/node_modules/vite/dist/node/chunks/dep-be032392.js:68601:35)
    at Object.resolveConfig (/home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/node_modules/vite/dist/node/chunks/dep-be032392.js:68151:34)
    at CAC.eval (/home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/node_modules/vite/dist/node/cli.js:781:36)
    at CAC.runMatchedCommand (/home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/node_modules/vite/dist/node/cli.js:633:34)
    at CAC.parse (/home/projects/stackblitz-bug-esbuild-linux-64-could-not-be-found/node_modules/vite/dist/node/cli.js:560:12)
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-bug-esbuild-linux-64-could-not-be-found?file=package.json

### Steps to reproduce

1. Import this [Vite project from GitHub](https://github.com/tony19-sandbox/vmodel-demo) into a Node.js container.
2. Install deps and start the dev server: `npm install && npm run serve`
3. Observe the error

### Expected behavior

The blitz starts without error

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 89984606,
  "usedJSHeapSize": 62801150,
  "jsHeapSizeLimit": 4294705152
}
Hash = c39325dd3d976e6d2170e0078ef1d9bb3de015b9
```

**Comment by jamest-pin** [comment]
This started happening to me today. Was previously ok in this project a couple of weeks ago with no changes to build script or other versions. 
I'm using `node:18-alpine`
