### ISSUE TITLE
Nuxt 3 fails with [uncaughtException] r.writeLatin1String is not a function

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#364]
### Describe the bug

This [Nuxt 3 project](https://stackblitz.com/edit/nuxt3-paint-worklet) works fine offline (on macOS) but emits the following error in StackBlitz:

```
~/projects/nuxt3-paint-worklet
Nuxt CLI v3.0.0-27252999.d2cc9e4                                                                                                                              18:25:01
                                                                                                                                                              18:25:02
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.104:3000/

ℹ Vite warmed up in 506ms                                                                                                                                     18:25:06
✔ Vite server built in 715ms                                                                                                                                  18:25:07
✔ Nitro built in 154 ms                                                                                                                                       18:25:07

 ERROR  [uncaughtException] r.writeLatin1String is not a function                                                                                             18:25:07

  at https://nuxt3-paint-worklet.jw.staticblitz.com/blitz.7a2e0ba760d73d6374a3060937bfe743461e6f65.js:6:529178
  at writeGeneric (https://nuxt3-paint-worklet.jw.staticblitz.com/blitz.7a2e0ba760d73d6374a3060937bfe743461e6f65.js:6:529459)
  at Socket._writeGeneric (https://nuxt3-paint-worklet.jw.staticblitz.com/blitz.7a2e0ba760d73d6374a3060937bfe743461e6f65.js:6:204584)
  at Socket._write (https://nuxt3-paint-worklet.jw.staticblitz.com/blitz.7a2e0ba760d73d6374a3060937bfe743461e6f65.js:6:204742)
  at doWrite (https://nuxt3-paint-worklet.jw.staticblitz.com/blitz.7a2e0ba760d73d6374a3060937bfe743461e6f65.js:6:520897)
  at clearBuffer (https://nuxt3-paint-worklet.jw.staticblitz.com/blitz.7a2e0ba760d73d6374a3060937bfe743461e6f65.js:6:522575)
  at Socket.Writable.uncork (https://nuxt3-paint-worklet.jw.staticblitz.com/blitz.7a2e0ba760d73d6374a3060937bfe743461e6f65.js:6:525095)
  at ClientRequest.OutgoingMessage.end (https://nuxt3-paint-worklet.jw.staticblitz.com/blitz.7a2e0ba760d73d6374a3060937bfe743461e6f65.js:6:611554)
  at IncomingMessage.onend (https://nuxt3-paint-worklet.jw.staticblitz.com/blitz.7a2e0ba760d73d6374a3060937bfe743461e6f65.js:6:507046)
  at Object.onceWrapper (https://nuxt3-paint-worklet.jw.staticblitz.com/blitz.7a2e0ba760d73d6374a3060937bfe743461e6f65.js:6:124448)


~/projects/nuxt3-paint-worklet 11s
❯ 
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/nuxt3-paint-worklet

### Steps to reproduce

1. Open blitz, and allow it to boot up
2. Observe the error in the terminal output

### Expected behavior

The Nuxt project runs without error

### Platform

```
Browser name  = Chrome 
Full version  = 94.0.4606.81
Major version = 94
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82546872,
  "usedJSHeapSize": 74749124,
  "jsHeapSizeLimit": 4294705152
}
Hash = 7a2e0ba760d73d6374a3060937bfe743461e6f65
```

**Comment by SamVerschueren** [comment]
We fixed the issue with the `writeLatin1String` function call. However, for some reason, `nuxt3` dependency doesn't work on StackBlitz. We have to digg deeper to find out why that's the case. It works with just `nuxt` though.

https://stackblitz.com/edit/github-xvms61?file=package.json
