### ISSUE TITLE
Failed to run test for Nx Workspace Angular Project

### ISSUE THREAD

**Issue by dalenguyen** [stackblitz/webcontainer-core#380]
### Describe the bug

I was testing the Nx Project using Stackbliz. 

Project: https://stackblitz.com/github/nrwl/stackblitz-nx-angular?preset=node 

The Angular app runs without any issue. However, when running the testing command, the error appears. 

### Link to the blitz that caused the error

https://stackblitz.com/github/nrwl/stackblitz-nx-angular?preset=node

### Steps to reproduce

Go to https://stackblitz.com/github/nrwl/stackblitz-nx-angular?preset=node 

Open Terminal

Run Test

```
yarn test
```

### Expected behavior

The test can run without any issues. 

### Screenshots

![image](https://user-images.githubusercontent.com/14116156/140453986-645d3605-68a9-4eb6-86d1-d3482c590c06.png)

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.54
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 111278612,
  "usedJSHeapSize": 89489680,
  "jsHeapSizeLimit": 4294705152
}
Hash = eb19bc088249a645473767848622a1d98c51b8f3
```

### Additional context

Error logs

```
~/projects/vbwiyymvx.github
❯ yarn test
$ nx test

> nx run my-app:test 
  console.error
    JIT compilation failed for NgModule [Function: DynamicTestModule]

      at getCompilerFacade (../../../packages/core/src/compiler/compiler_facade.ts:34:9)
      at Function.get (../../../packages/core/src/render3/jit/module.ts:119:23)
      at getNgModuleDef (../../../packages/core/src/render3/definition.ts:746:23)
      at verifySemanticsOfNgModuleDef (../../../packages/core/src/render3/jit/module.ts:207:4)
      at Function.get (../../../packages/core/src/render3/jit/module.ts:171:15)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.applyProviderOverridesToModule (../../../packages/core/testing/src/r3_test_bed_compiler.ts:415:14)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.compileTestModule (../../../packages/core/testing/src/r3_test_bed_compiler.ts:680:4)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.finalize (../../../packages/core/testing/src/r3_test_bed_compiler.ts:247:10)
      at TestBedRender3.get (../../../packages/core/testing/src/r3_test_bed.ts:417:6)
      at TestBedRender3.Object.<anonymous>.TestBedRender3.inject (../../../packages/core/testing/src/r3_test_bed.ts:315:23)
      at TestBedRender3.Object.<anonymous>.TestBedRender3.createComponent (../../../packages/core/testing/src/r3_test_bed.ts:372:29)
      at Function.Object.<anonymous>.TestBedRender3.createComponent (../../../packages/core/testing/src/r3_test_bed.ts:191:4)
      at eval (src/app/app.component.spec.ts:13:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:408:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3766:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:56)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:168:47)
      at Object.wrappedFunc (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4251:34)
      at TestScheduler.scheduleTests (../../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../../node_modules/@jest/core/build/runJest.js:401:19)
      at _run10000 (../../node_modules/@jest/core/build/cli/index.js:320:7)
      at Object.runCLI (../../node_modules/@jest/core/build/cli/index.js:173:3)
```

**Comment by d3lm** [comment]
Hey! I can confirm that it's failing and it has something to do with JIT compilation. Did you try to verify if you don't get the same error locally? You could try to download the project and run it locally.

Also, when I open the project it gets stuck at `nx serve` for some reason.

**Comment by dalenguyen** [comment]
It works fine locally. For the `nx serve`, I think it takes a few minutes to start. 

![image](https://user-images.githubusercontent.com/14116156/140622208-56d1cf3c-ab24-4d11-9c80-c5cd61e9710c.png)

**Comment by d3lm** [comment]
Ok thanks for verifying. Though it should not take a few minutes to serve the app 🤔

**Comment by dalenguyen** [comment]
@jrvidal I'm not what changed, but looks like it works now. 

```
~/projects/vbwiyymvx.github
❯ yarn test
$ nx test

> nx run my-app:test [existing outputs match the cache, left as is]
 PASS   my-app  apps/my-app/src/app/app.component.spec.ts
  AppComponent
    ✓ should create the app (458 ms)
    ✓ should have as title 'my-app' (422 ms)
    ✓ should render title (418 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        2.823 s
Ran all test suites.

———————————————————————————————————————————————

>  NX   SUCCESS  Running target "test" succeeded

  Nx read the output from cache instead of running the command for 1 out of 1 tasks.
```

**Comment by d3lm** [comment]
Recently we have shipped support for experimental vm modules which, AFAIK, is used by jest.

I am going to close this, and if something comes up feel free to open a new issue.
