### ISSUE TITLE
require() of ES modules is not supported

### ISSUE THREAD

**Issue by karanganesan** [stackblitz/webcontainer-core#419]
### Describe the bug

500
Must use import to load ES Module: /home/projects/sveltekit-m2vj4h/node_modules/three/examples/jsm/controls/OrbitControls.js
require() of ES modules is not supported.
require() of /home/projects/sveltekit-m2vj4h/node_modules/three/examples/jsm/controls/OrbitControls.js from /home/projects/sveltekit-m2vj4h/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename OrbitControls.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/projects/sveltekit-m2vj4h/node_modules/three/examples/jsm/package.json.
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/projects/sveltekit-m2vj4h/node_modules/three/examples/jsm/controls/OrbitControls.js
require() of ES modules is not supported.
require() of /home/projects/sveltekit-m2vj4h/node_modules/three/examples/jsm/controls/OrbitControls.js from /home/projects/sveltekit-m2vj4h/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename OrbitControls.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/projects/sveltekit-m2vj4h/node_modules/three/examples/jsm/package.json.

    at Object.Module._extensions..js (https://sveltekit-m2vj4h.w.staticblitz.com/blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:6:168131)
    at Module.load (https://sveltekit-m2vj4h.w.staticblitz.com/blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:6:166317)
    at Function.Module._load (https://sveltekit-m2vj4h.w.staticblitz.com/blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:6:163857)
    at Module.require (https://sveltekit-m2vj4h.w.staticblitz.com/blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:6:166635)
    at i (https://sveltekit-m2vj4h.w.staticblitz.com/blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:6:427481)
    at _0xa8ceda (https://sveltekit-m2vj4h.w.staticblitz.com/blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:11:118862)
    at nodeRequire (/home/projects/sveltekit-m2vj4h/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66559:17)
    at ssrImport (/home/projects/sveltekit-m2vj4h/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66501:20)
    at eval (/node_modules/svelte-cubed/components/controls/OrbitControls.svelte:11:37)
    at async instantiateModule (/home/projects/sveltekit-m2vj4h/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66544:9)

### Link to the blitz that caused the error

https://stackblitz.com/edit/sveltekit-m2vj4h?file=src%2Froutes%2Findex.svelte

### Steps to reproduce

open https://stackblitz.com/edit/sveltekit-m2vj4h?file=src%2Froutes%2Findex.svelte

### Expected behavior

to run?

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 94045185,
  "usedJSHeapSize": 86012449,
  "jsHeapSizeLimit": 2172649472
}
Hash = 5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b
```

**Comment by karanganesan** [comment]
reference repl - https://svelte.dev/repl/fb41dd0a4f81437393dc48b6f3e547f2?version=3.44.2

**Comment by jrvidal** [comment]
@karanganesan Thanks for the report.

I am unable to run the project locally, I get a blank 500 page (using node v16.13):
```
500
require() of ES Module /tmp/sveltemodules-RlN/node_modules/three/examples/jsm/controls/OrbitControls.js from /tmp/sveltemodules-RlN/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js not supported.
Instead change the require of OrbitControls.js in /tmp/sveltemodules-RlN/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js to a dynamic import() which is available in all CommonJS modules.
Error [ERR_REQUIRE_ESM]: require() of ES Module /tmp/sveltemodules-RlN/node_modules/three/examples/jsm/controls/OrbitControls.js from /tmp/sveltemodules-RlN/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js not supported.
Instead change the require of OrbitControls.js in /tmp/sveltemodules-RlN/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js to a dynamic import() which is available in all CommonJS modules.
    at nodeRequire (/tmp/sveltemodules-RlN/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66559:17)
    at ssrImport (/tmp/sveltemodules-RlN/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66501:20)
    at eval (/node_modules/svelte-cubed/components/controls/OrbitControls.svelte:11:37)
    at async instantiateModule (/tmp/sveltemodules-RlN/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66544:9)
```

Is this expected?

**Comment by jrvidal** [comment]
:wave: It seems this issue has been sitting for a while without new info. I'm closing this, but please feel free to open a new one if you still encounter this problem.

**Comment by IgorArnaut** [comment]
It also doesn't work with Angular Starter project.

**Comment by jrvidal** [comment]
@IgorArnaut Can you provide a link for the project that does not work?

**Comment by IgorArnaut** [comment]
> @IgorArnaut Can you provide a link for the project that does not work?
https://stackblitz.com/edit/m7nmdq?file=README.md

**Comment by jrvidal** [comment]
I see you already opened https://github.com/stackblitz/webcontainer-core/issues/1055, let's continue there.
