### ISSUE TITLE
Webcontainer doesn't work as installed Typescript version is higher than 4.5.0

### ISSUE THREAD

**Issue by EricPrits** [stackblitz/webcontainer-core#474]
### Describe the bug

When trying to initialize the webcontainer for an Angular project I get the following error and the webcontaoner won't load : (node:6) UnhandledPromiseRejectionWarning: Error: The Angular Compiler requires TypeScript >=4.4.2 and <4.5.0 but 4.5.3 was found instead.
    at checkVersion (file:///home/projects/angular-milw1r/node_modules/@angular/compiler-cli/bundles/index.js:17524:11)
    at verifySupportedTypeScriptVersion (file:///home/projects/angular-milw1r/node_modules/@angular/compiler-cli/bundles/index.js:17528:3)
    at new NgtscProgram (file:///home/projects/angular-milw1r/node_modules/@angular/compiler-cli/bundles/index.js:17678:7)
    at AngularWebpackPlugin.updateAotProgram (/home/projects/angular-milw1r/node_modules/@ngtools/webpack/src/ivy/plugin.js:321:32)
    at eval (/home/projects/angular-milw1r/node_modules/@ngtools/webpack/src/ivy/plugin.js:198:24)
    at Hook.eval [as call] (eval at _0x53a6f5 (https://angular-milw1r.w.staticblitz.com/blitz.c1a2f33ebdb80ec1573b6337c828d176e80f0398.js:11:220541), <anonymous>:20:1)
    at Hook.CALL_DELEGATE [as _call] (/home/projects/angular-milw1r/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/projects/angular-milw1r/node_modules/webpack/lib/Compiler.js:1054:30)
    at eval (/home/projects/angular-milw1r/node_modules/webpack/lib/Compiler.js:1099:29)
    at eval (eval at _0x53a6f5 (https://angular-milw1r.w.staticblitz.com/blitz.c1a2f33ebdb80ec1573b6337c828d176e80f0398.js:11:220541), <anonymous>:31:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-milw1r?file=src%2Ftest.ts

### Steps to reproduce

1. Open stackblitz to run Angular code
2. Webcontainer fails to render

### Expected behavior

The webcontainer should load and render the code

### Screenshots

![image](https://user-images.githubusercontent.com/22328440/145593232-f1052cfc-e9ed-4d91-96db-536750e87028.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.55
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43
performance.memory = {
  "totalJSHeapSize": 100157933,
  "usedJSHeapSize": 95187381,
  "jsHeapSizeLimit": 4294705152
}
Hash = c1a2f33ebdb80ec1573b6337c828d176e80f0398
```

**Comment by jrvidal** [comment]
@EricPrits Thanks for the report. This is an upstream issue, see https://github.com/stackblitz/webcontainer-core/issues/473
