### ISSUE TITLE
UnhandledPromiseRejectionWarn during initial opening of the 

### ISSUE THREAD

**Issue by kaankork** [stackblitz/webcontainer-core#479]
### Describe the bug

I'm trying to work on the [ready-made sample project](https://angular.io/start#create-the-sample-project), which is listed on the official Angular website. As instructed, I fork the repo and see the `Generating browser application bundles (phase: setup)..` in my terminal. 

Next, however, I get the following error in terminal and the preview interface on the right side does not display the UI, instead it's a blank white page.
```
(node:6) UnhandledPromiseRejectionWarning: Error: The Angular Compiler requires TypeScript >=4.4.2 and <4.5.0 but 4.5.3 was found instead.
    at checkVersion (file:///home/projects/angular-8gqmgh-yu2ucz/node_modules/@angular/compiler-cli/bundles/index.js:17524:11)
    at verifySupportedTypeScriptVersion (file:///home/projects/angular-8gqmgh-yu2ucz/node_modules/@angular/compiler-cli/bundles/index.js:17528:3)
    at new NgtscProgram (file:///home/projects/angular-8gqmgh-yu2ucz/node_modules/@angular/compiler-cli/bundles/index.js:17678:7)
    at AngularWebpackPlugin.updateAotProgram (/home/projects/angular-8gqmgh-yu2ucz/node_modules/@ngtools/webpack/src/ivy/plugin.js:321:32)
    at eval (/home/projects/angular-8gqmgh-yu2ucz/node_modules/@ngtools/webpack/src/ivy/plugin.js:198:24)
    at Hook.eval [as call] (eval at _0x53a6f5 (https://angular-8gqmgh-yu2ucz.w.staticblitz.com/blitz.c1a2f33ebdb80ec1573b6337c828d176e80f0398.js:11:220541), <anonymous>:20:1)
    at Hook.CALL_DELEGATE [as _call] (/home/projects/angular-8gqmgh-yu2ucz/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/projects/angular-8gqmgh-yu2ucz/node_modules/webpack/lib/Compiler.js:1054:30)
    at eval (/home/projects/angular-8gqmgh-yu2ucz/node_modules/webpack/lib/Compiler.js:1099:29)
    at eval (eval at _0x53a6f5 (https://angular-8gqmgh-yu2ucz.w.staticblitz.com/blitz.c1a2f33ebdb80ec1573b6337c828d176e80f0398.js:11:220541), <anonymous>:31:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-8gqmgh-yu2ucz?file=src%2Fapp%2Fapp.component.ts

### Steps to reproduce

1. Click on Fork

### Expected behavior

It is supposed to install all dependencies and display the web UI in the preview window on the right side. 

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82646657,
  "usedJSHeapSize": 79204253,
  "jsHeapSizeLimit": 4294705152
}
Hash = c1a2f33ebdb80ec1573b6337c828d176e80f0398
```

**Comment by jrvidal** [comment]
@kaankork Thanks for the report. This seems to be an upstream issue, see #477 and #473
