### ISSUE TITLE
node:6) UnhandledPromiseRejectionWarning: Error

### ISSUE THREAD

**Issue by DANILORE** [stackblitz/webcontainer-core#485]
### Describe the bug

/projects/quhuvj--run
❯ npm install && turbo start
warn preInstall No repository field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 29.652s
┌ [2/3] 🚚  Fetching dependencies
│ info pruneDeps Excluding 13 dependencies. For more information use `--verbose`.
└ Completed in 3.7s
┌ [3/3] 🔗  Linking dependencies
└ Completed in 3.565s
info security We found `install` scripts which turbo skips for security reasons. For more
information see https://turbo.sh/install-scripts.
├─ @angular/cli@13.0.4
├─ core-js@3.19.0
└─ esbuild@0.13.12
info Some packages were automatically replaced with polyfills. For more information see
https://turbo.sh/polyfills.
└─ esbuild@0.13.12 => esbuild-wasm@0.13.8

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 37.576s
$ ng serve
⠙ Generating browser application bundles (phase: setup)...(node:6) UnhandledPromiseRejectionWarning: Error: The Angular Compiler requires TypeScript >=4.4.2 and <4.5.0 but 4.5.4 was found instead.
    at checkVersion (file:///home/projects/quhuvj--run/node_modules/@angular/compiler-cli/bundles/index.js:17524:11)
    at verifySupportedTypeScriptVersion (file:///home/projects/quhuvj--run/node_modules/@angular/compiler-cli/bundles/index.js:17528:3)
    at new NgtscProgram (file:///home/projects/quhuvj--run/node_modules/@angular/compiler-cli/bundles/index.js:17678:7)
    at AngularWebpackPlugin.updateAotProgram (/home/projects/quhuvj--run/node_modules/@ngtools/webpack/src/ivy/plugin.js:321:32)
    at eval (/home/projects/quhuvj--run/node_modules/@ngtools/webpack/src/ivy/plugin.js:198:24)
    at Hook.eval [as call] (eval at _0x53a6f5 (https://quhuvj--run.w.staticblitz.com/blitz.c1a2f33ebdb80ec1573b6337c828d176e80f0398.js:11:220541), <anonymous>:20:1)
    at Hook.CALL_DELEGATE [as _call] (/home/projects/quhuvj--run/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/projects/quhuvj--run/node_modules/webpack/lib/Compiler.js:1054:30)
    at eval (/home/projects/quhuvj--run/node_modules/webpack/lib/Compiler.js:1099:29)
    at eval (eval at _0x53a6f5 (https://quhuvj--run.w.staticblitz.com/blitz.c1a2f33ebdb80ec1573b6337c828d176e80f0398.js:11:220541), <anonymous>:31:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧ Generating browser application bundles (phase: setup)...

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

copie todo el codigo

### Expected behavior

que muestre la app

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82969853,
  "usedJSHeapSize": 78091973,
  "jsHeapSizeLimit": 4294705152
}
Hash = c1a2f33ebdb80ec1573b6337c828d176e80f0398
```

**Comment by jrvidal** [comment]
@DANILORE Thanks for the report. This seems to be an upstream issue, see #477 and #473
