### ISSUE TITLE
TypeScript Version Mismatch

### ISSUE THREAD

**Issue by atutcuog** [stackblitz/webcontainer-core#491]
### Describe the bug

Unable to generate browser application bundles (using the standard Angular Tutorial):

(node:6) UnhandledPromiseRejectionWarning: Error: The Angular Compiler requires TypeScript >=4.4.2 and <4.5.0 but 4.5.4 was found instead.
    at checkVersion (file:///home/projects/angular-8marnu/node_modules/@angular/compiler-cli/bundles/index.js:17524:11)
    at verifySupportedTypeScriptVersion (file:///home/projects/angular-8marnu/node_modules/@angular/compiler-cli/bundles/index.js:17528:3)
    at new NgtscProgram (file:///home/projects/angular-8marnu/node_modules/@angular/compiler-cli/bundles/index.js:17678:7)
    at AngularWebpackPlugin.updateAotProgram (/home/projects/angular-8marnu/node_modules/@ngtools/webpack/src/ivy/plugin.js:321:32)
    at eval (/home/projects/angular-8marnu/node_modules/@ngtools/webpack/src/ivy/plugin.js:198:24)
    at Hook.eval [as call] (eval at _0x493c66 (https://angular-8marnu.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:11:221380), <anonymous>:20:1)
    at Hook.CALL_DELEGATE [as _call] (/home/projects/angular-8marnu/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/projects/angular-8marnu/node_modules/webpack/lib/Compiler.js:1054:30)
    at eval (/home/projects/angular-8marnu/node_modules/webpack/lib/Compiler.js:1099:29)
    at eval (eval at _0x493c66 (https://angular-8marnu.w.staticblitz.com/blitz.a3339ebb87d0fe73c7995fe67420660e0dc95de2.js:11:221380), <anonymous>:31:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/app.component.ts

### Steps to reproduce

1. Go to https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html
2. Wait.
3. That's it, in the third step, you should encounter this error.

### Expected behavior

The tutorial Angular webapp opens up. 

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 Edg/96.0.1054.53
performance.memory = {
  "totalJSHeapSize": 86913043,
  "usedJSHeapSize": 80629635,
  "jsHeapSizeLimit": 4294705152
}
Hash = a3339ebb87d0fe73c7995fe67420660e0dc95de2
```

**Comment by jrvidal** [comment]
@atutcuog Thanks for the report, I suspect this is an upstream issue, see https://github.com/angular/angular/issues/44480 and https://github.com/stackblitz/webcontainer-core/issues/473. Please, do comment if that does not apply to your problem.
