### ISSUE TITLE
v8.getHeapSpaceStatistics crashes REPL

### ISSUE THREAD

**Issue by lucacasonato** [stackblitz/webcontainer-core#5]
**Describe the bug**

Node REPL crashes on `require("v8").getHeapSpaceStatistics()`.

**To Reproduce**

Open node REPL, enter `require("v8").getHeapSpaceStatistics()`. See crash:
```
Uncaught TypeError: j is not a function
    at Object.getHeapSpaceStatistics (https://node-6taf5d.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:625925)
    at eval (REPL10:1:15)
    at __global_eval__ (https://node-6taf5d.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:8:15949)
    at _0x18a892 (https://node-6taf5d.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:21075)
    at Script.runInThisContext (https://node-6taf5d.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:20268)
    at Script.runInThisContext (https://node-6taf5d.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:458038)
    at REPLServer.p (https://node-6taf5d.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:1092122)
    at bound (https://node-6taf5d.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:1322974)
    at REPLServer.runBound [as eval] (https://node-6taf5d.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:1324533)
    at REPLServer.<anonymous> (https://node-6taf5d.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:1098633)
```

**Expected behavior**

I get heap statistics.

**Desktop:**

Google Chrome | 90.0.4430.212&nbsp;(Official Build)&nbsp;(64-bit)
-- | --
Revision | e3cd97fc771b893b7fd1879196d1215b622c2bed-refs/branch-heads/4430@{#1429}
OS | Linux
JavaScript | V8&nbsp;9.0.257.29

**Comment by KwintenP** [comment]
Everything with WebContainer runs in the browser. This means we do not have access to the API's to provide you with the info to implement this method on our end. 

We should have a graceful fallback though if this package is used/imported. Adding this to our internal tracker.
