### ISSUE TITLE
BUG: crypto.createHMAC not supported

### ISSUE THREAD

**Issue by ridomin** [stackblitz/webcontainer-core#57]
---
name: crypto.createHMAC not supported
about: cant use packages using crypto
title: ''
labels: ''
assignees: ''

---

# crypto.createHMAC not supported

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-fpuh1p

**To Reproduce**
1. Create a node.js environment
2. Add the  code below to index.js
3. run  `node index.js`

```js
const crypto = require('crypto');
const mac = crypto.createHmac('sha256', 'aa')
console.log(mac)
```

**Expected behavior**
same output as nodejs

**Observed**

```text
/projects/node-fpuh1p
❯ node index.js 
TypeError: Cannot read property 'toLowerCase' of undefined
    at new e.exports (https://node-fpuh1p.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:1179499)
    at new Hmac (https://node-fpuh1p.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:924216)
    at Object.createHmac (https://node-fpuh1p.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:612717)
    at Object.eval (/projects/node-fpuh1p/index.js:4:20)
    at Object.function (https://node-fpuh1p.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19819)
    at Module._compile (https://node-fpuh1p.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187549)
    at Object.Module._extensions..js (https://node-fpuh1p.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187908)
    at Module.load (https://node-fpuh1p.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:185988)
    at Function.Module._load (https://node-fpuh1p.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:183564)
    at Function.executeUserEntryPoint [as runMain] (https://node-fpuh1p.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:794701)
```

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.62
performance.memory = {
  totalJSHeapSize: 97015979,
  usedJSHeapSize: 91484355,
  jsHeapSizeLimit: 4294705152
}

**Additional context**

**Comment by ridomin** [comment]
dupe of #31

**Comment by d3lm** [comment]
Hey there! Just wanted to get back here and tell you that this has been fixed. I created an example https://stackblitz.com/edit/node-hk3eau.
