### ISSUE TITLE
I am trying to follow the Angular Introduction with the Getting started project

### ISSUE THREAD

**Issue by iuliaAndreea07** [stackblitz/webcontainer-core#606]
### Describe the bug

Unable to create new component

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-drn9te-iihnis?file=tsconfig.json

### Steps to reproduce

1. Open new console
2. Type command: `ng generate component product-alerts`
3. An error is thrown:

>  An unhandled exception occurred: Cannot set property global of #<Object> which has only a getter
> See "/tmp/ng-0q2Uom/angular-errors.log" for further details.

Full error can be seen in the logs: 

```
❯ cat /tmp/ng-0q2Uom/angular-errors.log
[error] TypeError: Cannot set property global of #<Object> which has only a getter
    at Script.runInContext (https://angular-drn9te-iihnis.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:15:96455)
    at Script.runInContext (https://angular-drn9te-iihnis.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:418152)
    at Script.runInNewContext (https://angular-drn9te-iihnis.w.staticblitz.com/blitz.d64d45524a435df425e7813603b52872ecfbe08e.js:6:418252)
    at wrap (/home/projects/angular-drn9te-iihnis/node_modules/@angular/cli/models/schematic-engine-host.js:170:35)
    at SchematicEngineHost._resolveReferenceString (/home/projects/angular-drn9te-iihnis/node_modules/@angular/cli/models/schematic-engine-host.js:61:40)
    at SchematicEngineHost.createSchematicDescription (/home/projects/angular-drn9te-iihnis/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:181:34)
    at SchematicEngine.createSchematic (/home/projects/angular-drn9te-iihnis/node_modules/@angular-devkit/schematics/src/engine/engine.js:228:38)
    at CollectionImpl.createSchematic (/home/projects/angular-drn9te-iihnis/node_modules/@angular-devkit/schematics/src/engine/engine.js:80:29)
    at GenerateCommand.getSchematic (/home/projects/angular-drn9te-iihnis/node_modules/@angular/cli/models/schematic-command.js:150:27)
    at GenerateCommand.initialize (/home/projects/angular-drn9te-iihnis/node_modules/@angular/cli/models/schematic-command.js:63:36)
```

### Expected behavior

New folder with:
product-alerts.component.ts
product-alerts.component.html
product-alerts.component.css

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 119112405,
  "usedJSHeapSize": 113944717,
  "jsHeapSizeLimit": 4294705152
}
Hash = d64d45524a435df425e7813603b52872ecfbe08e
```

**Comment by jrvidal** [comment]
Duplicate of https://github.com/stackblitz/webcontainer-core/issues/604
