### ISSUE TITLE
es modules not working with jest

### ISSUE THREAD

**Issue by Pyrolistical** [stackblitz/webcontainer-core#614]
### Describe the bug

According to #6 es modules works, but it doesn't work with jest.

### Link to the blitz that caused the error

https://stackblitz.com/github/Pyrolistical/stackblitz-jest-modules

### Steps to reproduce

1. run `npm test`

fails with
```
❯ npm test
$ NODE_OPTIONS='--experimental-vm-modules --no-warnings' jest
 FAIL  ./index.spec.js
  ● Test suite failed to run

    SyntaxError: Cannot use import statement outside a module

      at Proxy.<anonymous> (https:/vbwipnxyp--github.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:8:24692)
      at __global_eval__ (https:/vbwipnxyp--github.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:8:24711)
      at _0x56e065 (https:/vbwipnxyp--github.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:15:102700)
      at Script.runInContext (https:/vbwipnxyp--github.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:15:102257)
      at Script.runInContext (https:/vbwipnxyp--github.w.staticblitz.com/blitz.a8f9013f6760f2c4e84edef607d361d3a32b8049.js:6:336277)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.2 s
Ran all test suites.
```

### Expected behavior

I rewrote everything to use commonjs it and it does work: https://stackblitz.com/github/Pyrolistical/stackblitz-jest-modules/tree/commonjs

```
❯ npm test
$ jest
 PASS  ./index.spec.js
  ✓ index is true (41 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.377 s
Ran all test suites.
```

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Operating system: macOS Big Sur 11.6.4
Node: 14.19.0
```

**Comment by d3lm** [comment]
Hey there 👋 

Just wanted to let you know that experimental vm modules have been implemented and the command you mentioned works for me now. I am going to close this one for now, and if you run into further issue feel free to open a new issue.

**Comment by Pyrolistical** [comment]
huzzah! confirmed, it works
```sh
❯ npm test
$ NODE_OPTIONS='--experimental-vm-modules --no-warnings' jest
 PASS  ./index.spec.js
  ✓ index is true (41 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.306 s
Ran all test suites.
```

**Comment by d3lm** [comment]
Glad it works @Pyrolistical 👏
