### ISSUE TITLE
Booting WebContainer is Blocked in Microsoft Edge

### ISSUE THREAD

**Issue by MarkSky** [stackblitz/webcontainer-core#621]
### Describe the bug

Booting WebContainer doesn't work on Microsoft Edge (99.0.1150.36 64bit).
I found some websites are blocked by Browse safer with Microsoft Edge:

- [*.]stackblitz.com
- [*.]staticblitz.com
- [*.]stackblitz.io
- [*.]webcontainer.io

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-kqtflp?file=package.json

### Steps to reproduce

1. Open editor
2. booting webcontainer is not work

### Expected behavior

Booting webcontainer should disply web page.

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Microsoft Edge
Full version  = 99.0.4844.51
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.36
performance.memory = {
  "totalJSHeapSize": 362641799,
  "usedJSHeapSize": 350316811,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5bca79c80956550a0ee18f24bf5b874e18bb8626
```

**Comment by jrvidal** [comment]
@MarkSky Thanks for the report. Yes, if your browser blocks third-party resources, WebContainer will not work. This is described in [our documentation](https://developer.stackblitz.com/docs/platform/third-party-blocker).

Did you get an error message in the side pane? Or did it just get stuck?

**Comment by MarkSky** [comment]
Yes, there is a message: "Failed to boot WebContainer".
![螢幕擷取畫面 2022-03-09 164752](https://user-images.githubusercontent.com/4032734/157405754-df66bfd5-7055-4c93-b321-f3a0433af00f.jpg)

And in DevTools:
```
16:46:32.561 iframe.5bca79c80956550a0ee18f24bf5b874e18bb8626.html:1 
        
       Error handling response: TypeError: Cannot read properties of undefined (reading 'isRedirected')
    at chrome-extension://ahkjpbeeocnddjkakilopmfdlnjdpcdm/snapshot/script.main.js:6518:35
16:46:32.561 iframe.5bca79c80956550a0ee18f24bf5b874e18bb8626.html:1 
        
       Unchecked runtime.lastError: The message port closed before a response was received.
16:46:32.602 _relay_:1 
        
       Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://vitejs-css-test.stackblitz.io/') with script ('https://vitejs-css-test.stackblitz.io/_sw_.js'): The user denied permission to use Service Worker.
16:46:32.763 _relay_:1 
        
       Error handling response: TypeError: Cannot read properties of undefined (reading 'isRedirected')
    at chrome-extension://ahkjpbeeocnddjkakilopmfdlnjdpcdm/snapshot/script.main.js:6518:35
16:46:32.763 _relay_:1 
        
       Unchecked runtime.lastError: The message port closed before a response was received.
16:46:32.851 client-02707286ce6d.js:2 
        
       TypeError: Cannot read properties of undefined (reading 'Memory')
    at _0x35e7a4 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:93264)
    at _0x291f27.initFileSystem (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:363269)
    at _0x2666c.init (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:396562)
    at _0x4305c3 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:127824)
  
  16:46:32.856 client-02707286ce6d.js:2 
        
       Something went wrong TypeError: Cannot read properties of undefined (reading 'Memory')
    at _0x35e7a4 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:93264)
    at _0x291f27.initFileSystem (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:363269)
    at _0x2666c.init (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:396562)
    at _0x4305c3 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:127824)
(匿名) @ client-02707286ce6d.js:2
16:46:32.862 webcontainer.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Memory')
    at _0x35e7a4 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:93264)
    at _0x291f27.initFileSystem (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:363269)
    at _0x2666c.init (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:396562)
    at _0x4305c3 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:127824)
16:46:32.862 webcontainer.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Memory')
    at _0x35e7a4 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:93264)
    at _0x291f27.initFileSystem (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:363269)
    at _0x2666c.init (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:396562)
    at _0x4305c3 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:127824)
16:46:32.862 webcontainer.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Memory')
    at _0x35e7a4 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:93264)
    at _0x291f27.initFileSystem (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:363269)
    at _0x2666c.init (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:396562)
    at _0x4305c3 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:127824)
16:46:32.862 webcontainer.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:6 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Memory')
    at _0x35e7a4 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:93264)
    at _0x291f27.initFileSystem (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:363269)
    at _0x2666c.init (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:15:396562)
    at _0x4305c3 (blitz.5bca79c80956550a0ee18f24bf5b874e18bb8626.js:8:127824)
16:46:32.906 client-02707286ce6d.js:2 Uncaught (in promise) ReferenceError: WebAssembly is not defined
    at t.loadWASM (client-02707286ce6d.js:2:1224431)
    at client-02707286ce6d.js:2:2138752
16:46:33.325 client-02707286ce6d.js:2 
        
       Uncaught (in promise) ReferenceError: WebAssembly is not defined
    at t.loadWASM (client-02707286ce6d.js:2:1224431)
    at client-02707286ce6d.js:2:2138752
16:46:33.365 client-02707286ce6d.js:2 
        
       Uncaught (in promise) ReferenceError: WebAssembly is not defined
    at t.loadWASM (client-02707286ce6d.js:2:1224431)
    at client-02707286ce6d.js:2:2138752
16:46:33.404 client-02707286ce6d.js:2 
        
       Uncaught (in promise) ReferenceError: WebAssembly is not defined
    at t.loadWASM (client-02707286ce6d.js:2:1224431)
    at client-02707286ce6d.js:2:2138752
16:46:33.834 client-02707286ce6d.js:2 
        
       Uncaught (in promise) ReferenceError: WebAssembly is not defined
    at t.loadWASM (client-02707286ce6d.js:2:1224431)
    at client-02707286ce6d.js:2:2138752
16:46:33.834 client-02707286ce6d.js:2 
        
       Uncaught (in promise) ReferenceError: WebAssembly is not defined
    at t.loadWASM (client-02707286ce6d.js:2:1224431)
    at client-02707286ce6d.js:2:2138752
```

**Comment by jrvidal** [comment]
Ah, this is interesting. This might be related to https://github.com/stackblitz/webcontainer-core/issues/576. For some reason, the `WebAssembly` global is not defined. I think this might also be related: https://github.com/microsoft/vscode/issues/137704. Could you try the instructions there?

**Comment by MarkSky** [comment]
Yes, after I add the websites to the enhanced security list, it work.
