### ISSUE TITLE
SvelteKit template - TODOs not working

### ISSUE THREAD

**Issue by msgeissler** [stackblitz/webcontainer-core#639]
### Describe the bug

Using the default SvelteKit template I am unable to create TODOs.

After entering a TODO text and hitting enter, it disappears (the form is being reset, that is ok) but nothing more happens.

Unless something else is buggy, I believe this is due to missing cookies.
`cookies` in `hooks.js`  is always empty, no request/response seems to be able to actually set the `userid`. The dev tools also show that no `userid` value is ever stored in any cookie. So with every request `hooks.js` will generate a new id and won't be able to get the previous TODOs.

### Link to the blitz that caused the error

https://stackblitz.com/edit/sveltejs-kit-template-default-mk6miu?file=src%2Fhooks.js&terminal=dev

### Steps to reproduce

1. Go to the linked blitz
2. Open TODOS
3. Focus the input field, enter text and hit enter

### Expected behavior

Created TODOs show up

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 99.0.4844.74
Major version = 99
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 185731489,
  "usedJSHeapSize": 177483153,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6495216afc69f31e3592b868d6f1407d8619435d
```

**Comment by jrvidal** [comment]
@msgeissler Thanks for the report.

> [ ] I have run the project in my local machine and I could not reproduce the issue.

I have run your project in Stackblitz and locally and in both cases I get:
```
Error: Parse failure: Unexpected token (1:4)
Contents of line 1: npm RUimport cookie from 'cookie';
    at ssrTransform (/home/projects/sveltejs-kit-template-default-mk6miu/node_modules/vite/dist/node/chunks/dep-9c153816.js:52135:15)
    at doTransform (/home/projects/sveltejs-kit-template-default-mk6miu/node_modules/vite/dist/node/chunks/dep-9c153816.js:53052:48)
```

This does not seem like a WebContainer issue.

**Comment by msgeissler** [comment]
Hi @jrvidal,

thanks for the feedback.
As a quick note: this is not really "my project" (which is also the reason I did not try it locally). It is the default svelte (/sveltekit) demo linked on the stackblitz main homepage and I just wanted to have quick look at how it worked and have no intention on actually running it locally and installing all the dependencies for it. Because it is the provided default demo I expected it "to just work".

Can you tell me where you saw that error message? For me the project is starting just fine in stackblitz.
Manually running `npm run build` on stackblitz also works fine.
It also seems weird that there should be any text `npm RU` in front of the cookie import. This is also not present in the `hooks.js` file in the project (which is where the cookie import happens).

**Comment by jrvidal** [comment]
> It also seems weird that there should be any text npm RU in front of the cookie import. This is also not present in the hooks.js file in the project (which is where the cookie import happens).

It is weird indeed, I noticed now that this extraneous text was there. We might have some other backend issue intermixed.

> It is the default svelte (/sveltekit) demo linked on the stackblitz main homepage

I see now what you mean, this does look like a bug on our side :pray:
