### ISSUE TITLE
Not able fetch  API endpoint request

### ISSUE THREAD

**Issue by anilkk** [stackblitz/webcontainer-core#642]
### Describe the bug

I have used axios to gte the data from Lokalise API end points and  I get the 
`ERROR ----> Error: socket hang up
    at connResetException (https://nextjs-ctyzc2.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:6855)
    at TLSSocket.socketOnEnd (https://nextjs-ctyzc2.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:910485)
    at TLSSocket.EventEmitter.emit (https://nextjs-ctyzc2.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:131338)
    at endReadableNT (https://nextjs-ctyzc2.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:6:540012)
    at Object.callback (https://nextjs-ctyzc2.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:15:188119)
    at https://nextjs-ctyzc2.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:15:167184
    at _0x16827a (https://nextjs-ctyzc2.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:15:167218)
    at MessagePort._0x231308.port1.<computed> (https://nextjs-ctyzc2.w.staticblitz.com/blitz.6495216afc69f31e3592b868d6f1407d8619435d.js:15:167376) {
  code: 'ECONNRESET',
  config: {
`

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-ctyzc2?file=lokalise.js

### Steps to reproduce

1. Run this Stackblitz 
2. Create a Lokalise API token - https://docs.lokalise.com/en/articles/1929556-api-tokens
3. Create a `.env` file in the root and add `LOKALISE_API_KEY`variable.
4. run `node lokalise.js`

### Expected behavior

Fetch data without issue.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="906" alt="image" src="https://user-images.githubusercontent.com/1124415/159359802-9e899cd3-2fe1-4403-a26b-7ba4622218ca.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 99.0.4844.74

**Comment by jrvidal** [comment]
@anilkk Thanks for the report. This is most likely due to a CORS error, which we cannot work around given the security model of the browser.

**Comment by jrvidal** [comment]
No problem :+1:  I'm going to close this for the time being. We do keep the CORS issue in our minds and StackBlitz might change in the future to unblock more use cases, but there is nothing immediately actionable.
