### ISSUE TITLE
`writeAsciiString` is not a function

### ISSUE THREAD

**Issue by GregBrimble** [stackblitz/webcontainer-core#672]
### Describe the bug

```
Cause: TypeError: n.writeAsciiString is not a function
    at https://node-6zzdhd.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:783395
    at writeGeneric (https://node-6zzdhd.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:783579)
    at TLSSocket.Socket._writeGeneric (https://node-6zzdhd.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:237560)
    at TLSSocket.Socket._write (https://node-6zzdhd.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:237718)
    at https://node-6zzdhd.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:1012355
    at _write (https://node-6zzdhd.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:1012416)
    at TLSSocket.Writable.write (https://node-6zzdhd.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:1016073)
    at AsyncWriter.end (/home/projects/node-6zzdhd/node_modules/undici/lib/client.js:1790:16)
    at writeIterable (/home/projects/node-6zzdhd/node_modules/undici/lib/client.js:1695:12)
```

Doesn't seem to actually impact the project running, but this error appears in WebContainers, but not when running locally.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-xhsc9s

### Steps to reproduce

1. Load the WebContainer.
2. Let the dependencies install.
3. Start the command `npx wrangler dev index.js --local`.

### Expected behavior

This error shouldn't appear when trying to run the `wrangler` local dev server in WebContainers.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 100.0.4896.88

### Additional context

wrangler2 only just today became possible to run in a WebContainer with the release of https://github.com/stackblitz/webcontainer-core/issues/661.

I work at Cloudflare and am very happy to work with you to fix this problem if there's anything we can do to help.

**Comment by EricSimons** [comment]
Hey Greg- thanks so much for testing this, would love your help. We’re actually in an email thread with Sunil, Rita and Igor working on wrangler2/webcontainer. I just asked if they can add you to it, or if you share your email with me (either here or eric@stackblitz.com) I can loop you in!

**Comment by GregBrimble** [comment]
Ah, fantastic! Yeah, I'm gbrimble@. Please do loop me in!

**Comment by blittle** [comment]
I'm seeing this consistently when using `fetch` from `undici`. See this simple example:

https://stackblitz.com/edit/node-et6u3f?file=index.js

**Comment by d3lm** [comment]
This is going to be fixed in an upcoming release 👍

**Comment by d3lm** [comment]
Quick update: This is fixed now. Thanks for closing this issue @SamVerschueren.
