### ISSUE TITLE
Object is not defined (from chalk)

### ISSUE THREAD

**Issue by NullVoxPopuli** [stackblitz/webcontainer-core#673]
### Describe the bug

```
ReferenceError: Object is not defined
    at Function.build (/home/projects/github-k7htnb/node_modules/console-ui/node_modules/chalk/index.js:129:2)
    at Function.get (/home/projects/github-k7htnb/node_modules/console-ui/node_modules/chalk/index.js:61:17)
    at writeError (/home/projects/github-k7htnb/node_modules/console-ui/lib/write-error.js:101:24)
    at UI.writeError (/home/projects/github-k7htnb/node_modules/console-ui/lib/index.js:167:20)
    at CLI.logError (/home/projects/github-k7htnb/node_modules/ember-cli/lib/cli/cli.js:318:13)
    at CLI.run (/home/projects/github-k7htnb/node_modules/ember-cli/lib/cli/cli.js:253:12)
    at async module.exports (/home/projects/github-k7htnb/node_modules/ember-cli/lib/cli/index.js:145:12)
```
    

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-k7htnb

### Steps to reproduce

- visit blitz
- default commands run `ember s`, which uses the popular library, `chalk`

### Expected behavior

dev server boots

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Related to: https://github.com/stackblitz/webcontainer-core/issues/354

**Comment by d3lm** [comment]
Hey there 👋 

Thanks for the issue report. I was looking a bit into it and what I have noticed is that ember uses the [`esm`](https://www.npmjs.com/package/esm) package. Is there any reason you're using this instead of native esm in Node.js?

The error is coming from that package. That said, it should work even with this package but I was just curious why it's using the esm shim.

**Comment by NullVoxPopuli** [comment]
> Is there any reason you're using this instead of native esm in Node.js?

same reason anyone would ;) -- tons and tons of ecosystem code is still in cjs. The migration to ESM is a herculean effort in most mature projects -- and cjs is forbidden from requiring ESM, but ESM can import cjs.

**Comment by NullVoxPopuli** [comment]
In firefox I got this error just now:
```
[get stackTraceLimit@https://github-k7htnb.w-corp.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:291482
getErrorWithoutStack@https://github-k7htnb.w-corp.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:1073931
generateUnhandledRejectionError@https://github-k7htnb.w-corp.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:1074165
processPromiseRejections@https://github-k7htnb.w-corp.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:1075173
processTicksAndRejections@https://github-k7htnb.w-corp.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:797086
_0x3766af@https://github-k7htnb.w-corp.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:8:224285
]
```
