### ISSUE TITLE
Unknown cipher error when calling setPreviewData with Next.js framework

### ISSUE THREAD

**Issue by adamconn** [stackblitz/webcontainer-core#678]
### Describe the bug

Making a call to `res.setPreviewData` throws an error *Error: Unknown cipher*.

The following is the stack trace from my browser's console:

```
Uncaught     at _0x3aa4dc.initiv (https://nextjs-yufjmz.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:15:316267)
    at Cipheriv.createCipherBase (https://nextjs-yufjmz.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:1131371)
    at Cipheriv.createCipherWithIV (https://nextjs-yufjmz.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:1131630)
    at new Cipheriv (https://nextjs-yufjmz.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:1131970)
    at Object.createCipheriv (https://nextjs-yufjmz.w.staticblitz.com/blitz.49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf.js:6:807867)
    at Object.encryptWithSecret (file:///home/projects/nextjs-yufjmz/node_modules/next/dist/server/crypto-utils.js:23:36)
    at setPreviewData (file:///home/projects/nextjs-yufjmz/node_modules/next/dist/server/api-utils/node.js:323:33)
    at ServerResponse.apiRes.setPreviewData (file:///home/projects/nextjs-yufjmz/node_modules/next/dist/server/api-utils/node.js:167:13)
    at handler (webpack-internal:///(api)/./pages/api/preview.js:6:7)
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-yufjmz?file=pages%2Fapi%2Fpreview.js

### Steps to reproduce

1. Create a blitz using the Next.js framework.
2. Add a file `pages/api/preview.js`:
    ```
    export default function handler(req, res) {
      res.setPreviewData({});
      res.end('Preview mode enabled');
    }
    ```
3. In your browser, open the url `/api/preview`

### Expected behavior

Response is `Preview mode enabled`

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 100.0.4896.88
Major version = 100
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 66611753,
  "usedJSHeapSize": 61826369,
  "jsHeapSizeLimit": 4294705152
}
Hash = 49c6d2ee58ce7c1528881cc6d46ebf056b3b42bf
```

**Comment by adamconn** [comment]
The following code further isolates the issue. The crypto module returns `aes-256-gcm` in the list, but it returns undefined when you try to get info on it:

```
const crypto = require('crypto');

if (crypto.getCiphers().find((c) => c == 'aes-256-gcm')) {
  const info = crypto.getCipherInfo('aes-256-gcm');
  console.log(info);
}
```

**Comment by d3lm** [comment]
Hey there, thanks for reporting this issue. Right now `aes-256-gcm` is unsupported. We'll add this to our internal issue tracker.
