### ISSUE TITLE
Chrome chrashes and doesn't load other tabs

### ISSUE THREAD

**Issue by NullVoxPopuli** [stackblitz/webcontainer-core#692]
### Describe the bug

When I visit https://stackblitz.com/edit/github-8qeupk?file=package.json,
the terminal says it's `Fetching dependencies` but gets stuck. Maybe infinite loop?

It doesn't seem I'm allowed to visit the same blitz in a new tab either

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-8qeupk?file=package.json

### Steps to reproduce

visit: https://stackblitz.com/edit/github-8qeupk?file=package.json
observer frozen browser

### Expected behavior

webapp's devserver boots

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Ubuntu 
- Browser: Chrome
- Version: 101.0.4951.41

**Comment by d3lm** [comment]
Hey there! If I open your project it works fine for me and I can't seem to reproduce it. Any errors in the console?

**Comment by NullVoxPopuli** [comment]
I'm not using the same setup atm, but on Chrome canary I got _an_ error.
```
ReferenceError: Object is not defined
    at Function.build (/home/projects/github-8qeupk/node_modules/console-ui/node_modules/chalk/index.js:129:2)
    at Function.get (/home/projects/github-8qeupk/node_modules/console-ui/node_modules/chalk/index.js:61:17)
    at writeError (/home/projects/github-8qeupk/node_modules/console-ui/lib/write-error.js:101:24)
    ```
    
Why wouldn't Object be defined for chalk?

**Comment by d3lm** [comment]
It's not `chalk`, and that error is basically a duplicate of #673 which is some weird issue with the vm module and the `esm` package. I have looked briefly into it and saw that for some reason the global was modified which results in that strange error you mentioned. We have to take a closer look and see how we can resolve this issue.
