### ISSUE TITLE
file exported via pattern in export map cannot be found by vite

### ISSUE THREAD

**Issue by dominikg** [stackblitz/webcontainer-core#693]
### Describe the bug

vite-plugin-svelte contains a new overlay user-interface that is injected into the dev page and loaded from a virtual module id that resolves to a packaged file that is exported via pattern export `exports:{"./src/ui/*":"./src/ui/*"}` in [package.json](
 https://github.com/sveltejs/vite-plugin-svelte/blob/61ae87b34af858c03e9adeea9cbeecabcb536b10/packages/vite-plugin-svelte/package.json#L23)

unfortunately it fails to load on stackblitz with this error being shown in the dev page:

```
Cannot find module '@sveltejs/vite-plugin-svelte/src/ui/inspector/load-inspector.ts'
Require stack:
- /home/projects/vitejs-vite-19mtqy
    at Function.Module._resolveFilename (https://vitejs-vite-19mtqy.w.staticblitz.com/blitz.f2b430413f5697306be55fc5c653053509a24007.js:6:217231)
    at Function.resolve (https://vitejs-vite-19mtqy.w.staticblitz.com/blitz.f2b430413f5697306be55fc5c653053509a24007.js:6:415199)
    at Context.resolveId (file:///home/projects/vitejs-vite-19mtqy/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1571:35)
    at Object.resolveId (/home/projects/vitejs-vite-19mtqy/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:38898:55)
    at async ModuleGraph.resolveUrl (/home/projects/vitejs-vite-19mtqy/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:57481:26)
    at async ModuleGraph.getModuleByUrl (/home/projects/vitejs-vite-19mtqy/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:57361:23)
    at async doTransform (/home/projects/vitejs-vite-19mtqy/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:55838:20
```

### Link to the blitz that caused the error

 https://stackblitz.com/edit/vitejs-vite-19mtqy?file=svelte.config.js&terminal=dev

### Steps to reproduce

just open the blitz and wait for the error overlay to show up in the iframe

### Expected behavior

loads the file without error and subsequently also Inspector.svelte that is imported by it.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: linux
- Browser: chrome
- Version: 101

### Additional context

docs for vite-plugin-svelte inspector: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#inspector
code: https://github.com/sveltejs/vite-plugin-svelte/tree/main/packages/vite-plugin-svelte/src/ui/inspector

**Comment by dominikg** [comment]
was able to reproduce this locally when using npm instead of pnpm.

**Comment by d3lm** [comment]
Thanks for verifying 🙏
