### ISSUE TITLE
Importing https://stackblitz.com/github/tomayac/local-reverse-geocoder doesn't work

### ISSUE THREAD

**Issue by tomayac** [stackblitz/webcontainer-core#698]
### Describe the bug

```
~/projects/yqnibxxbv.github
❯ npm install && npm start
┌ [1/4] 🔍  Resolving dependencies
└ Completed in 0.073s
┌ [2/4] 🚚  Fetching dependencies
└ Completed in 3.229s
┌ [3/4] 🔗  Linking dependencies
└ Completed in 0.126s

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 3.461s
$ node --max-old-space-size=4096 app.js
Local reverse geocoder listening on port 3000
Initializing Geocoder…
(This may take a long time and will download ~300MB worth of data.)
TypeError: Failed to fetch
    at _0x1c7790._fetch (https://yqnibxxbv--github.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:15:381987)
    at _0x1c7790.performHTTPCall (https://yqnibxxbv--github.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:15:381693)
    at _0x1c7790._write (https://yqnibxxbv--github.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:15:375751)
    at _0x1c7790.writeLatin1String (https://yqnibxxbv--github.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:15:367851)
    at https://yqnibxxbv--github.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:783299
    at writeGeneric (https://yqnibxxbv--github.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:783580)
    at Socket._writeGeneric (https://yqnibxxbv--github.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:237560)
    at Socket._write (https://yqnibxxbv--github.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:237718)
    at doWrite (https://yqnibxxbv--github.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:1012568)
    at clearBuffer (https://yqnibxxbv--github.w.staticblitz.com/blitz.5428dc6786c976e0e08fde1105586a722833c4ef.js:6:1014312)
```

### Link to the blitz that caused the error

https://stackblitz.com/github/tomayac/local-reverse-geocoder/?file=README.md

### Steps to reproduce

1. Go to https://stackblitz.com/github/tomayac/local-reverse-geocoder

### Expected behavior

`npm i` succeeds

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="780" alt="Screen Shot 2022-05-17 at 10 46 23" src="https://user-images.githubusercontent.com/145676/168770125-bff170df-e3d4-42d6-a367-213dbad4073d.png">

### Platform

```
Browser name  = Chrome
Full version  = 101.0.4951.64
Major version = 101
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 99636617,
  "usedJSHeapSize": 84035369,
  "jsHeapSizeLimit": 4294705152
}
Hash = 5428dc6786c976e0e08fde1105586a722833c4ef
```

**Comment by SamVerschueren** [comment]
Hey @tomayac 👋 . Thanks for reporting.

I quickly looked into it and found a couple of things.
1. The main reason it seems to fail initially is due to mixed content. The zip files are downloaded over `http` and Chrome blocks that. Changing the `GEONAMES_URL` to `https` brings us to the next issue. ![image](https://user-images.githubusercontent.com/1913805/168772125-bb027fa1-8b46-4a89-be7f-ec0f2d77a437.png)
2. The endpoints do not have CORS setup, which means we can't send a request to them because they get blocked by Chrome. Installing an `Allow CORS` extension in Chrome circumvents this but still doesn't work. ![image](https://user-images.githubusercontent.com/1913805/168772551-e5e9bd37-f2a1-4c96-8d6b-749dc759c34c.png)
3. After enabling CORS and https, the size of the files are an issue. Unzipped, the `allCountries.txt` contains 1.6GB of data, the `alternateNames.txt` contains 608MB of data. And then there's some other smaller files as well. This amount of data is currently an issue and it fails to process that.

**Comment by SamVerschueren** [comment]
The giant file sizes is something we rarely run into. As far as I know, this is the first time I personally saw this (which doesn't mean other users might have ran into it as well).

There's a plan to support projects with big files which exceed the memory limits. But I can't give an estimate on this unfortunately.

**Comment by tomayac** [comment]
The [Kiwix PWA](https://github.com/kiwix/kiwix-js-windows) deals with this by letting the user download the huge files locally, and then references them via the File System Access API. Not concretely for my use case, just in general as a pattern maybe worthwhile to explore. I'm closing the Issue for now, but will of course be happy to learn if there are updates in the future when it comes to massive local files. Thanks for taking the time to investigate the problem `<3`.
