### ISSUE TITLE
Cannot use jest on node env

### ISSUE THREAD

**Issue by byeze** [stackblitz/webcontainer-core#700]
### Describe the bug

When I tried to run a sample test on my code (a simple 2+2), the console showed the following error:

```
 FAIL  src/tests/rules.test.js
  ● Test suite failed to run

    TypeError: Cannot redefine property: e
        at _0x29f4ba.defineProperty (<anonymous>)

      at Object.defineProperty (https:/node-7bbdiz.w.staticblitz.com/blitz.670e941965b7233a68cb924e1ca43e6a0f35bf71.js:15:114067)
          at _0x29f4ba.defineProperty (<anonymous>)
      at Object.get (https:/node-7bbdiz.w.staticblitz.com/blitz.670e941965b7233a68cb924e1ca43e6a0f35bf71.js:15:113532)
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.203 s
``` 

I'm using Typescript and Ts-jest for testing my code, the thing is that the error constantly appears, you can make the most simple test without dependencies, with, and change the code to make it super simple, but the error is the same.

**Sample test 1:**
```
import { sampleRules } from './../rules';
import { findMatch } from './../matcher';

test('should select Mobbex with Galicia partner', async () => {
  const match = await findMatch(sampleRules, {
    brand: 'MASTERCARD',
  });

  expect(match.id).toEqual('mobbex');
});
```

**Sample test 2:**

```
test('simple 2+2', async () => {
  expect(2+2).toEqual(4);
});
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-7bbdiz?file=src%2Frules.ts,src%2Findex.ts,src%2Ftests%2Frules.test.ts

### Steps to reproduce

1. Install dependencies
2. Run `npm run test`
3. View the terminal

### Expected behavior

Run the test without failing on the execution.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="950" alt="image" src="https://user-images.githubusercontent.com/7424138/169903680-456b42d9-7968-441c-8420-c59459603230.png">

### Platform

```
Browser name  = Chrome
Full version  = 101.0.4951.64
Major version = 101
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 158347523,
  "usedJSHeapSize": 153725567,
  "jsHeapSizeLimit": 4294705152
}
Hash = 670e941965b7233a68cb924e1ca43e6a0f35bf71
```

**Comment by jrvidal** [comment]
:wave: Thanks for the report. I can't reproduce on my end, I suspect that we might have fixed in the meantime (:smile: ). Is this still an issue for you?
