### ISSUE TITLE
Imported Github project using NX does not start up in Europe

### ISSUE THREAD

**Issue by TapaiBalazs** [stackblitz/webcontainer-core#735]
### Describe the bug

Our open source project is built with NX, and we demo it using Stackblitz. We've been using this for several months and we did not have any issues with it, but recently an error started happening for our developers located in Europe. The strangest thing is that our developers in Africa can open the project in Stackblitz and it starts up without errors.

The project will not start up in Europe, because of the following error:

```
Error: The Daemon Server is not running
Messages from the log:



More information: /home/projects/qgniylalb.github/node_modules/.cache/nx/d/daemon.log
    at daemonProcessException (/home/projects/qgniylalb.github/node_modules/nx/src/daemon/client/client.js:66:16)
    at Socket.eval (/home/projects/qgniylalb.github/node_modules/nx/src/daemon/client/client.js:148:29)
    at EventEmitter.emit (https://qgniylalb--github.w.staticblitz.com/blitz.8628379add68b16c6c7b3320a61a65ef38aa83fd.js:6:155573)
    at emitErrorNT (https://qgniylalb--github.w.staticblitz.com/blitz.8628379add68b16c6c7b3320a61a65ef38aa83fd.js:6:367810)
    at emitErrorCloseNT (https://qgniylalb--github.w.staticblitz.com/blitz.8628379add68b16c6c7b3320a61a65ef38aa83fd.js:6:367457)
    at _0x2b9b99 (https://qgniylalb--github.w.staticblitz.com/blitz.8628379add68b16c6c7b3320a61a65ef38aa83fd.js:15:130586)
    at https://qgniylalb--github.w.staticblitz.com/blitz.8628379add68b16c6c7b3320a61a65ef38aa83fd.js:15:130343
```

First I started to investigate this error based on NX issues reported, but on local machines it works for everybody. Then I noticed the pattern that my colleagues in Africa can open the project without error, and my colleagues in Europe can't, that's why I report this here.

### Link to the blitz that caused the error

https://stackblitz.com/github/thisdot/open-source?file=README.md&preset=node

### Steps to reproduce

1. Open the link
2. Wait for npm install to finish and the start command to run

### Expected behavior

The demo application should start up without errors. (In Europe)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

Screenshot of what happens to me (based in Europe)

![Screenshot 2022-06-30 at 10 04 04](https://user-images.githubusercontent.com/13385210/176625760-54cdfcf9-3c5b-45e0-8b74-431f90f79c74.png)

Screenshot of what happens to my colleague (based in Africa):

<img width="1440" alt="Screenshot 2022-06-30 at 08 56 35" src="https://user-images.githubusercontent.com/13385210/176625934-ae3097a9-4851-43f5-9c00-cec188e669cb.png">

### Platform

```
Browser name  = Chrome
Full version  = 103.0.0.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108766020,
  "usedJSHeapSize": 105397156,
  "jsHeapSizeLimit": 4294705152
}
Hash = 8628379add68b16c6c7b3320a61a65ef38aa83fd
```

### Additional context

My colleagues based in the US are not awake yet, so I cannot ask them to check, but this might be a regional issue somehow.

I believe the only difference is that in Africa the NX daemon is running, but in Europe it does not start up somehow.
Could there be possible restrictions that would prevent a webcontainer running something in the background? We recently updated to NX v14, and I can confirm that with the previous version it did work for me, although it was weeks ago when I checked it.

**Comment by TapaiBalazs** [comment]
Update:

A few days later today (july 5) it started up for me in Europe, maybe this was a temporary thing? 🤔

**Comment by TapaiBalazs** [comment]
Update:
No, today (july 6) I face the same issue again

**Comment by Zelig880** [comment]
Same here from UK on July 6th. The app does not work and the error is the same: 
![image](https://user-images.githubusercontent.com/9040770/177493949-bf30efcd-9346-4736-8339-1d56336886cb.png)
