### ISSUE TITLE
Don't work with umi framework

### ISSUE THREAD

**Issue by sorrycc** [stackblitz/webcontainer-core#742]
### Describe the bug

Don't work with [umi](https://umijs.org/) framework.

### Link to the blitz that caused the error

https://stackblitz.com/github/umijs/faq-examples/tree/master/examples/history

### Steps to reproduce

1. Open https://stackblitz.com/github/umijs/faq-examples/tree/master/examples/history ant wait

```
$ umi dev
info  - Umi v4.0.0-canary.20220707.1
ready - App listening at http://localhost:8000
event - [Webpack] Compiled in 652 ms (507 modules)
info  - [MFSU] buildDeps since cacheDependency has changed
wait  - [Webpack] Compiling...
event - [Webpack] Compiled in 48 ms (495 modules)
TypeError: Failed to execute 'decode' on 'TextDecoder': The provided ArrayBufferView value must not be shared.
    at Buffer._0x35712a [as utf8Slice] (https://xorilzbab--github.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:8:202869)
    at Object.slice (https://xorilzbab--github.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:76849)
    at Buffer.toString (https://xorilzbab--github.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:80753)
    at run (/home/projects/xorilzbab.github/node_modules/thread-stream/lib/worker.js:117:24)
    at Timeout.eval [as _onTimeout] (/home/projects/xorilzbab.github/node_modules/thread-stream/lib/wait.js:51:11)
    at listOnTimeout (https://xorilzbab--github.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:306540)
    at processTimers (https://xorilzbab--github.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:307363)
    at https://xorilzbab--github.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:15:249693
    at https://xorilzbab--github.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:15:249995
```

### Expected behavior

Don't throw error.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 103.0.0.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79404912,
  "usedJSHeapSize": 73532108,
  "jsHeapSizeLimit": 4294705152
}
Hash = bff91798029e1af88e01551d056a592b2882b9ac
```

**Comment by sorrycc** [comment]
Resolved.
