### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by wwyynnee** [stackblitz/webcontainer-core#744]
I switched from another hosting to yours, so I'm still a beginner. I have an error in the logs at startup (**npm start**), what should I do? Help to start node.js project is a Discord bot.
```
TypeError: Failed to fetch
    at _0x425d0a._fetch (https://wills.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:15:406182)
    at _0x425d0a.performHTTPCall (https://wills.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:15:405754)
    at _0x425d0a._write (https://wills.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:15:399835)
    at _0x425d0a.writeLatin1String (https://wills.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:15:390491)
    at _0xba2ea3.writeLatin1String (https://wills.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:15:210978)
    at https://wills.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:783438
    at writeGeneric (https://wills.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:783719)
    at Socket._writeGeneric (https://wills.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:237637)
    at Socket._write (https://wills.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:237795)
    at doWrite (https://wills.w.staticblitz.com/blitz.bff91798029e1af88e01551d056a592b2882b9ac.js:6:1012713)
```

- [Github project](https://github.com/wwyynnee/wills)
- [Stackblitz](https://stackblitz.com/edit/wills)

**Comment by jrvidal** [comment]
:wave: Thanks for the report. I can't access the project you linked above. Could you provide a link to an accessible project to reproduce the issue?

**Comment by jrvidal** [comment]
:wave: We're closing this due to inactivity. Please, feel free to open a new one if you're still encountering any errors.
