### ISSUE TITLE
Poor syntax errors

### ISSUE THREAD

**Issue by MarsOrBust24** [stackblitz/webcontainer-core#776]
### Describe the bug

Is there any way to make StackBlitz WebContainers give out better node errors? I'm not even getting a line number of during syntax errors

Node running bare metal will give out a MUCH better error:
```
// temp.js, bad code on line 11
const myMap = new Map(['absent', 0])
```

```
$ node temp.js
TypeError: Iterator value absent is not an entry object
    at new Map (<anonymous>)
    at file:///home/me/project/temp.js:11:16
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    ...
```

Meanwhile StackBlitz says this:

```
❯ node temp.js
Error: Iterator value absent is not an entry object
    at async ESMLoader.import (https://vc1gdd.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:1209040)
    at async i.loadESM (https://vc1gdd.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:246622)
    at async handleMainPromise (https://vc1gdd.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:989049)
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/nodemon-75h3ws?file=index.js,README.md

### Steps to reproduce

Make a syntax error.

### Expected behavior

Syntax errors should come with line numbers.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS:  All
- Browser: All
- Version: Latest

### Additional context

I was working on long files ~1000 lines... finding where I made a mistake was far more tedious in SB than it would have been on bare metal

**Comment by jrvidal** [comment]
:wave: Thanks for the report. This is an unexpected consequence of the transformations we need to perform to run ES modules. You'll notice that, without `"type": "module"` in your `package.json`, the stack traces are a bit more useful/clear.

Anyway, we're tracking this issue internally now, though I can't offer a concrete timeline. Thanks again!
