### ISSUE TITLE
BUG: ERR!: Failed to resolve dependencies

### ISSUE THREAD

**Issue by dazjean** [stackblitz/webcontainer-core#78]
---
name: Bug report
about:ERR!: Failed to resolve dependencies
title: 'ERR!: Failed to resolve dependencies'
labels: ''
assignees: ''

---

**Describe the bug**
 when init my propject yarn or npm  will get error `ERR!: Failed to resolve dependencies`.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/srejs-example-umajs?file=README.md

**To Reproduce**

**Expected behavior**

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 73155432,
  usedJSHeapSize: 66478128,
  jsHeapSizeLimit: 4294705152
}

**Additional context**
**Dependencies**
```json
{
  "name": "app",
  "version": "0.0.2",
  "description": "umajs-react-ssr",
  "author": "dazjean",
  "license": "ISC",
  "directories": {
    "lib": "lib",
    "test": "__tests__"
  },
  "files": [
    "lib",
    "index.d.ts"
  ],
  "publishConfig": {
    "registry": "http://registry.npmjs.org"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Umajs/Uma.git"
  },
  "scripts": {
    "fix:src": "npx eslint src --fix --ext .ts",
    "fix:web": "npx eslint web --fix --ext .tsx",
    "start": "ts-node-dev --respawn src/app.ts",
    "build": "tsc && srejs build",
    "fix": "npm run fix:src && npm run fix:web",
    "postinstall": "npm run fix && npm run build",
    "preprod": "npm run build",
    "prod": "node app/app.js --production"
  },
  "dependencies": {
    "@umajs/core": "^1.2.1",
    "@umajs/plugin-logger": "^0.1.1",
    "@umajs/plugin-react-ssr": "^1.0.3",
    "@umajs/plugin-static": "^1.2.0",
    "@umajs/plugin-views": "^2.0.1-alpha.0",
    "@umajs/router": "^1.2.2",
    "koa": "^2.11.0",
    "nunjucks": "^3.2.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0"
  },
  "devDependencies": {
    "@types/koa": "^2.0.48",
    "@types/react-router-dom": "^5.1.7",
    "@typescript-eslint/eslint-plugin": "^4.22.1",
    "@typescript-eslint/parser": "^4.22.1",
    "eslint": "^7.26.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.23.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.3.0",
    "ts-node": "^8.2.0",
    "ts-node-dev": "^1.0.0-pre.32",
    "typescript": "^3.2.2"
  }
}

```

**Terminal Log**
```shell
❯ npm install
┌ [1/3] 🔍  Resolving dependencies
└ 𐄂 Failed
ERR!: Failed to resolve dependencies

error Command failed with exit code 1
```

**Comment by dazjean** [comment]
**chrome js console**

```
[@blitz/registry] [INFO] Successfully initialized
5[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See <URL> for more details.
constants.js:66 [Contextify] [WARNING] running source code in new context
(anonymous) @ constants.js:66
_0x18a892 @ constants.js:66
runInContext @ constants.js:66
runInContext @ vm.js:143
runInNewContext @ vm.js:148
runInNewContext @ vm.js:303
(anonymous) @ repl.js:148
a0_0x310c @ blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6
_0x3ef789 @ constants.js:66
_0x1cd7f8 @ constants.js:66
(anonymous) @ constants.js:66
compileForInternalLoader @ loaders.js:283
compileForPublicLoader @ loaders.js:225
loadNativeModule @ helpers.js:35
Module._load @ loader.js:740
Module.require @ loader.js:952
i @ helpers.js:88
_0x1e5cfd @ constants.js:66
eval @ /bin/jsh:6
r @ /bin/jsh:6
eval @ /bin/jsh:6
r @ /bin/jsh:6
eval @ /bin/jsh:6
r @ /bin/jsh:6
eval @ /bin/jsh:6
Promise.then (async)
eval @ /bin/jsh:6
eval @ /bin/jsh:6
r @ /bin/jsh:6
eval @ /bin/jsh:6
eval @ /bin/jsh:6
eval @ /bin/jsh:6
eval @ /bin/jsh:6
function @ constants.js:66
Module._compile @ loader.js:1063
Module._extensions..js @ loader.js:1092
Module.load @ loader.js:928
Module._load @ loader.js:769
executeUserEntryPoint @ run_main.js:72
a0_0x310c @ run_main_module.js:17
_0x3ef789 @ constants.js:66
_0x1cd7f8 @ constants.js:66
_0x5e3b6e @ constants.js:66
run @ constants.js:66
async function (async)
run @ constants.js:66
_0x293e01 @ constants.js:66
ext-83882c2429dcfe052444b.js:2 WebSocket connection to 'wss://s-usc1c-nss-227.firebaseio.com/.ws?v=5&ns=stackblitz' failed: 
t.open @ ext-83882c2429dcfe052444b.js:2
(anonymous) @ ext-83882c2429dcfe052444b.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
s-usc1c-nss-227.firebaseio.com/.lp?dframe=t&id=973576&pw=Bdjh48JN9D&ns=stackblitz:5 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
EnvSendPing @ s-usc1c-nss-227.firebaseio.com/.lp?dframe=t&id=973576&pw=Bdjh48JN9D&ns=stackblitz:5
EnvDisconnect @ s-usc1c-nss-227.firebaseio.com/.lp?dframe=t&id=973576&pw=Bdjh48JN9D&ns=stackblitz:10
gitworker-fd631e3ffbc6f2b268f6b.js:2 error TypeError: network error
gitworker-fd631e3ffbc6f2b268f6b.js:2 TypeError: Cannot read property 'length' of undefined
    at l.push (gitworker-fd631e3ffbc6f2b268f6b.js:2)
    at gitworker-fd631e3ffbc6f2b268f6b.js:2
    at c (gitworker-fd631e3ffbc6f2b268f6b.js:2)
    at Generator._invoke (gitworker-fd631e3ffbc6f2b268f6b.js:2)
    at Generator.forEach.e.<computed> [as next] (gitworker-fd631e3ffbc6f2b268f6b.js:2)
    at C (gitworker-fd631e3ffbc6f2b268f6b.js:2)
    at o (gitworker-fd631e3ffbc6f2b268f6b.js:2)
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
c @ gitworker-fd631e3ffbc6f2b268f6b.js:2
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
forEach.e.<computed> @ gitworker-fd631e3ffbc6f2b268f6b.js:2
s @ gitworker-fd631e3ffbc6f2b268f6b.js:2
Promise.then (async)
u @ gitworker-fd631e3ffbc6f2b268f6b.js:2
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
d @ gitworker-fd631e3ffbc6f2b268f6b.js:2
value @ gitworker-fd631e3ffbc6f2b268f6b.js:2
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
c @ gitworker-fd631e3ffbc6f2b268f6b.js:2
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
forEach.e.<computed> @ gitworker-fd631e3ffbc6f2b268f6b.js:2
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
w @ gitworker-fd631e3ffbc6f2b268f6b.js:2
clone @ gitworker-fd631e3ffbc6f2b268f6b.js:2
e.onCall @ index.js:61
(anonymous) @ index.js:16
client-94d5e987bc253fae685eb.js:2 GitWorkerService: cloned https://github.com/dazjean/srejs-example-umajs.git master
client-94d5e987bc253fae685eb.js:2 Uncaught (in promise) TypeError: v.unlink is not a function
    at client-94d5e987bc253fae685eb.js:2
    at u (client-94d5e987bc253fae685eb.js:2)
    at Generator._invoke (client-94d5e987bc253fae685eb.js:2)
    at Generator.E.forEach.e.<computed> [as throw] (client-94d5e987bc253fae685eb.js:2)
    at s (client-94d5e987bc253fae685eb.js:2)
    at nrWrapper (srejs-example-umajs?file=package.json:8)
(anonymous) @ client-94d5e987bc253fae685eb.js:2
u @ client-94d5e987bc253fae685eb.js:2
(anonymous) @ client-94d5e987bc253fae685eb.js:2
E.forEach.e.<computed> @ client-94d5e987bc253fae685eb.js:2
s @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
Promise.then (async)
(anonymous) @ srejs-example-umajs?file=package.json:8
c @ client-94d5e987bc253fae685eb.js:2
a @ client-94d5e987bc253fae685eb.js:2
nrWrapper @ srejs-example-umajs?file=package.json:8
gitworker-fd631e3ffbc6f2b268f6b.js:2 StackblitzFsGit addAll err ResolveRefError: Could not resolve reference "refs/heads/master".
    at https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:163460
    at c (https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:105207)
    at Generator._invoke (https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:104995)
    at Generator.forEach.e.<computed> [as next] (https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:105630)
    at C (https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:115110)
    at o (https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:115313)
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
Promise.catch (async)
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
c @ gitworker-fd631e3ffbc6f2b268f6b.js:2
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
forEach.e.<computed> @ gitworker-fd631e3ffbc6f2b268f6b.js:2
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
d @ gitworker-fd631e3ffbc6f2b268f6b.js:2
value @ gitworker-fd631e3ffbc6f2b268f6b.js:2
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
c @ gitworker-fd631e3ffbc6f2b268f6b.js:2
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
forEach.e.<computed> @ gitworker-fd631e3ffbc6f2b268f6b.js:2
(anonymous) @ gitworker-fd631e3ffbc6f2b268f6b.js:2
w @ gitworker-fd631e3ffbc6f2b268f6b.js:2
addAll @ gitworker-fd631e3ffbc6f2b268f6b.js:2
e.onCall @ index.js:61
(anonymous) @ index.js:16
gitworker-fd631e3ffbc6f2b268f6b.js:2 StackblitzFsGit statusList err ResolveRefError: Could not resolve reference "refs/heads/master".
    at https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:163460
    at c (https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:105207)
    at Generator._invoke (https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:104995)
    at Generator.forEach.e.<computed> [as next] (https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:105630)
    at C (https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:115110)
    at o (https://c.staticblitz.com/assets/gitworker-fd631e3ffbc6f2b268f6b.js:2:115313)
```

**Comment by dazjean** [comment]
**network tab**
![image](https://user-images.githubusercontent.com/10277671/119291016-4edeeb80-bc80-11eb-9d85-807c39be75a3.png)

**Comment by dazjean** [comment]
dazjean — 今天11:11
有一个特别的配置，在npm install 安装后调用了postinstall钩子去执行了typescript的编译。  感觉这会是一个问题的关键
There is a special configuration. After the installation of NPM install, the postinstall hook is invoked to execute typescript compilation. It feels like this is going to be the key to a problem
MEE6
机器人
 — 今天11:11
GG @dazjean, you just advanced to level 1!
eric — 今天11:12
yeah postinstall won't execute, but that shouldn't halt the installation though
there also appears to be an error with our git integration (which is very buggy atm, fixes should be going out next week)
if you fork that project, and hit refresh on the new project, does it install fine?
wondering if the git integration is messing with the install somehow

**Comment by KwintenP** [comment]
Seems like a bug indeed!

🙏 for reporting!

**Comment by jrvidal** [comment]
@dazjean I can't reproduce it anymore, it looks fixed to me! Please feel free to reopen or comment if you find further issues.
