### ISSUE TITLE
SvelteKit - Failed to run start command

### ISSUE THREAD

**Issue by lukasbelka** [stackblitz/webcontainer-core#803]
### Describe the bug

 Container did not start at all with the following error message:

Error: Rename your server hook file from src/hooks.js to src/hooks.server.js (because there's also client hooks now). See the PR for more information: https://github.com/sveltejs/kit/pull/6586
    at eval (file:///home/projects/sveltejs-kit-template-default-umtnmq/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:341:13)
    at call (file:///home/projects/sveltejs-kit-template-default-umtnmq/node_modules/vite/dist/node/chunks/dep-665b0112.js:48376:7)
    at next (file:///home/projects/sveltejs-kit-template-default-umtnmq/node_modules/vite/dist/node/chunks/dep-665b0112.js:48320:5)
    at viteServeRawFsMiddleware (file:///home/projects/sveltejs-kit-template-default-umtnmq/node_modules/vite/dist/node/chunks/dep-665b0112.js:37123:13)
    at call (file:///home/projects/sveltejs-kit-template-default-umtnmq/node_modules/vite/dist/node/chunks/dep-665b0112.js:48376:7)
    at next (file:///home/projects/sveltejs-kit-template-default-umtnmq/node_modules/vite/dist/node/chunks/dep-665b0112.js:48320:5)
    at viteTransformMiddleware (file:///home/projects/sveltejs-kit-template-default-umtnmq/node_modules/vite/dist/node/chunks/dep-665b0112.js:60318:20)
    at call (file:///home/projects/sveltejs-kit-template-default-umtnmq/node_modules/vite/dist/node/chunks/dep-665b0112.js:48376:7)
    at next (file:///home/projects/sveltejs-kit-template-default-umtnmq/node_modules/vite/dist/node/chunks/dep-665b0112.js:48320:5)
    at next (file:///home/projects/sveltejs-kit-template-default-umtnmq/node_modules/vite/dist/node/chunks/dep-665b0112.js:48298:14)

### Link to the blitz that caused the error

https://stackblitz.com/edit/sveltejs-kit-template-default-s955oj?file=README.md&terminal=dev

### Steps to reproduce

1. Go to Dashboard
2. Create a new Project in the Fullstack tab
3. Click on Svelte

### Expected behavior

A ready to start Svelte project should be available

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 91.0
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
performance.memory = undefined
Hash = a1e315a41ec6498e2c2758b32fbf437db67b244b
```

**Comment by fvsch** [comment]
Thanks for the report @lukasbelka!

This looks like an upstream issue with SvelteKit's default project. I can also reproduce locally. I reported the issue in the SvelteKit repo, and we'll try to get a fix quicky.

**Comment by fvsch** [comment]
In the meantime, to get a working project, you can:

- fix the file naming issue as reported in the error;
- or downgrade to `"@sveltejs/kit": "1.0.0-next.476"` in package.json (requires to run `npm install` and `npm run dev` again, or saving the project and reloading the page).

**Comment by lukasbelka** [comment]
Thank you for the prompt reply @fvsch. I did that before and subsequently the "todos" page showed an 500 error-message. I'am not sure in which extend the whole project is affected then - do you have any idea about it?

**Comment by fvsch** [comment]
Hmm no, I don't know how many changes are required to make it work. Maybe best to wait for the SvelteKit team to update their starter template, and to downgrade the SvelteKit version in the meantime.

**Comment by fvsch** [comment]
The SvelteKit team fixed the issue upstream, and the SvelteKit starter on StackBlitz now works again. Thanks again for the heads up @lukasbelka.
