### ISSUE TITLE
Codeflow: Multiple issues with github.com/nrwl/nx

### ISSUE THREAD

**Issue by cmgriffing** [stackblitz/webcontainer-core#833]
### Describe the bug

The first load caused a "Failed to resolve dependencies" error.

The second attempt installed dependencies fine and then died trying to start a project:

```
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Object.findPagesDir (/home/nrwl/nx/node_modules/next/dist/lib/find-pages-dir.js:42:19)
    at new DevServer (/home/nrwl/nx/node_modules/next/dist/server/dev/next-dev-server.js:107:66)
    at NextServer.createServer (/home/nrwl/nx/node_modules/next/dist/server/next.js:137:20)
    at eval (/home/nrwl/nx/node_modules/next/dist/server/next.js:149:42)
    at async NextServer.prepare (/home/nrwl/nx/node_modules/next/dist/server/next.js:127:24)
    at async eval (/home/nrwl/nx/node_modules/next/dist/cli/next-dev.js:141:9)
```

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/nrwl/nx

### Steps to reproduce

No changes to the code have been made. The project has just been loaded and fails at the install/setup phase.

### Expected behavior

Installation and starting the project would succeed.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 781d7336116100a3cea72283913b570818ac125e
WebContainer = ea2f6b48b77806aba8e6fe3b6311530cc7674f64

Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 125293390,
  "usedJSHeapSize": 121730214,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

My guess is that this is a broader issue with nx workspaces or workspaces in general. (not certain though)

Looking closer, I noticed this:
```
info security We found `install` scripts which turbo skips for security reasons. For more information see https://turbo.sh/install-scripts.
├─ @napi-rs/canvas-linux-arm64-gnu@0.1.30
├─ @napi-rs/canvas-linux-arm64-musl@0.1.30
├─ @napi-rs/canvas-linux-x64-gnu@0.1.30
├─ @napi-rs/canvas-linux-x64-musl@0.1.30
├─ @nestjs/core@9.1.4
├─ @parcel/watcher@2.0.4
├─ @swc/core@1.3.7
├─ core-js@3.25.5
├─ core-js-pure@3.25.5
├─ cypress@9.7.0
├─ es5-ext@0.10.62
├─ esbuild@0.15.5
├─ nx@14.8.3
└─ weak-napi@2.0.2
```

**Comment by jrvidal** [comment]
:wave: We're closing this due to inactivity. Please, feel free to open a new one if you're still encountering any errors.
