### ISSUE TITLE
BUG: next/image doesn't work as it fails to install node Sharp

### ISSUE THREAD

**Issue by deadcoder0904** [stackblitz/webcontainer-core#85]
**Describe the bug**
I am trying to use `next/image` but it doesn't work as it fails to install node Sharp

I get the following error:

```bash
Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /projects/nextjs-image-full-bleed/node_modules/sharp/lib/constructor.js
- /projects/nextjs-image-full-bleed/node_modules/sharp/lib/index.js
- /projects/nextjs-image-full-bleed/node_modules/next/dist/next-server/server/image-optimizer.js
- /projects/nextjs-image-full-bleed/node_modules/next/dist/next-server/server/next-server.js
- /projects/nextjs-image-full-bleed/node_modules/next/dist/server/next.js
- /projects/nextjs-image-full-bleed/node_modules/next/dist/server/lib/start-server.js
- /projects/nextjs-image-full-bleed/node_modules/next/dist/cli/next-dev.js
- /projects/nextjs-image-full-bleed/node_modules/next/dist/bin/next

- Run "npm rebuild --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.eval (/projects/nextjs-image-full-bleed/node_modules/sharp/lib/constructor.js:34:9)
    at Object.function (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19819)
    at Module._compile (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187549)
    at Object.Module._extensions..js (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187908)
    at Module.load (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:185988)
    at Function.Module._load (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:183564)
    at Module.require (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:186304)
    at i (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:484674)
    at _0x1e5cfd (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19724)
    at Object.eval (/projects/nextjs-image-full-bleed/node_modules/sharp/lib/index.js:3:15)
    at Object.function (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19819)
    at Module._compile (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187549)
    at Object.Module._extensions..js (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187908)
    at Module.load (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:185988)
    at Function.Module._load (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:183564)
    at Module.require (https://nextjs-image-full-bleed.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:186304)
```

**Reproduction**

# next.config.js

```js
module.exports = {
  images: {
    domains: ['images.unsplash.com']
  }
};
```

# index.js

```js
import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div className="grid--wrapper">
      <Head>
        <title>Next Image Full Bleed Layout</title>
      </Head>
      <h1>Next Image Full Bleed Layout</h1>
      <Image
        src="https://images.unsplash.com/photo-1494587351196-bbf5f29cff42?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1651&q=80"
        layout="fill"
      />
    </div>
  );
}
```

**Link to the blitz that caused the error**
https://stackblitz.com/edit/nextjs-image-full-bleed

**Expected behavior**
It should work

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 121807022,
  usedJSHeapSize: 113074970,
  jsHeapSizeLimit: 2172649472
}

**Comment by KwintenP** [comment]
HI, 

This is a bug indeed. We are working on providing wasm polyfills for packages like sharp and imagemin, which are unable to run in the browser. This fix hasn't landed yet though.

Aside from that, NextJS actually replaced the sharp dependency with a wasm version in `10.0.8`. Which means that bumping to that version, your example actually works. (https://stackblitz.com/edit/nextjs-image-full-bleed-ryzjan?file=pages%2Findex.js).

Let me know if you run into more issues.

**Comment by deadcoder0904** [comment]
@KwintenP you guys need to update the Next.js version on the homepage boilerplate then :)

**Comment by KwintenP** [comment]
Totally agree! This should actually be updated in the next day or two!

**Comment by KwintenP** [comment]
Updated!
