### ISSUE TITLE
node-test produces TypeError: `prepareStackTrace cannot be redefined`

### ISSUE THREAD

**Issue by FossPrime** [stackblitz/webcontainer-core#881]
### Describe the bug

When using the `node-test` package, the user will get an error saying:

```
TypeError: Cannot redefine property: prepareStackTrace
    at _0x1ae56f.defineProperty (<anonymous>)
    at eval (/home/FossPrime/feathers-nosql/node_modules/.pnpm/node-test@1.4.6/node_modules/node-test/lib/traces.js:2:2297)
```

[node-test](https://www.npmjs.com/package/node-test) shims the [Node 18 Test Runner](https://nodejs.org/docs/latest-v18.x/api/test.html) functionality into Node 16,

### Link to the blitz that caused the error

- StackBlitz Classic https://stackblitz.com/edit/bug-sb-wc-881?file=package.json
- CodeFlow https://stackblitz.com/~/github.com/FossPrime/bug-sb-wc-881

### Steps to reproduce

Run `npm run test`

### Expected behavior

```
~/feathers-nosql $ npm run test

> feathers-nosql@0.0.0 test
> npx pnpx tsx test/index.test.ts

.../share/pnpm/store/v3/tmp/dlx-2332     |  +10 +
Packages are copied from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/fossprime/.local/share/pnpm/store/v3
  Virtual store is at:             ../.local/share/pnpm/store/v3/tmp/dlx-2332/node_modules/.pnpm
.../share/pnpm/store/v3/tmp/dlx-2332     | Progress: resolved 32, reused 10, downloaded 0, added 10, done
~/feathers-nosql $
```

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

Correct output on baremetal/cloudshell:
![Screenshot 2022-10-28 17 55 48](https://user-images.githubusercontent.com/876076/198747984-88ec38a5-53c2-4a42-8de7-0f54fd646080.png)

<details>
<summary>CodeFlow stack Trace</summary>

~/FossPrime/feathers-nosql master 6s
❯ pnpx tsx test/index.test.ts
.../share/pnpm/store/v3/tmp/dlx-51       |  +10 +
.../share/pnpm/store/v3/tmp/dlx-51       | Progress: resolved 32, reused 10, downloaded 0, added 10, done
TypeError: Cannot redefine property: prepareStackTrace
    at _0x1ae56f.defineProperty (<anonymous>)
    at eval (/home/FossPrime/feathers-nosql/node_modules/.pnpm/node-test@1.4.6/node_modules/node-test/lib/traces.js:2:2297)
    at Object.eval (/home/FossPrime/feathers-nosql/node_modules/.pnpm/node-test@1.4.6/node_modules/node-test/lib/traces.js:3:3)
    at Object.function (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15:141204)
    at Module._compile (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:219079)
    at Object.v (/home/.local/share/pnpm/store/v3/tmp/dlx-51/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.0/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:976)
    at Module.load (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:217769)
    at Module._load (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:215340)
    at Module.require (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:218087)
    at i (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:415284)
    at _0x29562e (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15:140573)
    at eval (/home/FossPrime/feathers-nosql/node_modules/.pnpm/node-test@1.4.6/node_modules/node-test/lib/Context.js:2:141)
    at Object.eval (/home/FossPrime/feathers-nosql/node_modules/.pnpm/node-test@1.4.6/node_modules/node-test/lib/Context.js:3:3)
    at Object.function (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15:141204)
    at Module._compile (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:219079)
    at Object.v (/home/.local/share/pnpm/store/v3/tmp/dlx-51/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.0/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:976)
    at Module.load (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:217769)
    at Module._load (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:215340)
    at Module.require (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:218087)
    at i (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:415284)
    at _0x29562e (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15:140573)
    at eval (/home/FossPrime/feathers-nosql/node_modules/.pnpm/node-test@1.4.6/node_modules/node-test/lib/Suite.js:2:128)
    at Object.eval (/home/FossPrime/feathers-nosql/node_modules/.pnpm/node-test@1.4.6/node_modules/node-test/lib/Suite.js:3:3)
    at Object.function (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15:141204)
    at Module._compile (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:219079)
    at Object.v (/home/.local/share/pnpm/store/v3/tmp/dlx-51/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.0/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:976)
    at Module.load (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:217769)
    at Module._load (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:215340)
    at _0x1fd5a3.executionFunctionOrLineOffset (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:983452)
    at _0x1fd5a3._evaluate (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15:293788)
    at _0x1fd5a3._evaluate (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15:293916)
    at async ModuleJob.run (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:987338)
    at async Promise.all (index 0)
    at async ESMLoader.import (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:1209044)
    at async i.loadESM (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:246623)
    at async handleMainPromise (https://feathers-nosql.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:989053)
 ERROR  Command failed with exit code 1: /home/.local/share/pnpm/store/v3/tmp/dlx-51/node_modules/.bin/tsx test/index.test.ts

pnpm: Command failed with exit code 1: /home/.local/share/pnpm/store/v3/tmp/dlx-51/node_modules/.bin/tsx test/index.test.ts
    at makeError (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:22439:17)
    at handlePromise (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:23010:33)
    at async Object.handler [as dlx] (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:188121:7)
    at async eval (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:195411:21)
    at async main (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:195382:34)
    at async runPnpm (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:195576:5)
    at async eval (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:195568:7)

</details>

### Platform

```
Version = 1.67.0
Hash = 35b869fee6c097380f8b2e33563ab4a16c08f57b
WebContainer = ea2f6b48b77806aba8e6fe3b6311530cc7674f64

Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87551751,
  "usedJSHeapSize": 84351271,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Node 18 would help provide a good workaround.

**Comment by FossPrime** [comment]
Something's off about this.
