### ISSUE TITLE
`node:http2` throws on use

### ISSUE THREAD

**Issue by penalosa** [stackblitz/webcontainer-core#887]
### Describe the bug

Unexpected errors when using the `node:http2` module—it throws on use.

### Link to the blitz that caused the error

https://stackblitz.com/edit/cloudflare-templates-bx6w92?file=test.mjs

### Steps to reproduce

Run the following file with `node test.mjs`

```js
//test.mjs
import { connect } from 'node:http2';
connect('https://example.com');
```

The stacktrace:

```
Error: i.consume is not a function
    at async ESMLoader.import (https://cloudflare-templates-bx6w92.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:1209044)
    at async i.loadESM (https://cloudflare-templates-bx6w92.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:246623)
    at async handleMainPromise (https://cloudflare-templates-bx6w92.w-credentialless.staticblitz.com/blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:989053)
```

### Expected behavior

I'd expect this method not to throw. However, given it's a browser environment, I think it might not be possible to support—in that case I would expect a clearer error message.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 106

**Comment by jrvidal** [comment]
Closing in favor of https://github.com/stackblitz/webcontainer-core/issues/126
