### ISSUE TITLE
Web Publisher can't run start command

### ISSUE THREAD

**Issue by michaelrkn** [stackblitz/webcontainer-core#890]
### Describe the bug

I tried to edit https://stackblitz.com/~/github.com/supabase/supabase/edit/master/apps/reference/docs/guides/cli.mdx. Booting WebContainer and Installing Dependencies succeeded but Running Start Command failed.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/supabase/supabase/edit/master/apps/reference/docs/guides/cli.mdx

### Steps to reproduce

Go to https://stackblitz.com/~/github.com/supabase/supabase/edit/master/apps/reference/docs/guides/cli.mdx. It says "Failed to run start command".

### Expected behavior

It should succeed in running start command.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

Chrome Version 106.0.5249.119 (Official Build) (arm64)

### Additional context

Chrome console output:

```
fetch.worker.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6 Retrying to fetch dependencies
fetchDependencies @ fetch.worker.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6
await in fetchDependencies (async)
fetchDependencies @ fetch.worker.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6
_0x10fa5b @ fetch.worker.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
publisher-3cedeaf6ffeba.js:2 Couldn't read /home/supabase/supabase/.stackblitz/config.json. ENOENT: no such file or directory, readFile '/home/supabase/supabase/.stackblitz/config.json'
(anonymous) @ publisher-3cedeaf6ffeba.js:2
await in (anonymous) (async)
(anonymous) @ publisher-3cedeaf6ffeba.js:2
t @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
await in (anonymous) (async)
(anonymous) @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
await in (anonymous) (async)
(anonymous) @ publisher-3cedeaf6ffeba.js:2
ca @ publisher-3cedeaf6ffeba.js:2
xc @ publisher-3cedeaf6ffeba.js:2
t.unstable_runWithPriority @ publisher-3cedeaf6ffeba.js:2
$i @ publisher-3cedeaf6ffeba.js:2
Sc @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
j @ publisher-3cedeaf6ffeba.js:2
k.port1.onmessage @ publisher-3cedeaf6ffeba.js:2
publisher-3cedeaf6ffeba.js:2 Couldn't read /home/supabase/supabase/.stackblitzrc. ENOENT: no such file or directory, readFile '/home/supabase/supabase/.stackblitzrc'
(anonymous) @ publisher-3cedeaf6ffeba.js:2
await in (anonymous) (async)
(anonymous) @ publisher-3cedeaf6ffeba.js:2
t @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
await in (anonymous) (async)
(anonymous) @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
await in (anonymous) (async)
(anonymous) @ publisher-3cedeaf6ffeba.js:2
ca @ publisher-3cedeaf6ffeba.js:2
xc @ publisher-3cedeaf6ffeba.js:2
t.unstable_runWithPriority @ publisher-3cedeaf6ffeba.js:2
$i @ publisher-3cedeaf6ffeba.js:2
Sc @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
j @ publisher-3cedeaf6ffeba.js:2
k.port1.onmessage @ publisher-3cedeaf6ffeba.js:2
publisher-3cedeaf6ffeba.js:2 Couldn't read /home/supabase/supabase/pnpm-workspace.yaml. ENOENT: no such file or directory, readFile '/home/supabase/supabase/pnpm-workspace.yaml'
(anonymous) @ publisher-3cedeaf6ffeba.js:2
await in (anonymous) (async)
(anonymous) @ publisher-3cedeaf6ffeba.js:2
t @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
await in (anonymous) (async)
(anonymous) @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
await in (anonymous) (async)
(anonymous) @ publisher-3cedeaf6ffeba.js:2
ca @ publisher-3cedeaf6ffeba.js:2
xc @ publisher-3cedeaf6ffeba.js:2
t.unstable_runWithPriority @ publisher-3cedeaf6ffeba.js:2
$i @ publisher-3cedeaf6ffeba.js:2
Sc @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
j @ publisher-3cedeaf6ffeba.js:2
k.port1.onmessage @ publisher-3cedeaf6ffeba.js:2
blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15 [Contextify] [WARNING] running source code in new context
(anonymous) @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
_0x31d04f @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
runInContext @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
runInContext @ vm.js:139
runInNewContext @ vm.js:144
runInNewContext @ vm.js:298
(anonymous) @ repl.js:193
𝐰𝐜_0x599c @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6
_0x532f9f @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8
_0x5e9737 @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
(anonymous) @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
compileForInternalLoader @ loaders.js:312
compileForPublicLoader @ loaders.js:252
loadNativeModule @ helpers.js:49
Module._load @ loader.js:804
Module.require @ loader.js:1005
i @ helpers.js:102
_0x29562e @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
eval @ jsh:6
r @ jsh:6
eval @ jsh:6
r @ jsh:6
eval @ jsh:6
r @ jsh:6
eval @ jsh:6
Promise.then (async)
eval @ jsh:6
eval @ jsh:6
r @ jsh:6
eval @ jsh:6
eval @ jsh:6
eval @ jsh:6
eval @ jsh:6
function @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
Module._compile @ loader.js:1103
Module._extensions..js @ loader.js:1157
Module.load @ loader.js:981
Module._load @ loader.js:822
executeUserEntryPoint @ run_main.js:77
𝐰𝐜_0x599c @ run_main_module.js:17
_0x532f9f @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8
_0x5e9737 @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
_0x3d478e @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:34
run @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:34
await in run (async)
_0x338297 @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8
blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8 Uncaught (in promise) Error: Failed running "npm run dev" command
    at publisher-3cedeaf6ffeba.js:2:1653259
    at Object.output (publisher-3cedeaf6ffeba.js:2:1655405)
    at output (publisher-3cedeaf6ffeba.js:2:1655507)
    at Function._0xc92c67 (webcontainer.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:140833)
    at MessagePort._0x17db5b (webcontainer.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:110679)
    at MessagePort.nrWrapper (cli.mdx:8:29785)
deserialize @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8
_0x555fbd @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8
Promise.then (async)
apply @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8
(anonymous) @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
(anonymous) @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
_notifyListeners @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
emitSelf @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
_emitOutput @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
_onMessage @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
_0x37ee12.<computed> @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
publisher-3cedeaf6ffeba.js:2 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
e._parseColor @ publisher-3cedeaf6ffeba.js:2
e.setTheme @ publisher-3cedeaf6ffeba.js:2
t.open @ publisher-3cedeaf6ffeba.js:2
e.open @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
ca @ publisher-3cedeaf6ffeba.js:2
xc @ publisher-3cedeaf6ffeba.js:2
t.unstable_runWithPriority @ publisher-3cedeaf6ffeba.js:2
$i @ publisher-3cedeaf6ffeba.js:2
Sc @ publisher-3cedeaf6ffeba.js:2
ac @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
t.unstable_runWithPriority @ publisher-3cedeaf6ffeba.js:2
$i @ publisher-3cedeaf6ffeba.js:2
Zi @ publisher-3cedeaf6ffeba.js:2
Ji @ publisher-3cedeaf6ffeba.js:2
cc @ publisher-3cedeaf6ffeba.js:2
notify @ publisher-3cedeaf6ffeba.js:2
t.notifyNestedSubs @ publisher-3cedeaf6ffeba.js:2
t.handleChangeWrapper @ publisher-3cedeaf6ffeba.js:2
y @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
x @ publisher-3cedeaf6ffeba.js:2
output @ publisher-3cedeaf6ffeba.js:2
output @ publisher-3cedeaf6ffeba.js:2
_0xc92c67 @ webcontainer.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6
_0x17db5b @ webcontainer.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6
nrWrapper @ cli.mdx:8
blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8 Uncaught (in promise) Error: Failed running "npm run dev" command
    at publisher-3cedeaf6ffeba.js:2:1653259
    at Object.output (publisher-3cedeaf6ffeba.js:2:1655405)
    at output (publisher-3cedeaf6ffeba.js:2:1655507)
    at Function._0xc92c67 (webcontainer.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:140833)
    at MessagePort._0x17db5b (webcontainer.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6:110679)
    at MessagePort.nrWrapper (cli.mdx:8:29785)
deserialize @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8
_0x555fbd @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8
Promise.then (async)
apply @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:8
(anonymous) @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
(anonymous) @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
_notifyListeners @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
emitSelf @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
_emitOutput @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
_onMessage @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
_0x37ee12.<computed> @ blitz.a0ea75dd36396805bd36e49d0b54d86602583e15.js:15
publisher-3cedeaf6ffeba.js:2 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
t._drawToCache @ publisher-3cedeaf6ffeba.js:2
t.draw @ publisher-3cedeaf6ffeba.js:2
e._drawChars @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
t._forEachCell @ publisher-3cedeaf6ffeba.js:2
t._drawForeground @ publisher-3cedeaf6ffeba.js:2
t.onGridChanged @ publisher-3cedeaf6ffeba.js:2
t.renderRows @ publisher-3cedeaf6ffeba.js:2
t._renderRows @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
e._innerRefresh @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
nrWrapper @ cli.mdx:8
requestAnimationFrame (async)
nrWrapper @ cli.mdx:8
e.refresh @ publisher-3cedeaf6ffeba.js:2
t.refreshRows @ publisher-3cedeaf6ffeba.js:2
t.refresh @ publisher-3cedeaf6ffeba.js:2
t.open @ publisher-3cedeaf6ffeba.js:2
e.open @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
ca @ publisher-3cedeaf6ffeba.js:2
xc @ publisher-3cedeaf6ffeba.js:2
t.unstable_runWithPriority @ publisher-3cedeaf6ffeba.js:2
$i @ publisher-3cedeaf6ffeba.js:2
Sc @ publisher-3cedeaf6ffeba.js:2
ac @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
t.unstable_runWithPriority @ publisher-3cedeaf6ffeba.js:2
$i @ publisher-3cedeaf6ffeba.js:2
Zi @ publisher-3cedeaf6ffeba.js:2
Ji @ publisher-3cedeaf6ffeba.js:2
cc @ publisher-3cedeaf6ffeba.js:2
notify @ publisher-3cedeaf6ffeba.js:2
t.notifyNestedSubs @ publisher-3cedeaf6ffeba.js:2
t.handleChangeWrapper @ publisher-3cedeaf6ffeba.js:2
y @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
(anonymous) @ publisher-3cedeaf6ffeba.js:2
x @ publisher-3cedeaf6ffeba.js:2
output @ publisher-3cedeaf6ffeba.js:2
output @ publisher-3cedeaf6ffeba.js:2
_0xc92c67 @ webcontainer.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6
_0x17db5b @ webcontainer.a0ea75dd36396805bd36e49d0b54d86602583e15.js:6
nrWrapper @ cli.mdx:8
```

**Comment by sylwiavargas** [comment]
Hi @michaelrkn! Thank you for the report.
We'll look into it next week 👀

**Comment by d3lm** [comment]
Thanks for the report!

I tried to open your link in WebPublisher but it seems the file you're referencing doesn't exist. Can you update the link so we can try and reproduce the issue?

**Comment by sylwiavargas** [comment]
Hi Dom! I took a look and I see that the file was moved. It's now here: https://stackblitz.com/~/github.com/supabase/supabase/edit/master/apps/docs/docs/reference/cli.mdx.

While the file loads now, it takes a longer while because of the number of dependencies, and the preview is blocked because of the native binaries:

> docs:dev:  error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
> www:dev:  info  - Attempted to load @next/swc-linux-x64-gnu, but an error occurred: Cannot load native addon because loading addons is disabled: /home/supabase/supabase/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node

@michaelrkn - I'm so sorry it took us such a long time to get back to you on this. Over this time, Web Publisher and Codeflow went through significant improvements. hat being said, the `native addon` error is still an obstacle for this integration - you can read more about it [here](https://webcontainers.io/guides/troubleshooting#cannot-load-native-addon-error).

**Comment by sylwiavargas** [comment]
Actually, I just talked to Dom and SWC is compiled to Wasm - in the more recent version, Next.js automatically installs `swc-wasm`.

This means that if Supabase depends on Next.js then you could either add `swc-wasm` to the dependencies, or update Next.js to a more recent version.

I hope this helps!

**Comment by jrvidal** [comment]
https://github.com/stackblitz/webcontainer-core/issues/870#issuecomment-1489268961

**Comment by jrvidal** [comment]
👋 We're closing this due to inactivity. Please, feel free to open a new one if you're still encountering any errors.
