### ISSUE TITLE
e.close ist not a function

### ISSUE THREAD

**Issue by crearis** [stackblitz/webcontainer-core#897]
### Describe the bug

Project crashes after some seconds in preview-window

### Link to the blitz that caused the error

https://stackblitz.com/edit/crearis-starter

### Steps to reproduce

1. Start the project
2. wait until it's completely launched in Preview
3. wait some seconds ... and it will crash with this message:

 ERROR  [uncaughtException] e.close is not a function 
  at Immediate.closeParserInstance (https://crearis-starter.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:6:371524)
  at processImmediate (https://crearis-starter.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:6:307089)
  at Object.callback (https://crearis-starter.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:15:258712)
  at https://crearis-starter.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:15:339215
  at _0x3600ae (https://crearis-starter.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:15:339249)
  at _0x25aacd.<computed>.<computed> (https://crearis-starter.w-credentialless.staticblitz.com/blitz.bba8d0a5a025db74852964077975228459d6d20b.js:15:339443)

### Expected behavior

project should run stable

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 107.0.0.0
Major version = 107
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87263749,
  "usedJSHeapSize": 81935861,
  "jsHeapSizeLimit": 4294705152
}
Hash = bba8d0a5a025db74852964077975228459d6d20b
```

**Comment by d3lm** [comment]
Hey there! Thanks for reporting this issue. I can confirm that this is a bug on our side. We'll post an update here once this is fixed.

**Comment by Nemikolh** [comment]
Hi @crearis ! :wave: 

Thanks for waiting! I believe this issue is fixed. :tada: I didn't ran into any issues while looking at your blitz, so I think you're good to go. :ship:
