### ISSUE TITLE
WritableStream is not defined

### ISSUE THREAD

**Issue by gederer** [stackblitz/webcontainer-core#932]
### Describe the bug

I have a Qwik application running on Stack Blitz. When I click on a link to navigate from the home page to a different page, I get the following error output:
```
❯ yarn install && yarn run dev
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.16s.
yarn run v1.22.19
$ vite --mode ssr

  VITE v4.0.1  ready in 2434 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
11:08:16 AM [vite] Internal server error: WritableStream is not defined
      at Object.getWritableStream (file:///home/projects/zzmiwnkjw.github/node_modules/@builder.io/qwik-city/vite/index.cjs:22786:22)
      at Object.getWritableStream (file:///home/projects/zzmiwnkjw.github/node_modules/@builder.io/qwik-city/vite/index.cjs:22621:42)
      at renderQData (file:///home/projects/zzmiwnkjw.github/node_modules/@builder.io/qwik-city/vite/index.cjs:22933:30)
      at async Object.next (file:///home/projects/zzmiwnkjw.github/node_modules/@builder.io/qwik-city/vite/index.cjs:22511:9)
      at async runNext (file:///home/projects/zzmiwnkjw.github/node_modules/@builder.io/qwik-city/vite/index.cjs:22679:5)
      at async eval (file:///home/projects/zzmiwnkjw.github/node_modules/@builder.io/qwik-city/vite/index.cjs:23059:11)
```
My app behaves correctly when I run it locally.

### Link to the blitz that caused the error

https://stackblitz.com/github/gederer/server-actions-play?file=README.md

### Steps to reproduce

1. Visit the blitz, above
2. Click the provided `actions` link

### Expected behavior

The browser should navigate to the actions page, which looks like:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/705111/210439089-e332f4dc-b661-4f69-a53d-6fbf277c5ff6.png">

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: macOS
- Browser: Chrome
- Version 108.0.5359.124 (Official Build) (x86_64)

**Comment by SamVerschueren** [comment]
This should be working now. Thanks for creating the issue 🙏 . If you run into other issues, let us know!
