### ISSUE TITLE
zlib.gunzip throw Error: incorrect header check on some gz files

### ISSUE THREAD

**Issue by azu** [stackblitz/webcontainer-core#973]
### Describe the bug

When I use `zlib.gunzip` in Web Container, it can not decode some gzip file by following error

> Error: cc.dat.gz Error: incorrect header check

I met this issue when I used [kuromoji.js](https://github.com/takuyaa/kuromoji.js).

- Web Container: https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-vrxpkk?file=package.json,index.mjs
- Repo: https://github.com/azu/webcontainer-gzip-issue

```
❯ npm test
$ node index.mjs
Success: base.dat.gz
Error: cc.dat.gz Error: incorrect header check
    at InternalError (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:291731)
    at zlibOnError (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:1719050)
    at Zlib.prototype._error (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:394064)
    at Zlib.prototype._checkError (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:393775)
    at Zlib.prototype._after (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:393850)
    at Zlib.prototype._write/< (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:6:392183)
    at _0x5d97a4 (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:15:150541)
    at _0x2fb6cc/< (https://stackblitzwebcontainerapistart-yeg2.w-corp.staticblitz.com/blitz.927bd077ab89da68c6338c4363cc22e79cccb4ef.js:15:150281)
    at <anonymous> (<anonymous>) {
  errno: -3,
  code: undefined
}
Success: check.dat.gz
Success: tid.dat.gz
Success: tid_map.dat.gz
Success: tid_pos.dat.gz
Success: unk.dat.gz
Success: unk_char.dat.gz
Success: unk_compat.dat.gz
Success: unk_invoke.dat.gz
Success: unk_map.dat.gz
Success: unk_pos.dat.gz
```

In Local Node.js v16.19.0

```
Success: unk_char.dat.gz
Success: unk_compat.dat.gz
Success: unk_invoke.dat.gz
Success: unk_map.dat.gz
Success: cc.dat.gz
Success: tid_map.dat.gz
Success: base.dat.gz
Success: check.dat.gz
Success: tid.dat.gz
Success: unk.dat.gz
Success: unk_pos.dat.gz
Success: tid_pos.dat.gz
```

Web Container can not decode https://github.com/takuyaa/kuromoji.js/blob/master/dict/cc.dat.gz by `zlib.gunzip`.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-vrxpkk?file=package.json,index.mjs

### Steps to reproduce

1. open https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-vrxpkk?file=package.json,index.mjs
2. run `npm test`

### Expected behavior

Success to decode cc.dat.gz.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

Webcontainer:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/19714/220484721-f0cb6821-e907-4773-874a-e6ff87892259.png">

Local

<img width="667" alt="image" src="https://user-images.githubusercontent.com/19714/220484672-4064e1b6-5f33-4c16-9dc3-76b168a7424e.png">

### Platform

- OS: macOS
- Browser: Firefox and Chrome
- Version: 110.0, 110.0.5481.100

### Additional context

Related: https://github.com/stackblitz/webcontainer-core/issues/319

**Comment by d3lm** [comment]
Hey! I can confirm that there seems to be an issue with zlib on our end. Thanks for reporting this issue.

**Comment by kirjavascript** [comment]
:wave: Hi there, this issue has been fixed and the WebContainer link posted appears to work now. 

Feel free to open another issue if there is anything else needed!
